<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mario Ervedosa, adapting Scognamiglio, Maggi and Wüthrich">
<meta name="dcterms.date" content="2026-08-31">

<title>Credit Lecture 2: Exponential Dispersion Family and Generalised Linear Models</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>



  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../lectures/lecture.css">
</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#exponential-dispersion-family-a-bit-of-theory" id="toc-exponential-dispersion-family-a-bit-of-theory" class="nav-link" data-scroll-target="#exponential-dispersion-family-a-bit-of-theory"><span class="header-section-number">2</span> Exponential dispersion family: a bit of theory</a>
  <ul class="collapse">
  <li><a href="#the-bernoulli-member" id="toc-the-bernoulli-member" class="nav-link" data-scroll-target="#the-bernoulli-member"><span class="header-section-number">2.1</span> The Bernoulli member</a></li>
  <li><a href="#deviance-loss-function" id="toc-deviance-loss-function" class="nav-link" data-scroll-target="#deviance-loss-function"><span class="header-section-number">2.2</span> Deviance loss function</a></li>
  <li><a href="#examples-of-deviance-losses" id="toc-examples-of-deviance-losses" class="nav-link" data-scroll-target="#examples-of-deviance-losses"><span class="header-section-number">2.3</span> Examples of deviance losses</a></li>
  <li><a href="#model-fitting-on-finite-samples" id="toc-model-fitting-on-finite-samples" class="nav-link" data-scroll-target="#model-fitting-on-finite-samples"><span class="header-section-number">2.4</span> Model fitting on finite samples</a></li>
  </ul></li>
  <li><a href="#model-validation-and-model-selection" id="toc-model-validation-and-model-selection" class="nav-link" data-scroll-target="#model-validation-and-model-selection"><span class="header-section-number">3</span> Model validation and model selection</a></li>
  <li><a href="#glm-regression-function" id="toc-glm-regression-function" class="nav-link" data-scroll-target="#glm-regression-function"><span class="header-section-number">4</span> GLM regression function</a>
  <ul class="collapse">
  <li><a href="#logit-link-example" id="toc-logit-link-example" class="nav-link" data-scroll-target="#logit-link-example"><span class="header-section-number">4.1</span> Logit-link example</a></li>
  <li><a href="#edf-and-the-special-canonical-link-choice" id="toc-edf-and-the-special-canonical-link-choice" class="nav-link" data-scroll-target="#edf-and-the-special-canonical-link-choice"><span class="header-section-number">4.2</span> EDF and the (special) canonical link choice</a></li>
  </ul></li>
  <li><a href="#glm-fitting-and-examples" id="toc-glm-fitting-and-examples" class="nav-link" data-scroll-target="#glm-fitting-and-examples"><span class="header-section-number">5</span> GLM fitting and examples</a>
  <ul class="collapse">
  <li><a href="#relationship-to-deviance-losses" id="toc-relationship-to-deviance-losses" class="nav-link" data-scroll-target="#relationship-to-deviance-losses"><span class="header-section-number">5.1</span> Relationship to deviance losses</a></li>
  <li><a href="#glm-example-bondora-data" id="toc-glm-example-bondora-data" class="nav-link" data-scroll-target="#glm-example-bondora-data"><span class="header-section-number">5.2</span> GLM example: Bondora data</a></li>
  <li><a href="#bernoulli-deviance-loss-in-sample-and-out-of-sample" id="toc-bernoulli-deviance-loss-in-sample-and-out-of-sample" class="nav-link" data-scroll-target="#bernoulli-deviance-loss-in-sample-and-out-of-sample"><span class="header-section-number">5.3</span> Bernoulli deviance loss: in-sample and out-of-sample</a></li>
  <li><a href="#individual-bernoulli-versus-grouped-binomial" id="toc-individual-bernoulli-versus-grouped-binomial" class="nav-link" data-scroll-target="#individual-bernoulli-versus-grouped-binomial"><span class="header-section-number">5.4</span> Individual Bernoulli versus grouped binomial</a></li>
  </ul></li>
  <li><a href="#takeaways-and-outlook" id="toc-takeaways-and-outlook" class="nav-link" data-scroll-target="#takeaways-and-outlook">Takeaways and outlook</a></li>
  <li><a href="#copyright-and-attribution" id="toc-copyright-and-attribution" class="nav-link" data-scroll-target="#copyright-and-attribution">Copyright and attribution</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Credit Lecture 2: Exponential Dispersion Family and Generalised Linear Models</h1>
<p class="subtitle lead">Deep Learning for Actuarial Modelling: a credit risk companion</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mario Ervedosa, adapting Scognamiglio, Maggi and Wüthrich </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 31, 2026</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>We develop the distributional machinery behind the PD models of the first credit lecture. The exponential dispersion family and its deviance losses are presented as in Lecture 2 of Deep Learning for Actuarial Modeling, with the Bernoulli member worked through as the running example in place of the Poisson. A logistic GLM is fitted to the Bondora modelling table, validated in-sample and out-of-sample on both a random and an out-of-time split, and the course’s offsets-versus-weights equivalence is transplanted to the equivalence between individual Bernoulli and grouped binomial fitting.</p>
  </div>
</div>


</header>


<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>The first credit lecture estimated probabilities of default (PD) informally, by empirical default rates per covariate band and by two regression models whose loss functions we simply asserted. This lecture supplies the distributional theory behind those choices. The framework is the <strong>exponential dispersion family (EDF)</strong>, the class of distributions for which maximum likelihood estimation coincides with the minimisation of an associated <strong>deviance loss</strong>. Claim counts led the insurance lectures to the Poisson member of this family. The binary default indicator leads us to the Bernoulli member, and everything in this lecture works that member through the general theory.</p>
<p>Before the theory, we recall what a good credit risk regression model should deliver. The original lecture lists eight desirable properties of actuarial regression models, and each has a direct credit reading:</p>
<ul>
<li><strong>Accuracy</strong>: the estimated PDs should be close to the true (unknown) default probabilities.</li>
<li><strong>Smoothness</strong>: PDs should vary smoothly in continuous borrower characteristics.</li>
<li><strong>Sparsity</strong>: the model should not carry covariates that do no work.</li>
<li><strong>Explainability</strong>: a declined applicant, a validator, and a supervisor will all ask why.</li>
<li><strong>Finite sample properties</strong>: estimates must be reliable at the cell sizes a portfolio actually has.</li>
<li><strong>Quantifiable uncertainty</strong>: a PD without a standard error cannot support a capital number.</li>
<li><strong>Adaptability</strong>: the model must be re-estimable as the book and the economy move.</li>
<li><strong>Regulatory compliance</strong>: rating systems used for capital face use-test and documentation requirements that constrain model form.</li>
</ul>
<p>Explainability and regulatory compliance carry more weight in credit than almost anywhere else in actuarial work, because PD models are embedded in individual lending decisions and in regulatory capital. The EDF and generalised linear model (GLM) framework of this lecture scores highly on both, which is one reason logistic regression remained the industry standard for decades. The deep learning lectures that follow have to earn their extra accuracy against this benchmark.</p>
</section>
<section id="exponential-dispersion-family-a-bit-of-theory" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Exponential dispersion family: a bit of theory</h1>
<p>The density below is written once and covers both a discrete and a continuous response, so it is worth fixing what each of those objects is before the theory starts.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Mass functions, densities and distribution functions">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Mass functions, densities and distribution functions
</div>
</div>
<div class="callout-body-container callout-body">
<p>A <strong>discrete</strong> random variable places its probability on individual outcomes, and its <strong>probability mass function</strong> records how much sits on each,</p>
<p><span class="math display">\[
p(y) = \mathbb{P}(Y = y) \ge 0,
\qquad
\sum_{y \in \mathcal{Y}} p(y) = 1 ,
\]</span></p>
<p>the sum running over the support <span class="math inline">\(\mathcal{Y}\)</span>. By contrast, a <strong>continuous</strong> random variable has no atoms, i.e.&nbsp;<span class="math inline">\(\mathbb{P}(Y = y) = 0\)</span> for every single value <span class="math inline">\(y\)</span>, so probability is carried instead by a <strong>density</strong> <span class="math inline">\(f\)</span> and recovered only over intervals,</p>
<p><span class="math display">\[
f(y) \ge 0,
\qquad
\int_{\mathbb{R}} f(y)\,\mathrm{d}y = 1,
\qquad
\mathbb{P}(a &lt; Y \le b) = \int_a^b f(y)\,\mathrm{d}y .
\]</span></p>
<p>Similarly, the <strong>cumulative distribution function</strong> accumulates either of them,</p>
<p><span class="math display">\[
F(y) = \mathbb{P}(Y \le y) = \sum_{z \le y} p(z)
\quad \text{(discrete)},
\qquad
F(y) = \mathbb{P}(Y \le y) = \int_{-\infty}^{y} f(z)\,\mathrm{d}z
\quad \text{(continuous)} ,
\]</span></p>
<p>and it is non-decreasing and right-continuous, with <span class="math inline">\(F(y) \to 0\)</span> as <span class="math inline">\(y \to -\infty\)</span> and <span class="math inline">\(F(y) \to 1\)</span> as <span class="math inline">\(y \to +\infty\)</span>. In the continuous case <span class="math inline">\(f = F'\)</span> wherever the derivative exists, so a density and a distribution function hold the same information in differential and in accumulated form. The complement <span class="math inline">\(S(y) = 1 - F(y)\)</span> is the <strong>survival function</strong>, and it is the object lecture S1 attaches its monthly hazards to.</p>
<p>Consequently both quantities the first lecture defined sit on this list. The default indicator has a mass function with two atoms,</p>
<p><span class="math display">\[
\mathbb{P}\left(D_i^{(k)} = 1 \,\middle|\, \boldsymbol{X}_i\right) = \mu_k(\boldsymbol{X}_i),
\qquad
\mathbb{P}\left(D_i^{(k)} = 0 \,\middle|\, \boldsymbol{X}_i\right) = 1 - \mu_k(\boldsymbol{X}_i) ,
\]</span></p>
<p>and the time to default <span class="math inline">\(T_i\)</span> has a distribution function whose value at the horizon is the probability of default itself,</p>
<p><span class="math display">\[
\mathrm{PD}_k(\boldsymbol{X}_i)
= \mathbb{P}\left( T_i \le k \,\middle|\, \boldsymbol{X}_i \right)
= F_{T_i \mid \boldsymbol{X}_i}(k) .
\]</span></p>
<p>A PD is therefore a conditional distribution function read at a single point, which is why moving the horizon <span class="math inline">\(k\)</span> produces a whole term structure from one distribution. Since <span class="math inline">\(T_i\)</span> is measured in whole months on book, the discrete forms above are the operative ones throughout this series, and the continuous forms are the idealisation that makes the calculus convenient.</p>
</div>
</div>
<p>A random variable <span class="math inline">\(Y\)</span> belongs to the exponential dispersion family if its density (or probability mass function) can be written as</p>
<p><span class="math display">\[
Y \sim f_{\theta}(y)
= \exp\left( \frac{y\theta - \kappa(\theta)}{\varphi / v} + c(y, \varphi/v) \right),
\]</span></p>
<p>with <strong>canonical parameter</strong> <span class="math inline">\(\theta \in \boldsymbol{\Theta} \subseteq \mathbb{R}\)</span>, <strong>cumulant function</strong> <span class="math inline">\(\kappa: \boldsymbol{\Theta} \to \mathbb{R}\)</span>, <strong>dispersion parameter</strong> <span class="math inline">\(\varphi &gt; 0\)</span> and <strong>weight</strong> (exposure, volume) <span class="math inline">\(v &gt; 0\)</span>. The cumulant function determines the member of the family, and it determines the first two moments,</p>
<p><span class="math display">\[
\mathbb{E}[Y] = \kappa'(\theta),
\qquad
\mathrm{Var}(Y) = \frac{\varphi}{v}\, \kappa''(\theta).
\]</span></p>
<p>Those two formulas are asserted here and the callout proves them, which also explains where the cumulant function gets its name.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Moments, and the function that generates them">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Moments, and the function that generates them
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <strong><span class="math inline">\(m\)</span>th raw moment</strong> of <span class="math inline">\(Y\)</span> is <span class="math inline">\(\mathbb{E}[Y^m]\)</span>, and the <strong><span class="math inline">\(m\)</span>th central moment</strong> is <span class="math inline">\(\mathbb{E}\left[(Y - \mathbb{E}[Y])^m\right]\)</span>. The first raw moment is the mean, the second central moment is the variance, and the third and fourth central moments, standardised by the variance, give the skewness and the kurtosis. Moments are averages of powers, so each one summarises a single shape feature of the distribution.</p>
<p>The <strong>moment generating function</strong> collects all of them at once,</p>
<p><span class="math display">\[
M_Y(s) = \mathbb{E}\left[ e^{sY} \right]
= \sum_{m = 0}^{\infty} \frac{s^m}{m!} \, \mathbb{E}\left[Y^m\right] ,
\]</span></p>
<p>for <span class="math inline">\(s\)</span> in a neighbourhood of the origin on which the expectation is finite. Therefore the moments need no separate calculation. Differentiate <span class="math inline">\(m\)</span> times and evaluate at zero, which leaves one term of that series, hence <span class="math inline">\(\mathbb{E}[Y^m] = M_Y^{(m)}(0)\)</span>. Moreover, where <span class="math inline">\(M_Y\)</span> exists on an open interval around zero it pins down the distribution completely. Its logarithm <span class="math inline">\(K_Y(s) = \log M_Y(s)\)</span> is the <strong>cumulant generating function</strong>, whose derivatives at zero are the cumulants, the first two being the mean and the variance directly.</p>
<p>For an EDF member that logarithm comes out in closed form. Writing <span class="math inline">\(\psi = \varphi / v\)</span> for brevity, and reading the integral as a sum for a discrete member,</p>
<p><span class="math display">\[
M_Y(s)
= \int \exp\left( sy + \frac{y\theta - \kappa(\theta)}{\psi} + c(y, \psi) \right) \mathrm{d}y
= \exp\left( \frac{\kappa(\theta + s\psi) - \kappa(\theta)}{\psi} \right)
\int f_{\theta + s\psi}(y) \, \mathrm{d}y ,
\]</span></p>
<p>since the exponent rearranges as</p>
<p><span class="math display">\[
sy + \frac{y\theta - \kappa(\theta)}{\psi}
= \frac{y(\theta + s\psi) - \kappa(\theta + s\psi)}{\psi}
+ \frac{\kappa(\theta + s\psi) - \kappa(\theta)}{\psi} .
\]</span></p>
<p>The remaining integrand is the same family member at canonical parameter <span class="math inline">\(\theta + s\psi\)</span>, so it integrates to one for every <span class="math inline">\(s\)</span> small enough to keep <span class="math inline">\(\theta + s\psi\)</span> inside <span class="math inline">\(\boldsymbol{\Theta}\)</span>. Consequently</p>
<p><span class="math display">\[
K_Y(s) = \frac{\kappa(\theta + s\psi) - \kappa(\theta)}{\psi},
\qquad
K_Y'(s) = \kappa'(\theta + s\psi),
\qquad
K_Y''(s) = \psi \, \kappa''(\theta + s\psi) ,
\]</span></p>
<p>and setting <span class="math inline">\(s = 0\)</span> returns <span class="math inline">\(\mathbb{E}[Y] = \kappa'(\theta)\)</span> and <span class="math inline">\(\mathrm{Var}(Y) = (\varphi/v)\,\kappa''(\theta)\)</span>. The name follows, since <span class="math inline">\(\kappa\)</span> generates the cumulants of the family up to that affine change of argument.</p>
<p>In particular, the Bernoulli case is immediate, with <span class="math inline">\(\psi = 1\)</span> and <span class="math inline">\(\kappa(\theta) = \log(1 + e^{\theta})\)</span>,</p>
<p><span class="math display">\[
M_{D^{(k)}}(s) = \frac{1 + e^{\theta + s}}{1 + e^{\theta}} = 1 - \mu_k + \mu_k e^{s} ,
\]</span></p>
<p>whose two terms are the two atoms of the mass function read off as coefficients. The third cumulant is <span class="math inline">\(\kappa'''(\theta) = \mu_k (1 - \mu_k)(1 - 2\mu_k)\)</span>, so the skewness of the indicator is <span class="math inline">\((1 - 2\mu_k) / \sqrt{\mu_k (1 - \mu_k)}\)</span>, which reaches <span class="math inline">\(4.13\)</span> at a PD of 5 per cent and vanishes only at <span class="math inline">\(\mu_k = 1/2\)</span>. Consequently a handful of defaults carries much of the weight in a small cell, which is a recurring difficulty in low-default portfolios.</p>
</div>
</div>
<p>Since <span class="math inline">\(\kappa\)</span> is strictly convex on the interior of <span class="math inline">\(\boldsymbol{\Theta}\)</span>, the mean function <span class="math inline">\(\kappa'\)</span> is strictly increasing and therefore invertible. Its inverse</p>
<p><span class="math display">\[
h := (\kappa')^{-1}
\]</span></p>
<p>is called the <strong>canonical link</strong>. Hence means and canonical parameters correspond one to one, <span class="math inline">\(h(\mathbb{E}[Y]) = \theta\)</span>.</p>
<section id="the-bernoulli-member" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="the-bernoulli-member"><span class="header-section-number">2.1</span> The Bernoulli member</h2>
<p>The first lecture’s notation carries over unchanged, and this lecture keeps it. The response is the fixed-horizon default indicator <span class="math inline">\(D_i^{(k)} = \mathbf{1}\{T_i \le k\} \in \{0, 1\}\)</span> of loan <span class="math inline">\(i\)</span> over a window of <span class="math inline">\(k\)</span> months, and its conditional mean is <span class="math inline">\(\mu_k(\boldsymbol{X}_i) = \mathbb{E}\left[D_i^{(k)} \mid \boldsymbol{X}_i\right]
= \mathrm{PD}_k(\boldsymbol{X}_i)\)</span>. The horizon travels with both, since a PD means nothing without the window it was measured over, and here <span class="math inline">\(k = 12\)</span> months throughout. Where a subscript slot is already occupied, by a parameterisation <span class="math inline">\(\vartheta\)</span> or by a learning sample <span class="math inline">\(\mathcal{L}\)</span>, the window rides on the response instead of being written twice.</p>
<p>Suppressing the loan index while the distributional theory is in view, the indicator has probability mass function <span class="math inline">\(\mathbb{P}\left(D^{(k)} = y\right) = \mu_k^{y} (1 - \mu_k)^{1-y}\)</span> for <span class="math inline">\(y \in \{0,1\}\)</span>. Rewriting,</p>
<p><span class="math display">\[
\mathbb{P}\left(D^{(k)} = y\right)
= \exp\left( y \log\frac{\mu_k}{1-\mu_k} + \log(1 - \mu_k) \right)
= \exp\left( y\theta - \log(1 + e^{\theta}) \right),
\]</span></p>
<p>which is the EDF form with</p>
<p><span class="math display">\[
\theta = \log\frac{\mu_k}{1-\mu_k},
\qquad
\kappa(\theta) = \log\left(1 + e^{\theta}\right),
\qquad
\varphi = 1, \quad v = 1.
\]</span></p>
<p>The canonical parameter is the <strong>log-odds</strong> of default, an object every credit modeller already works with. Differentiating the cumulant function,</p>
<p><span class="math display">\[
\kappa'(\theta) = \frac{e^{\theta}}{1 + e^{\theta}} = \mu_k,
\qquad
\kappa''(\theta) = \mu_k (1 - \mu_k),
\]</span></p>
<p>so the mean function is the sigmoid, the variance is <span class="math inline">\(\mu_k(1-\mu_k)\)</span>, and the canonical link is the <strong>logit</strong>, <span class="math inline">\(h(\mu) = \log(\mu/(1-\mu))\)</span>. The dispersion is fixed at <span class="math inline">\(\varphi = 1\)</span>; a single binary observation carries no free variance parameter, so overdispersion belongs to aggregated default counts alone. The weight is <span class="math inline">\(v = 1\)</span> because the fixed-horizon construction of the first lecture gave every loan the same twelve-month window; its alternative exposure <span class="math inline">\(v_i = \min(T_i, k)\)</span> belongs to the hazard convention that lecture S1 takes up. This is the simplification that credit buys: where the insurance lectures carry <span class="math inline">\(v_i\)</span> through every formula as a time exposure, our formulas carry <span class="math inline">\(v_i \equiv 1\)</span> and <span class="math inline">\(\varphi = 1\)</span>, and the general theory specialises accordingly.</p>
</section>
<section id="deviance-loss-function" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="deviance-loss-function"><span class="header-section-number">2.2</span> Deviance loss function</h2>
<p>For mean estimation within the EDF, the natural loss is the <strong>deviance loss</strong></p>
<!-- REVIEW (Mario, round 2, 2 Sep 2026): mention how this meets up with the ML world.
     Answered by the callout below. -->
<p><span class="math display">\[
L(y, m)
= 2\, \frac{\varphi}{v} \left( \log f_{h(y)}(y) - \log f_{h(m)}(y) \right)
\;\geq\; 0,
\]</span></p>
<p>which compares the log-likelihood of the observation <span class="math inline">\(y\)</span> under the best possible parameter (the saturated model, canonical parameter <span class="math inline">\(h(y)\)</span>) with its log-likelihood under the estimated mean <span class="math inline">\(m\)</span>. The deviance loss is zero precisely when <span class="math inline">\(m = y\)</span>, and it is <strong>strictly consistent</strong> for mean estimation (Gneiting, 2011), which is the minimal requirement for a loss that is meant to recover conditional means.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="The same losses, under machine learning names">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The same losses, under machine learning names
</div>
</div>
<div class="callout-body-container callout-body">
<p>Machine learning practice picks a loss and reads the model off it, whereas the EDF derives the loss from an assumption about the response. Both routes arrive at the same short menu. Every named regression objective in a gradient boosting library is one of the deviance losses tabulated in the next section, wearing a different label.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>EDF member</th>
<th>boosting <code>objective</code></th>
<th>loss or metric function</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Gaussian</td>
<td><code>reg:squarederror</code>, <code>regression</code></td>
<td><code>mean_squared_error</code>, <code>nn.MSELoss</code></td>
</tr>
<tr class="even">
<td>gamma</td>
<td><code>reg:gamma</code>, <code>gamma</code></td>
<td><code>mean_gamma_deviance</code></td>
</tr>
<tr class="odd">
<td>Poisson</td>
<td><code>count:poisson</code>, <code>poisson</code></td>
<td><code>mean_poisson_deviance</code>, <code>nn.PoissonNLLLoss</code></td>
</tr>
<tr class="even">
<td>Tweedie</td>
<td><code>reg:tweedie</code>, <code>tweedie</code></td>
<td><code>mean_tweedie_deviance</code></td>
</tr>
<tr class="odd">
<td>Bernoulli</td>
<td><code>binary:logistic</code>, <code>binary</code></td>
<td><code>log_loss</code>, <code>nn.BCELoss</code></td>
</tr>
</tbody>
</table>
<p>Three details make that correspondence exact. First, the factor two and the saturated log-likelihood are constants in <span class="math inline">\(m\)</span>, so they move the value of the loss without moving its minimiser. A library reporting a negative log-likelihood and one reporting a deviance therefore agree on the fitted model and disagree on the number they print, which is why a loss reading is comparable across models within one implementation and meaningless across two.</p>
<p>Second, under the canonical link the derivative of the negative log-likelihood with respect to the linear predictor is <span class="math inline">\((m - y) / \psi\)</span> for <strong>every</strong> member of the family, and the second derivative is <span class="math inline">\(\kappa''(\theta) / \psi\)</span>. Hence a single boosting implementation serves the whole menu, since swapping the objective swaps the two lines that compute the gradient and the Hessian. The raw residual drives the fit in every row above.</p>
<p>Third, and this is what the EDF framing adds, choosing a loss is choosing a variance function <span class="math inline">\(V(\mu)\)</span>: an assumption about how dispersion scales with the mean. Gaussian takes it constant, Poisson linear in <span class="math inline">\(\mu\)</span> and gamma quadratic. On a <span class="math inline">\(0/1\)</span> response the Bernoulli variance <span class="math inline">\(\mu_k(1 - \mu_k)\)</span> is forced by the response itself, so squared error, which on an indicator is the Brier score, and log loss are both strictly consistent for <span class="math inline">\(\mu_k\)</span> and differ in how they weight the observations. Lecture 7 uses that freedom deliberately when it decomposes the Brier score.</p>
<p>The warning sits one level up, in the metrics a scoring pipeline reaches for by default. Accuracy, the <span class="math inline">\(F_1\)</span> score and the AUC are invariant under any strictly monotone rescaling of the fitted scores, so they grade the ordering of the borrowers and leave the level of <span class="math inline">\(\mathrm{PD}_k\)</span> unidentified. A model selected on AUC alone can therefore rank the book faultlessly and still misprice every loan in it. Lecture 7 takes that gap up as calibration, and lectures 4 and 5 train their networks on <code>nn.BCELoss</code>, which is this section’s Bernoulli deviance halved. Its sibling <code>nn.BCEWithLogitsLoss</code> folds the logit link into the same loss for numerical stability.</p>
</div>
</div>
</section>
<section id="examples-of-deviance-losses" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="examples-of-deviance-losses"><span class="header-section-number">2.3</span> Examples of deviance losses</h2>
<p>Each EDF member has its own deviance loss. The course table carries six members; the Bernoulli row is the one this lecture series lives on.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>EDF distribution</th>
<th>cumulant <span class="math inline">\(\kappa(\theta)\)</span></th>
<th>deviance loss <span class="math inline">\(L(y, m)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Gaussian</td>
<td><span class="math inline">\(\theta^2/2\)</span></td>
<td><span class="math inline">\((y-m)^2\)</span></td>
</tr>
<tr class="even">
<td>gamma</td>
<td><span class="math inline">\(-\log(-\theta)\)</span></td>
<td><span class="math inline">\(2\left((y-m)/m + \log(m/y)\right)\)</span></td>
</tr>
<tr class="odd">
<td>inverse Gaussian</td>
<td><span class="math inline">\(-\sqrt{-2\theta}\)</span></td>
<td><span class="math inline">\((y-m)^2/(m^2 y)\)</span></td>
</tr>
<tr class="even">
<td>Poisson</td>
<td><span class="math inline">\(e^{\theta}\)</span></td>
<td><span class="math inline">\(2\left(m - y - y \log(m/y)\right)\)</span></td>
</tr>
<tr class="odd">
<td>Tweedie, <span class="math inline">\(p \in (1,2)\)</span></td>
<td><span class="math inline">\(\frac{((1-p)\theta)^{\frac{2-p}{1-p}}}{2-p}\)</span></td>
<td><span class="math inline">\(2\left(y\frac{y^{1-p}-m^{1-p}}{1-p} - \frac{y^{2-p}-m^{2-p}}{2-p}\right)\)</span></td>
</tr>
<tr class="even">
<td><strong>Bernoulli</strong></td>
<td><span class="math inline">\(\log(1 + e^{\theta})\)</span></td>
<td><span class="math inline">\(2\left(-y \log m - (1-y)\log(1-m)\right)\)</span></td>
</tr>
</tbody>
</table>
<p>For the Bernoulli member the saturated log-likelihood vanishes, because at <span class="math inline">\(y \in \{0, 1\}\)</span> the best possible model puts probability one on the observed outcome. What remains is</p>
<p><span class="math display">\[
L(y, m) = 2 \left( -y \log m - (1-y) \log(1-m) \right),
\]</span></p>
<p>which is twice the <strong>log-loss</strong> (binary cross-entropy). Machine learning practice in credit scoring minimises log-loss as a matter of routine, and this identity says that doing so is maximum likelihood estimation within the Bernoulli EDF. The loss that data scientists reach for on empirical grounds and the loss that the EDF theory prescribes are the same object, up to the factor two.</p>
</section>
<section id="model-fitting-on-finite-samples" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="model-fitting-on-finite-samples"><span class="header-section-number">2.4</span> Model fitting on finite samples</h2>
<p>The correct deviance loss matters beyond consistency. When the chosen deviance loss matches the actual EDF behaviour of the response, the resulting estimator is best asymptotic normal (Gourieroux, Monfort and Trognon, 1984), so it makes the most of a finite sample. The practical instruction is to select the deviance loss that aligns with the EDF properties of <span class="math inline">\(Y\)</span>. For a binary default indicator there is no modelling choice to agonise over; the indicator is Bernoulli by construction, and the Bernoulli deviance is the correct loss. The choice becomes genuinely delicate later in the credit curriculum, e.g.&nbsp;when modelling loss given default, whose observations live on <span class="math inline">\([0, 1]\)</span> with mass at both endpoints and fit no EDF member comfortably.</p>
</section>
</section>
<section id="model-validation-and-model-selection" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Model validation and model selection</h1>
<p>Model fitting minimises an <strong>in-sample loss</strong> over a learning sample</p>
<p><span class="math display">\[
\mathcal{L} = \left( D_i^{(k)}, \boldsymbol{X}_i \right)_{i=1}^{n},
\qquad
\widehat{\mu}_{\mathcal{L}} \in \underset{\mu}{\arg\min}
\sum_{i=1}^{n} L\left(D_i^{(k)}, \mu(\boldsymbol{X}_i)\right),
\]</span></p>
<p>where the general theory’s weights <span class="math inline">\(v_i/\varphi\)</span> have already been set to one. A model can achieve a small in-sample loss by memorising noise, so a fair assessment requires a <strong>test sample</strong> <span class="math inline">\(\mathcal{T} = (D_t^{(k)}, \boldsymbol{X}_t)_{t=1}^{m}\)</span> that took no part in the fitting. The <strong>out-of-sample loss</strong> (generalisation loss)</p>
<p><span class="math display">\[
\widehat{\mathrm{GL}}\left(\mathcal{T}, \widehat{\mu}_{\mathcal{L}}\right)
= \frac{1}{m} \sum_{t=1}^{m} L\left(D_t^{(k)}, \widehat{\mu}_{\mathcal{L}}(\boldsymbol{X}_t)\right)
\]</span></p>
<p>is the main workhorse for model validation and model selection in machine learning, and it is the quantity every model comparison in this lecture series reports.</p>
<p>The course partitions the insurance data at random. Credit adds a complication that the first lecture already exposed: the Bondora vintage default rates run from 7 per cent in 2012 to 37 per cent in 2017, so consecutive loans are far from exchangeable in time. A random split places loans from every vintage on both sides of the partition, and the test sample then resembles the learning sample by construction. Credit validation practice therefore prefers an <strong>out-of-time split</strong>, holding out the most recent vintages, because the model will only ever be used on business written after its development window. We build both partitions below and let the numbers make the argument.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="This partition is audited in lecture R3">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>This partition is audited in lecture R3
</div>
</div>
<div class="callout-body-container callout-body">
<p>The split built below is the one lectures 4 to 8 and S3 inherit, and lecture R3 examines it rather than taking it on trust. Three of its findings bear on the numbers in this section.</p>
<p>The held-out window is 28.6 per cent pandemic-era originations, so the fall in the default rate reported just below mixes a tightened underwriting standard, a relief programme that suppressed the flag, and the economy itself. R3 dates the relief distortion to a two-month notch in the monthly hazard, in April and May 2020.</p>
<p>That distortion cannot be excluded on this table. Because the outcome window opens at origination, dropping every loan whose window overlaps the notch empties the test sample completely, and R3 shows the count is exactly zero. The demonstration moves to lecture R1’s calendar-indexed table, where excluding the notch lifts the twelve-month probability of default by 2.4 per cent relative.</p>
<p>Finally, the development and out-of-time samples are separable by a classifier at an area under the curve of 0.96, while most marginal stability indices call the covariates unchanged.</p>
<p><strong>The results in this lecture are left as they stand.</strong> They are correct for the partition they were computed on, and R3 is the lecture that questions the partition.</p>
</div>
</div>
<div id="3353f575" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> polars <span class="im">as</span> pl</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> roc_auc_score</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>dat <span class="op">=</span> pl.read_parquet(<span class="st">"../data/bondora_pd.parquet"</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>model_dat <span class="op">=</span> (</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    dat.<span class="bu">filter</span>(pl.col(<span class="st">"Age"</span>).is_not_null() <span class="op">&amp;</span> (pl.col(<span class="st">"IncomeTotal"</span>) <span class="op">&gt;</span> <span class="dv">0</span>))</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    .with_columns(logIncome<span class="op">=</span>pl.col(<span class="st">"IncomeTotal"</span>).log())</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(pl.col(<span class="st">"Education"</span>) <span class="op">!=</span> <span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"modelling sample: n = </span><span class="sc">{</span>model_dat<span class="sc">.</span>height<span class="sc">:,}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>modelling sample: n = 148,667</code></pre>
</div>
</div>
<p>We start from the modelling sample of the first lecture and additionally drop the three loans whose education field carries the unknown code <span class="math inline">\(-1\)</span>, which leaves <span class="math inline">\(n = 148{,}667\)</span> loans. The learning and test samples are then constructed twice, once at random and once by origination date.</p>
<div id="7e843b63" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>g <span class="op">=</span> model_dat.select(</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"default_12m"</span>, <span class="st">"Age"</span>, <span class="st">"logIncome"</span>, <span class="st">"Country"</span>, <span class="st">"Education"</span>,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>     <span class="st">"HomeOwnershipType"</span>, <span class="st">"NewCreditCustomer"</span>, <span class="st">"VerificationType"</span>,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>     <span class="st">"EmploymentDurationCurrentEmployer"</span>, <span class="st">"LoanDate"</span>]).to_pandas()</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co"># random 80/20 split</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">1</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>perm <span class="op">=</span> rng.permutation(<span class="bu">len</span>(g))</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>n_learn <span class="op">=</span> <span class="bu">int</span>(<span class="fl">0.8</span> <span class="op">*</span> <span class="bu">len</span>(g))</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>g_rand <span class="op">=</span> g.iloc[perm].reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>learn_r, test_r <span class="op">=</span> g_rand.iloc[:n_learn], g_rand.iloc[n_learn:]</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="co"># out-of-time split at the 0.8 quantile of origination dates</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>cutoff <span class="op">=</span> g[<span class="st">"LoanDate"</span>].quantile(<span class="fl">0.8</span>)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>learn_t <span class="op">=</span> g[g[<span class="st">"LoanDate"</span>] <span class="op">&lt;=</span> cutoff]</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>test_t <span class="op">=</span> g[g[<span class="st">"LoanDate"</span>] <span class="op">&gt;</span> cutoff]</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"random:      learn </span><span class="sc">{</span><span class="bu">len</span>(learn_r)<span class="sc">:,}</span><span class="ss"> (rate </span><span class="sc">{</span>learn_r[<span class="st">'default_12m'</span>]<span class="sc">.</span>mean()<span class="sc">:.4f}</span><span class="ss">), "</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"test </span><span class="sc">{</span><span class="bu">len</span>(test_r)<span class="sc">:,}</span><span class="ss"> (rate </span><span class="sc">{</span>test_r[<span class="st">'default_12m'</span>]<span class="sc">.</span>mean()<span class="sc">:.4f}</span><span class="ss">)"</span>)</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"out-of-time: learn </span><span class="sc">{</span><span class="bu">len</span>(learn_t)<span class="sc">:,}</span><span class="ss"> (rate </span><span class="sc">{</span>learn_t[<span class="st">'default_12m'</span>]<span class="sc">.</span>mean()<span class="sc">:.4f}</span><span class="ss">), "</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"test </span><span class="sc">{</span><span class="bu">len</span>(test_t)<span class="sc">:,}</span><span class="ss"> (rate </span><span class="sc">{</span>test_t[<span class="st">'default_12m'</span>]<span class="sc">.</span>mean()<span class="sc">:.4f}</span><span class="ss">)"</span>)</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"cutoff date: </span><span class="sc">{</span>cutoff<span class="sc">.</span>date()<span class="sc">}</span><span class="ss">, "</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"test window </span><span class="sc">{</span>test_t[<span class="st">'LoanDate'</span>]<span class="sc">.</span><span class="bu">min</span>()<span class="sc">.</span>date()<span class="sc">}</span><span class="ss"> to </span><span class="sc">{</span>test_t[<span class="st">'LoanDate'</span>]<span class="sc">.</span><span class="bu">max</span>()<span class="sc">.</span>date()<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>random:      learn 118,933 (rate 0.2888), test 29,734 (rate 0.2921)
out-of-time: learn 118,998 (rate 0.3048), test 29,669 (rate 0.2280)
cutoff date: 2019-11-04, test window 2019-11-05 to 2020-07-19</code></pre>
</div>
</div>
<p>The two partitions have nearly identical sizes and completely different characters. Under the random split, the learning and test default rates agree to three decimal places, 28.9 against 29.2 per cent. Under the out-of-time split, the learning window defaults at 30.5 per cent while the held-out window, November 2019 to July 2020, defaults at 22.8 per cent. That window covers the onset of the COVID-19 pandemic, during which the platform’s origination volumes and lending standards shifted markedly, so the drop reflects a changed book as much as a changed economy. This is precisely the situation an out-of-time split exists to simulate.</p>
<p>One remark on metrics before we fit anything. The deviance losses of this lecture judge the <strong>level</strong> of the predicted PDs, so they are calibration measures in the sense of the later calibration lecture. Credit practice leads its validation reports with the <strong>area under the ROC curve (AUC)</strong>, equivalently the Gini coefficient <span class="math inline">\({\rm Gini} = 2\,{\rm AUC} - 1\)</span>, which judges only the <strong>ranking</strong> of borrowers by predicted risk and is blind to the level. The two views can disagree, and below they will. We report AUC alongside every deviance and defer the systematic treatment of calibration to the companion of lecture 7.</p>
</section>
<section id="glm-regression-function" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> GLM regression function</h1>
<p>A <strong>generalised linear model</strong> couples the EDF response with a regression structure. For a smooth and strictly increasing <strong>link function</strong> <span class="math inline">\(g\)</span>, the GLM regression function is</p>
<p><span class="math display">\[
\boldsymbol{X} \mapsto g\left(\mu_{\vartheta}(\boldsymbol{X})\right)
= \vartheta_0 + \sum_{j=1}^{q} \vartheta_j X_j
=: \langle \vartheta, \boldsymbol{X} \rangle,
\]</span></p>
<p>with regression parameter <span class="math inline">\(\vartheta = (\vartheta_0, \ldots, \vartheta_q)^\top \in \mathbb{R}^{q+1}\)</span>. The conditional mean is linear in the covariates up to the link transformation, <span class="math inline">\(\mu_{\vartheta}(\boldsymbol{X}) = \mathbb{E}[D^{(k)} \,|\, \boldsymbol{X}] = g^{-1}\langle \vartheta, \boldsymbol{X} \rangle\)</span>, which in credit is the PD functional <span class="math inline">\(\mathrm{PD}_k(\boldsymbol{X}) = \mu_{\vartheta}(\boldsymbol{X})\)</span> of the first lecture.</p>
<section id="logit-link-example" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="logit-link-example"><span class="header-section-number">4.1</span> Logit-link example</h2>
<p>The insurance lectures favour the log-link, under which the mean is a product of factors <span class="math inline">\(e^{\vartheta_j X_j}\)</span> that pricing actuaries read as price relativities. The credit analogue uses the logit link <span class="math inline">\(g(\mu) = \log(\mu / (1 - \mu))\)</span>, under which the <strong>odds</strong> of default are multiplicative,</p>
<p><span class="math display">\[
\frac{\mu_{\vartheta}(\boldsymbol{X})}{1 - \mu_{\vartheta}(\boldsymbol{X})}
= e^{\vartheta_0} \prod_{j=1}^{q} e^{\vartheta_j X_j}.
\]</span></p>
<p>Each covariate contributes its own <strong>odds ratio</strong> <span class="math inline">\(e^{\vartheta_j}\)</span> per unit of <span class="math inline">\(X_j\)</span>, and the intercept <span class="math inline">\(\vartheta_0\)</span> calibrates the overall level, in exact parallel to the bias parameter of the log-link example. Odds ratios are the credit scorer’s price relativities. They also explain the industry’s <strong>scorecard points</strong>. A traditional scorecard reports <span class="math inline">\(\mathrm{score} = A - B \,\langle \vartheta, \boldsymbol{X} \rangle\)</span> for display constants <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span>, so the score is an affine transformation of the GLM’s linear predictor, and the familiar “points to double the odds” is <span class="math inline">\(B \log 2\)</span>. A scorecard is a logistic GLM wearing different units.</p>
<div id="431d2487" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>ages <span class="op">=</span> np.arange(<span class="dv">18</span>, <span class="dv">91</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>b0, b1, b2 <span class="op">=</span> <span class="fl">1.2</span>, <span class="op">-</span><span class="fl">0.045</span>, <span class="fl">0.55</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> x2, colour, lab <span class="kw">in</span> [(<span class="dv">0</span>, <span class="st">"#3B4A75"</span>, <span class="st">"repeat customer"</span>),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>                        (<span class="dv">1</span>, <span class="st">"#8C2F1E"</span>, <span class="st">"new customer"</span>)]:</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    lin <span class="op">=</span> b0 <span class="op">+</span> b1 <span class="op">*</span> ages <span class="op">+</span> b2 <span class="op">*</span> x2</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    plt.plot(ages, <span class="dv">1</span> <span class="op">/</span> (<span class="dv">1</span> <span class="op">+</span> np.exp(<span class="op">-</span>lin)), color<span class="op">=</span>colour, label<span class="op">=</span>lab)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"age of borrower"</span>)<span class="op">;</span> plt.ylabel(<span class="st">"PD"</span>)<span class="op">;</span> plt.legend()</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02_credit-edf-glm_files/figure-html/cell-4-output-1.png" width="1336" height="587" class="figure-img"></p>
<figcaption>Logit-link GLM with q = 2 illustrative covariates: PD against borrower age for a repeat customer (lower curve) and a new customer (upper curve), using illustrative parameters. The age effect is a common factor on the odds scale, so the two curves are parallel in the log-odds and squeeze together as the PD approaches 0 or 1 on the probability scale.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="edf-and-the-special-canonical-link-choice" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="edf-and-the-special-canonical-link-choice"><span class="header-section-number">4.2</span> EDF and the (special) canonical link choice</h2>
<p>Any smooth and strictly increasing <span class="math inline">\(g\)</span> produces a valid GLM. Choosing the <strong>canonical link</strong> of the response’s EDF member, <span class="math inline">\(g = h = (\kappa')^{-1}\)</span>, makes the canonical parameter itself linear in the covariates, <span class="math inline">\(\theta = \langle \vartheta, \boldsymbol{X} \rangle\)</span>, and buys two structural properties:</p>
<ul>
<li>the maximum likelihood estimator of the GLM is unique (when it exists; see the separation remark in the fitting section below), and</li>
<li>the fitted GLM fulfils the <strong>balance property</strong>.</li>
</ul>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>EDF distribution</th>
<th>canonical link <span class="math inline">\(h(\mu)\)</span></th>
<th>support of <span class="math inline">\(\theta\)</span></th>
<th>mean parameter space</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Gaussian</td>
<td><span class="math inline">\(\mu\)</span></td>
<td><span class="math inline">\(\mathbb{R}\)</span></td>
<td><span class="math inline">\(\mathbb{R}\)</span></td>
</tr>
<tr class="even">
<td>gamma</td>
<td><span class="math inline">\(-1/\mu\)</span></td>
<td><span class="math inline">\((-\infty, 0)\)</span></td>
<td><span class="math inline">\((0, \infty)\)</span></td>
</tr>
<tr class="odd">
<td>inverse Gaussian</td>
<td><span class="math inline">\(-1/(2\mu^2)\)</span></td>
<td><span class="math inline">\((-\infty, 0]\)</span></td>
<td><span class="math inline">\((0, \infty)\)</span></td>
</tr>
<tr class="even">
<td>Poisson</td>
<td><span class="math inline">\(\log(\mu)\)</span></td>
<td><span class="math inline">\(\mathbb{R}\)</span></td>
<td><span class="math inline">\((0, \infty)\)</span></td>
</tr>
<tr class="odd">
<td>Tweedie, <span class="math inline">\(p \in (1,2)\)</span></td>
<td><span class="math inline">\(\mu^{1-p}/(1-p)\)</span></td>
<td><span class="math inline">\((-\infty, 0)\)</span></td>
<td><span class="math inline">\((0, \infty)\)</span></td>
</tr>
<tr class="even">
<td><strong>Bernoulli</strong></td>
<td><span class="math inline">\(\log\left(\mu/(1-\mu)\right)\)</span></td>
<td><span class="math inline">\(\mathbb{R}\)</span></td>
<td><span class="math inline">\((0, 1)\)</span></td>
</tr>
</tbody>
</table>
<p>The insurance lectures note that the canonical link is sometimes inconvenient (the gamma’s canonical link violates positivity of the mean, so the log-link is used instead) and sometimes exactly right (the log-link is the Poisson’s canonical link). Credit sits in the comfortable case. The logit is the Bernoulli’s canonical link, its canonical parameter space is all of <span class="math inline">\(\mathbb{R}\)</span>, and its mean parameter space is <span class="math inline">\((0,1)\)</span>, so predicted PDs respect their natural range automatically. Logistic regression therefore enjoys both structural properties above without giving anything up.</p>
<p>The balance property deserves its credit translation. Under the canonical link, the maximum likelihood score equations include, through the intercept,</p>
<p><span class="math display">\[
\sum_{i=1}^{n} \widehat{\mu}(\boldsymbol{X}_i) = \sum_{i=1}^{n} D_i^{(k)},
\]</span></p>
<p>so the fitted PDs sum exactly to the observed number of defaults on the learning sample. Credit modellers call this <strong>calibration in the large</strong>: the model reproduces the portfolio’s central tendency on its development data. In insurance the same identity guarantees that the estimated prices collect the right total premium. The theorem holds on <span class="math inline">\(\mathcal{L}\)</span>, as an algebraic consequence of the score equations, and it is silent about every other sample. The out-of-time exercise below shows how hard that limitation bites.</p>
</section>
</section>
<section id="glm-fitting-and-examples" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> GLM fitting and examples</h1>
<p>The GLM parameter is estimated by maximum likelihood. For our Bernoulli responses the log-likelihood of the learning sample is</p>
<p><span class="math display">\[
\vartheta \mapsto \ell(\vartheta)
= \sum_{i=1}^{n}
D_i^{(k)} \log \mu_{\vartheta}(\boldsymbol{X}_i)
+ \left(1 - D_i^{(k)}\right) \log\left(1 - \mu_{\vartheta}(\boldsymbol{X}_i)\right),
\]</span></p>
<p>and <span class="math inline">\(\widehat{\vartheta}^{\rm MLE} \in \arg\max_{\vartheta} \ell(\vartheta)\)</span> has no closed form. It is computed by Fisher’s scoring method, equivalently iteratively reweighted least squares (IRLS), exactly as in Nelder and Wedderburn (1972); <code>statsmodels</code> reports the iteration count with every fit.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="Maximum likelihood, ordinary least squares and iteratively reweighted least squares">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Maximum likelihood, ordinary least squares and iteratively reweighted least squares
</div>
</div>
<div class="callout-body-container callout-body">
<p>Three names attach to one estimation problem. <strong>Maximum likelihood</strong> is the criterion, <strong>ordinary least squares</strong> (OLS) is the closed form that criterion takes in a single special case, and <strong>iteratively reweighted least squares</strong> (IRLS) is the algorithm that reaches every other case by solving a sequence of least squares problems. The derivation below shows how the three connect, and it also supplies three results the lecture asserts elsewhere: the balance property, the uniqueness of the canonical-link MLE, and the numerical mechanism behind quasi-complete separation.</p>
<p><strong>The score equations.</strong> Write <span class="math inline">\(\mu_i = \mu_{\vartheta}(\boldsymbol{X}_i)\)</span> for the fitted mean of observation <span class="math inline">\(i\)</span>, <span class="math inline">\(\theta_i = h(\mu_i)\)</span> for its canonical parameter and <span class="math inline">\(Y_i\)</span> for its response. The EDF log-likelihood of the learning sample is</p>
<p><span class="math display">\[
\ell(\vartheta) = \sum_{i=1}^{n} \frac{Y_i \theta_i - \kappa(\theta_i)}{\varphi / v_i}
+ \sum_{i=1}^{n} c\!\left(Y_i, \varphi / v_i\right),
\]</span></p>
<p>whose second sum carries no <span class="math inline">\(\vartheta\)</span> and therefore drops out on differentiation. The regression parameter reaches the likelihood through two links in a chain, since <span class="math inline">\(\theta_i = h(\mu_i)\)</span> and <span class="math inline">\(\mu_i = g^{-1}\langle \vartheta, \boldsymbol{X}_i \rangle\)</span>. Because <span class="math inline">\(h\)</span> inverts <span class="math inline">\(\kappa'\)</span>, we have <span class="math inline">\(\partial \theta_i / \partial \mu_i = 1 / \kappa''(\theta_i)\)</span>, and differentiating the link relation gives <span class="math inline">\(\partial \mu_i / \partial \vartheta_j = X_{ij} / g'(\mu_i)\)</span>. Hence</p>
<p><span class="math display">\[
\frac{\partial \ell}{\partial \vartheta_j}
= \sum_{i=1}^{n} \frac{v_i}{\varphi}\left(Y_i - \mu_i\right)
\frac{1}{\kappa''(\theta_i)} \cdot \frac{X_{ij}}{g'(\mu_i)}
= \sum_{i=1}^{n} \frac{Y_i - \mu_i}{\mathrm{Var}(Y_i)} \cdot \frac{X_{ij}}{g'(\mu_i)},
\qquad j = 0, \ldots, q,
\]</span></p>
<p>using <span class="math inline">\(\mathrm{Var}(Y_i) = (\varphi / v_i)\, \kappa''(\theta_i)\)</span> from the moments callout. Setting all <span class="math inline">\(q+1\)</span> derivatives to zero gives the <strong>score equations</strong>. Each residual enters weighted by its own inverse variance and by the local slope of the link, so a precisely measured observation counts for more, as does one whose mean responds strongly to the linear predictor.</p>
<p><strong>What the canonical link removes.</strong> Choosing <span class="math inline">\(g = h\)</span> makes <span class="math inline">\(g'(\mu_i) = 1 / \kappa''(\theta_i)\)</span>, and the two occurrences of <span class="math inline">\(\kappa''\)</span> cancel. The score equations collapse to</p>
<p><span class="math display">\[
\sum_{i=1}^{n} \frac{v_i}{\varphi} \left(Y_i - \mu_i\right) X_{ij} = 0,
\qquad j = 0, \ldots, q,
\]</span></p>
<p>so at the optimum the fitted means reproduce the observed responses along every covariate direction. Taking <span class="math inline">\(j = 0\)</span>, whose design column is a column of ones, returns the balance property stated above. Furthermore, the canonical link makes <span class="math inline">\(\theta_i = \langle \vartheta, \boldsymbol{X}_i \rangle\)</span> linear in <span class="math inline">\(\vartheta\)</span>, and <span class="math inline">\(\kappa\)</span> is convex, so <span class="math inline">\(\ell\)</span> is concave in <span class="math inline">\(\vartheta\)</span>; strictly so wherever <span class="math inline">\(\kappa'' &gt; 0\)</span> and the design matrix has full rank. That concavity is the precise content of “the MLE is unique when it exists”.</p>
<p><strong>OLS as the degenerate case.</strong> The Gaussian member has <span class="math inline">\(\kappa(\theta) = \theta^2 / 2\)</span>, hence <span class="math inline">\(\kappa'' \equiv 1\)</span>, canonical link the identity, <span class="math inline">\(v_i \equiv 1\)</span> and <span class="math inline">\(\varphi = \sigma^2\)</span>. The collapsed score equations become <span class="math inline">\(\boldsymbol{X}^\top (\boldsymbol{Y} - \boldsymbol{X}\vartheta) = 0\)</span>, the normal equations, solved in closed form by <span class="math inline">\(\widehat{\vartheta} = (\boldsymbol{X}^\top \boldsymbol{X})^{-1} \boldsymbol{X}^\top \boldsymbol{Y}\)</span>. Two separate facts sit behind that formula and are routinely conflated. Maximum likelihood coincides with least squares here because the Gaussian log-likelihood equals <span class="math inline">\(-\lVert \boldsymbol{Y} - \boldsymbol{X}\vartheta \rVert^2 / (2\sigma^2)\)</span> up to an additive constant, so maximising the one minimises the other. The solution is available in closed form for a different reason, namely that <span class="math inline">\(\kappa''\)</span> is constant, which makes the score linear in <span class="math inline">\(\vartheta\)</span>. Every other EDF member has genuine curvature in <span class="math inline">\(\kappa\)</span>, so its score is nonlinear and no closed form exists.</p>
<p><strong>IRLS as the general case.</strong> Newton-Raphson would iterate <span class="math inline">\(\vartheta^{(t+1)} = \vartheta^{(t)} - \left(\nabla^2 \ell\right)^{-1} \nabla \ell\)</span>. Fisher’s scoring method replaces the observed Hessian by its expectation, the <strong>expected information</strong> <span class="math inline">\(\mathcal{I}(\vartheta) = \boldsymbol{X}^\top W \boldsymbol{X}\)</span> with <span class="math inline">\(W = \mathrm{diag}(w_1, \ldots, w_n)\)</span> and</p>
<p><span class="math display">\[
w_i = \frac{1}{\mathrm{Var}(Y_i)\, g'(\mu_i)^2}.
\]</span></p>
<p>Define the <strong>working response</strong> <span class="math inline">\(z_i = \langle \vartheta^{(t)}, \boldsymbol{X}_i \rangle + g'(\mu_i)\left(Y_i - \mu_i\right)\)</span>, a first-order expansion of the link around the current fit. Then <span class="math inline">\(\left(\boldsymbol{X}^\top W \boldsymbol{z}\right)_j
= \sum_i w_i g'(\mu_i)(Y_i - \mu_i) X_{ij} + \left(\boldsymbol{X}^\top W \boldsymbol{X}\vartheta^{(t)}\right)_j\)</span>, and the first sum is exactly <span class="math inline">\(\partial \ell / \partial \vartheta_j\)</span> derived above. Consequently the scoring update rearranges into</p>
<p><span class="math display">\[
\vartheta^{(t+1)}
= \left(\boldsymbol{X}^\top W \boldsymbol{X}\right)^{-1} \boldsymbol{X}^\top W \boldsymbol{z},
\]</span></p>
<p>which is a weighted least squares fit of the working response on the design. Each iteration therefore has the shape of an OLS solve, with <span class="math inline">\(W\)</span> and <span class="math inline">\(\boldsymbol{z}\)</span> recomputed from the current fit, and the algorithm takes its name from that. Under the canonical link the observed Hessian is <span class="math inline">\(-\sum_i (v_i / \varphi)\, \kappa''(\theta_i)\, \boldsymbol{X}_i \boldsymbol{X}_i^\top\)</span>, which involves no <span class="math inline">\(Y_i\)</span> and so equals its own expectation, and Fisher scoring and Newton-Raphson coincide. Away from the canonical link they differ, and the Fisher version is preferred for keeping <span class="math inline">\(\mathcal{I}\)</span> positive definite.</p>
<p><strong>The Bernoulli case.</strong> Here <span class="math inline">\(\varphi = 1\)</span>, <span class="math inline">\(v_i \equiv 1\)</span>, <span class="math inline">\(\kappa''(\theta_i) = \mu_i (1 - \mu_i)\)</span> and the logit link satisfies <span class="math inline">\(g'(\mu_i) = 1 / (\mu_i (1 - \mu_i))\)</span>, so the pieces above become</p>
<p><span class="math display">\[
\sum_{i=1}^{n} \left(D_i^{(k)} - \mu_i\right) X_{ij} = 0,
\qquad
w_i = \mu_i (1 - \mu_i),
\qquad
z_i = \langle \vartheta^{(t)}, \boldsymbol{X}_i \rangle
+ \frac{D_i^{(k)} - \mu_i}{\mu_i (1 - \mu_i)}.
\]</span></p>
<p>The weight <span class="math inline">\(\mu_i(1-\mu_i)\)</span> peaks at a fitted PD of one half and falls away towards either extreme, which has two credit consequences. In a low-default portfolio every fitted PD sits near zero, so the weights are small, the information matrix is correspondingly thin, and standard errors are wider than the row count alone would suggest. More sharply, where a covariate class contains no defaults at all, its fitted PD is driven towards zero at every iteration, its weight follows, and <span class="math inline">\(\boldsymbol{X}^\top W \boldsymbol{X}\)</span> approaches singularity. That is the numerical mechanism behind the quasi-complete separation encountered in the Bondora fit below.</p>
</div>
</div>
<section id="relationship-to-deviance-losses" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="relationship-to-deviance-losses"><span class="header-section-number">5.1</span> Relationship to deviance losses</h2>
<p>Maximising this log-likelihood is the same problem as minimising the Bernoulli deviance loss over the learning sample,</p>
<p><span class="math display">\[
\widehat{\vartheta}^{\rm MLE}
\in \underset{\vartheta}{\arg\min}
\sum_{i=1}^{n} 2 \left( -D_i^{(k)} \log \mu_{\vartheta}(\boldsymbol{X}_i)
- \left(1 - D_i^{(k)}\right) \log\left(1 - \mu_{\vartheta}(\boldsymbol{X}_i)\right) \right),
\]</span></p>
<p>because the two objectives differ by the saturated log-likelihood, which is zero for binary data, and by the factor <span class="math inline">\(-2\)</span>. In-sample loss minimisation, maximum likelihood, and log-loss minimisation are one estimation problem seen from three angles, and by the finite-sample result quoted earlier this common estimator is also the one that uses the data best.</p>
</section>
<section id="glm-example-bondora-data" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="glm-example-bondora-data"><span class="header-section-number">5.2</span> GLM example: Bondora data</h2>
<p>We now fit a logistic GLM whose scope mirrors the seven-covariate French motor third-party liability (MTPL) fit of the course. The first lecture’s covariates <code>AgeClass</code>, <code>logIncome</code> and <code>Country</code> are joined by five further application-time variables: education, home ownership, the new-customer flag, income verification, and employment duration.</p>
<p>Two data points force small engineering decisions, and both are worth stating openly. First, <code>HomeOwnershipType</code> is missing for 1,604 loans and <code>EmploymentDurationCurrentEmployer</code> for 820. In credit data, missingness is routinely informative (an applicant who skips a field differs from one who fills it in), so we assign each an explicit <code>missing</code> category, drop no rows, impute no values, and let the model estimate what missingness is worth. Second, the first lecture’s oldest age class <code>71+</code> contains 13 loans and zero defaults. In a logistic GLM a covariate class with no defaults drives its coefficient to <span class="math inline">\(-\infty\)</span>; the likelihood keeps improving as the fitted PD of the class falls to zero, IRLS runs until it hits its iteration cap, and the reported coefficient and standard error are numerical artefacts. This is <strong>quasi-complete separation</strong>, the standard failure mode of maximum likelihood in sparse categorical data, and it is the fine print behind “the MLE is unique when it exists”. The practical remedy at these volumes is coarser classes, so we merge the two oldest bands into <code>61+</code>.</p>
<div id="d9d6792b" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>g[<span class="st">"AgeClass"</span>] <span class="op">=</span> pd.cut(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    g[<span class="st">"Age"</span>], [<span class="dv">18</span>, <span class="dv">20</span>, <span class="dv">25</span>, <span class="dv">30</span>, <span class="dv">40</span>, <span class="dv">50</span>, <span class="dv">60</span>, <span class="dv">101</span>],</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    labels<span class="op">=</span>[<span class="st">"18-20"</span>, <span class="st">"21-25"</span>, <span class="st">"26-30"</span>, <span class="st">"31-40"</span>, <span class="st">"41-50"</span>, <span class="st">"51-60"</span>, <span class="st">"61+"</span>],</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    include_lowest<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>ho <span class="op">=</span> g[<span class="st">"HomeOwnershipType"</span>]</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>g[<span class="st">"HomeOwnership"</span>] <span class="op">=</span> np.where(ho.isna() <span class="op">|</span> (ho <span class="op">==</span> <span class="op">-</span><span class="dv">1</span>), <span class="st">"missing"</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>                              ho.fillna(<span class="op">-</span><span class="dv">1</span>).astype(<span class="bu">int</span>).astype(<span class="bu">str</span>))</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>g[<span class="st">"EmploymentDuration"</span>] <span class="op">=</span> g[<span class="st">"EmploymentDurationCurrentEmployer"</span>].fillna(<span class="st">"missing"</span>)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="co"># rebuild the splits so they carry the engineered columns</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>g_rand <span class="op">=</span> g.iloc[perm].reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>learn_r, test_r <span class="op">=</span> g_rand.iloc[:n_learn], g_rand.iloc[n_learn:]</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>learn_t, test_t <span class="op">=</span> g[g[<span class="st">"LoanDate"</span>] <span class="op">&lt;=</span> cutoff], g[g[<span class="st">"LoanDate"</span>] <span class="op">&gt;</span> cutoff]</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>FORMULA <span class="op">=</span> (<span class="st">"default_12m ~ AgeClass + logIncome + Country + C(Education)"</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>           <span class="st">" + C(HomeOwnership) + NewCreditCustomer + C(VerificationType)"</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>           <span class="st">" + C(EmploymentDuration)"</span>)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>glm_r <span class="op">=</span> smf.glm(FORMULA, data<span class="op">=</span>learn_r, family<span class="op">=</span>sm.families.Binomial()).fit()</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(glm_r.summary())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:            default_12m   No. Observations:               118933
Model:                            GLM   Df Residuals:                   118894
Model Family:                Binomial   Df Model:                           38
Link Function:                  Logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -63416.
Date:                Thu, 03 Sep 2026   Deviance:                   1.2683e+05
Time:                        11:33:03   Pearson chi2:                 1.18e+05
No. Iterations:                     5   Pseudo R-squ. (CS):             0.1269
Covariance Type:            nonrobust                                         
========================================================================================================
                                           coef    std err          z      P&gt;|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------
Intercept                                0.7627      0.395      1.929      0.054      -0.012       1.538
AgeClass[T.21-25]                       -0.1370      0.058     -2.380      0.017      -0.250      -0.024
AgeClass[T.26-30]                       -0.3632      0.057     -6.348      0.000      -0.475      -0.251
AgeClass[T.31-40]                       -0.5094      0.056     -9.052      0.000      -0.620      -0.399
AgeClass[T.41-50]                       -0.5503      0.057     -9.622      0.000      -0.662      -0.438
AgeClass[T.51-60]                       -0.6180      0.058    -10.572      0.000      -0.733      -0.503
AgeClass[T.61+]                         -0.5987      0.063     -9.550      0.000      -0.722      -0.476
Country[T.ES]                            1.9632      0.021     95.336      0.000       1.923       2.004
Country[T.FI]                            1.1349      0.022     51.259      0.000       1.092       1.178
Country[T.SK]                            2.5260      0.150     16.888      0.000       2.233       2.819
C(Education)[T.2]                        0.0798      0.040      1.990      0.047       0.001       0.158
C(Education)[T.3]                       -0.1207      0.026     -4.648      0.000      -0.172      -0.070
C(Education)[T.4]                       -0.2593      0.025    -10.427      0.000      -0.308      -0.211
C(Education)[T.5]                       -0.4296      0.026    -16.388      0.000      -0.481      -0.378
C(HomeOwnership)[T.1]                   -1.6857      0.372     -4.527      0.000      -2.416      -0.956
C(HomeOwnership)[T.10]                  -1.5201      0.373     -4.072      0.000      -2.252      -0.788
C(HomeOwnership)[T.2]                   -1.4985      0.373     -4.020      0.000      -2.229      -0.768
C(HomeOwnership)[T.3]                   -1.3790      0.373     -3.702      0.000      -2.109      -0.649
C(HomeOwnership)[T.4]                   -1.4735      0.374     -3.941      0.000      -2.206      -0.741
C(HomeOwnership)[T.5]                   -1.5802      0.378     -4.177      0.000      -2.322      -0.839
C(HomeOwnership)[T.6]                   -1.5457      0.378     -4.092      0.000      -2.286      -0.805
C(HomeOwnership)[T.7]                   -1.6702      0.375     -4.449      0.000      -2.406      -0.934
C(HomeOwnership)[T.8]                   -1.8757      0.373     -5.032      0.000      -2.606      -1.145
C(HomeOwnership)[T.9]                   -2.0325      0.388     -5.232      0.000      -2.794      -1.271
C(HomeOwnership)[T.missing]             -1.6563      0.366     -4.524      0.000      -2.374      -0.939
NewCreditCustomer[T.True]                0.3011      0.015     19.967      0.000       0.272       0.331
C(VerificationType)[T.2]                 0.3686      0.148      2.487      0.013       0.078       0.659
C(VerificationType)[T.3]                -0.1341      0.031     -4.364      0.000      -0.194      -0.074
C(VerificationType)[T.4]                -0.2368      0.016    -14.772      0.000      -0.268      -0.205
C(EmploymentDuration)[T.Other]          -0.0841      0.036     -2.338      0.019      -0.155      -0.014
C(EmploymentDuration)[T.Retiree]         0.2325      0.033      7.025      0.000       0.168       0.297
C(EmploymentDuration)[T.TrialPeriod]     0.2027      0.095      2.131      0.033       0.016       0.389
C(EmploymentDuration)[T.UpTo1Year]       0.1560      0.021      7.335      0.000       0.114       0.198
C(EmploymentDuration)[T.UpTo2Years]      0.1611      0.036      4.438      0.000       0.090       0.232
C(EmploymentDuration)[T.UpTo3Years]      0.0871      0.040      2.204      0.028       0.010       0.165
C(EmploymentDuration)[T.UpTo4Years]      0.0807      0.047      1.730      0.084      -0.011       0.172
C(EmploymentDuration)[T.UpTo5Years]      0.1170      0.020      5.938      0.000       0.078       0.156
C(EmploymentDuration)[T.missing]        -0.2141      0.105     -2.032      0.042      -0.421      -0.008
logIncome                               -0.0311      0.014     -2.208      0.027      -0.059      -0.003
========================================================================================================</code></pre>
</div>
</div>
<p>The fit estimates 39 regression parameters and converges in five IRLS iterations. A few coefficients read as odds ratios illustrate the logit link’s interpretability. A Spanish borrower carries <span class="math inline">\(e^{1.963} \approx 7.1\)</span> times the default odds of an otherwise identical Estonian borrower, which quantifies the country effect that resolved the first lecture’s Simpson’s paradox. A new customer carries <span class="math inline">\(e^{0.301} \approx 1.35\)</span> times the odds of a repeat customer. Higher education (level 5) multiplies the odds by <span class="math inline">\(e^{-0.430} \approx 0.65\)</span> relative to primary education. Meanwhile the income coefficient sits at <span class="math inline">\(-0.031\)</span>: once country and the other application variables are controlled, declared income has almost no residual work left to do, continuing its demotion from the confounded <span class="math inline">\(+0.255\)</span> of the first lecture’s GLM1.</p>
<p>Because the logit is the canonical link, the balance property must hold on the learning sample to machine precision, and it does:</p>
<div id="4a3cec87" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"sum of fitted PDs:       </span><span class="sc">{</span>glm_r<span class="sc">.</span>fittedvalues<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:,.4f}</span><span class="ss">"</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"observed defaults in L:  </span><span class="sc">{</span>learn_r[<span class="st">'default_12m'</span>]<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:,}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>sum of fitted PDs:       34,345.0000
observed defaults in L:  34,345</code></pre>
</div>
</div>
</section>
<section id="bernoulli-deviance-loss-in-sample-and-out-of-sample" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="bernoulli-deviance-loss-in-sample-and-out-of-sample"><span class="header-section-number">5.3</span> Bernoulli deviance loss: in-sample and out-of-sample</h2>
<p>We evaluate the fitted GLM with the scaled Bernoulli deviance loss, in <span class="math inline">\(10^{-2}\)</span> units as the course does for its Poisson losses, and we report the AUC alongside. For each test sample we also report the deviance of the <strong>null model</strong> that predicts that sample’s own mean default rate for every loan, because Bernoulli deviance levels depend on the base rate and are comparable across samples only relative to such a floor.</p>
<div id="3af4471e" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> bernoulli_deviance(pred, obs):</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    p <span class="op">=</span> np.asarray(pred, <span class="bu">float</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> np.asarray(obs, <span class="bu">float</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="dv">100</span> <span class="op">*</span> <span class="dv">2</span> <span class="op">*</span> np.mean(<span class="op">-</span>y <span class="op">*</span> np.log(p) <span class="op">-</span> (<span class="dv">1</span> <span class="op">-</span> y) <span class="op">*</span> np.log(<span class="dv">1</span> <span class="op">-</span> p))</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> report(label, pred, obs):</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    null <span class="op">=</span> np.full(<span class="bu">len</span>(obs), np.asarray(obs, <span class="bu">float</span>).mean())</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>label<span class="sc">}</span><span class="ss">: deviance </span><span class="sc">{</span>bernoulli_deviance(pred, obs)<span class="sc">:7.3f}</span><span class="ss">   "</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"null </span><span class="sc">{</span>bernoulli_deviance(null, obs)<span class="sc">:7.3f}</span><span class="ss">   "</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"AUC </span><span class="sc">{</span>roc_auc_score(obs, pred)<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>report(<span class="st">"random fit, in-sample      "</span>, glm_r.fittedvalues, learn_r[<span class="st">"default_12m"</span>])</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>report(<span class="st">"random fit, random test    "</span>, glm_r.predict(test_r), test_r[<span class="st">"default_12m"</span>])</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"mean predicted PD on random test: </span><span class="sc">{</span>glm_r<span class="sc">.</span>predict(test_r)<span class="sc">.</span>mean()<span class="sc">:.4f}</span><span class="ss">   "</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"observed rate: </span><span class="sc">{</span>test_r[<span class="st">'default_12m'</span>]<span class="sc">.</span>mean()<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>random fit, in-sample      : deviance 106.641   null 120.210   AUC 0.7263
random fit, random test    : deviance 108.197   null 120.802   AUC 0.7182
mean predicted PD on random test: 0.2888   observed rate: 0.2921</code></pre>
</div>
</div>
<p>On the random split the picture is exactly the course’s. The out-of-sample deviance, 108.197, sits just above the in-sample 106.641, so the model generalises with a small gap, and the AUC declines only from 0.726 to 0.718. The mean predicted PD on the test sample, 28.9 per cent, agrees with the observed 29.2 per cent, so the balance property transfers to the test sample almost perfectly. It transfers because a random split makes the two samples statistically identical, and that is the flattering assumption the out-of-time split now removes.</p>
<div id="687eb9e2" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>glm_t <span class="op">=</span> smf.glm(FORMULA, data<span class="op">=</span>learn_t, family<span class="op">=</span>sm.families.Binomial()).fit()</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>report(<span class="st">"oot fit, in-sample         "</span>, glm_t.fittedvalues, learn_t[<span class="st">"default_12m"</span>])</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>report(<span class="st">"oot fit, out-of-time test  "</span>, glm_t.predict(test_t), test_t[<span class="st">"default_12m"</span>])</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"mean predicted PD on oot test: </span><span class="sc">{</span>glm_t<span class="sc">.</span>predict(test_t)<span class="sc">.</span>mean()<span class="sc">:.4f}</span><span class="ss">   "</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"observed rate: </span><span class="sc">{</span>test_t[<span class="st">'default_12m'</span>]<span class="sc">.</span>mean()<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>oot fit, in-sample         : deviance 108.873   null 122.969   AUC 0.7274
oot fit, out-of-time test  : deviance 100.400   null 107.365   AUC 0.7158
mean predicted PD on oot test: 0.3072   observed rate: 0.2280</code></pre>
</div>
</div>
<p>Read these numbers carefully, because the naive reading gets them backwards. The out-of-time test deviance, 100.400, is <strong>lower</strong> than the random-split test deviance, and a careless comparison would conclude the model performs better out of time. The null deviances expose the mechanics. The out-of-time window’s base rate of 22.8 per cent makes its null deviance 107.4, against 120.8 on the random test sample, so the entire apparent improvement is the lower entropy of a lower base rate. Relative to its own null, the model explains far less out of time. The calibration failure is where the drift actually lands. The refit predicts a mean PD of 30.7 per cent on the held-out window against an observed 22.8 per cent, an overstatement of nearly eight percentage points from a model whose fitted PDs summed exactly to the observed defaults on its own development window. The balance property is an in-sample identity, and the out-of-time split is what reveals that.</p>
<p>The AUC tells the complementary story. It falls only to 0.716 on the out-of-time window, so the model still ranks borrowers nearly as well as it ever did, while its level is badly off. This combination, ranking that survives the drift and a level that does not, is the routine experience of credit scorecards, and it explains the industry’s standing practice of keeping a scorecard’s coefficients while recalibrating its intercept to the current central tendency. The calibration lecture’s companion takes this up properly.</p>
<div id="50ae0aae" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>g_oot <span class="op">=</span> g.copy()</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>g_oot[<span class="st">"pred"</span>] <span class="op">=</span> glm_t.predict(g_oot)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>g_oot[<span class="st">"month"</span>] <span class="op">=</span> g_oot[<span class="st">"LoanDate"</span>].dt.to_period(<span class="st">"M"</span>).dt.to_timestamp()</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>monthly <span class="op">=</span> (g_oot[g_oot[<span class="st">"month"</span>] <span class="op">&gt;=</span> <span class="st">"2013-01-01"</span>]</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>           .groupby(<span class="st">"month"</span>)[[<span class="st">"default_12m"</span>, <span class="st">"pred"</span>]].mean())</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">6.5</span>, <span class="fl">3.6</span>))</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>ax.plot(monthly.index, monthly[<span class="st">"default_12m"</span>], <span class="st">"o"</span>, ms<span class="op">=</span><span class="dv">3</span>,</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span><span class="st">"#8A8377"</span>, label<span class="op">=</span><span class="st">"observed"</span>)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>ax.plot(monthly.index, monthly[<span class="st">"pred"</span>], color<span class="op">=</span><span class="st">"#8C2F1E"</span>, label<span class="op">=</span><span class="st">"predicted"</span>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>ax.axvline(cutoff, color<span class="op">=</span><span class="st">"#3B4A75"</span>, ls<span class="op">=</span><span class="st">"--"</span>, lw<span class="op">=</span><span class="dv">1</span>, label<span class="op">=</span><span class="st">"oot cutoff"</span>)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"origination month"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"12-month default rate"</span>)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>ax.legend()<span class="op">;</span> plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02_credit-edf-glm_files/figure-html/cell-9-output-1.png" width="961" height="527" class="figure-img"></p>
<figcaption>Monthly observed default rate (dots) against the mean predicted PD of the out-of-time fit (line). Left of the dashed cutoff is the development window, where the fit tracks the vintage cycle it was estimated on; right of it, prediction and outcome part company as the pandemic-era book departs from the development experience. Months are plotted from 2013 onward; the sparse 2009 to 2012 vintages are omitted from the display only.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="individual-bernoulli-versus-grouped-binomial" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="individual-bernoulli-versus-grouped-binomial"><span class="header-section-number">5.4</span> Individual Bernoulli versus grouped binomial</h2>
<p>The course closes its GLM lecture by showing that two formulations of the Poisson GLM coincide: regressing claim counts with <span class="math inline">\(\log v_i\)</span> as an offset, and regressing claim frequencies with <span class="math inline">\(v_i\)</span> as weights. The weights mechanism has an exact Bernoulli counterpart. Borrowers who share one covariate cell contribute a product of identical Bernoulli likelihood terms, and that product depends on the cell’s data only through its number of loans and its number of defaults. Consequently, fitting the GLM on one row per loan and fitting it on one row per covariate cell, with the cell’s default rate as response and its loan count as weight, are the same likelihood and must return the same estimate. Aggregation over identical covariate rows plays the role that aggregation over exposure plays for counts.</p>
<p>We verify this on a purely categorical sub-model, since exact aggregation needs discrete cells.</p>
<div id="5ad64800" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>SUB <span class="op">=</span> <span class="st">"default_12m ~ AgeClass + Country + C(Education)"</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>glm_ind <span class="op">=</span> smf.glm(SUB, data<span class="op">=</span>learn_r, family<span class="op">=</span>sm.families.Binomial()).fit()</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>cells <span class="op">=</span> (learn_r</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>         .groupby([<span class="st">"AgeClass"</span>, <span class="st">"Country"</span>, <span class="st">"Education"</span>], observed<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>         .agg(n<span class="op">=</span>(<span class="st">"default_12m"</span>, <span class="st">"size"</span>), defaults<span class="op">=</span>(<span class="st">"default_12m"</span>, <span class="st">"sum"</span>))</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>         .reset_index())</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>cells[<span class="st">"rate"</span>] <span class="op">=</span> cells[<span class="st">"defaults"</span>] <span class="op">/</span> cells[<span class="st">"n"</span>]</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>glm_grp <span class="op">=</span> smf.glm(<span class="st">"rate ~ AgeClass + Country + C(Education)"</span>, data<span class="op">=</span>cells,</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>                  family<span class="op">=</span>sm.families.Binomial(), var_weights<span class="op">=</span>cells[<span class="st">"n"</span>]).fit()</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"rows: </span><span class="sc">{</span><span class="bu">len</span>(learn_r)<span class="sc">:,}</span><span class="ss"> individual  -&gt;  </span><span class="sc">{</span><span class="bu">len</span>(cells)<span class="sc">:,}</span><span class="ss"> cells"</span>)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"max |coefficient difference|: "</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">abs</span>(glm_ind.params.values <span class="op">-</span> glm_grp.params.values)<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.2e}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>rows: 118,933 individual  -&gt;  124 cells
max |coefficient difference|: 9.92e-13</code></pre>
</div>
</div>
<p>The learning sample of 118,933 loans collapses to 124 cells, and the two coefficient vectors agree to <span class="math inline">\(10^{-12}\)</span>, which is the IRLS convergence tolerance, so the two fits are the same fit. The reported deviances differ, because the saturated model changes when the data are grouped, and the coefficient estimates are unaffected. In practice the grouped form is how logistic GLMs are fitted on aggregated cohort data, e.g.&nbsp;historical default-rate tables where loan-level records no longer exist, and it is also a substantial computational saving whenever the covariates are categorical.</p>
</section>
</section>
<section id="takeaways-and-outlook" class="level1 unnumbered">
<h1 class="unnumbered">Takeaways and outlook</h1>
<p>The Bernoulli member of the EDF hands credit modelling its complete toolkit. The canonical parameter is the log-odds, the canonical link is the logit, the deviance loss is twice the log-loss, maximum likelihood is deviance minimisation, and the balance property is calibration in the large on the development sample. The out-of-time exercise added the caveat that theory attaches to all of it: every guarantee is an in-sample guarantee, and a drifting book collects the difference.</p>
<p>The GLM regression function is linear in the covariates up to the link,</p>
<p><span class="math display">\[
\boldsymbol{X} \mapsto g\left(\mu_{\vartheta}(\boldsymbol{X})\right)
= \vartheta_0 + \sum_{j=1}^{q} \vartheta_j X_j
= \langle \vartheta, \boldsymbol{X} \rangle.
\]</span></p>
<p>The networks of the coming lectures keep every piece of this lecture’s machinery (the Bernoulli deviance as loss, the sigmoid as output activation, the out-of-sample loss as arbiter) and change exactly one thing, replacing the covariates with learned features,</p>
<p><span class="math display">\[
\boldsymbol{X} \mapsto g\left(\mu_{\vartheta}(\boldsymbol{X})\right)
= w_0^{(d+1)} + \sum_{j=1}^{q_d} w_j^{(d+1)}\, z_j^{(d:1)}(\boldsymbol{X})
= \langle \boldsymbol{w}^{(d+1)}, \boldsymbol{z}^{(d:1)}(\boldsymbol{X}) \rangle,
\]</span></p>
<p>where <span class="math inline">\(\boldsymbol{z}^{(d:1)}: \mathbb{R}^q \to \mathbb{R}^{q_d}\)</span> is a feature extractor learned from the data. A neural network PD model is a logistic GLM on features the model builds for itself, which is why everything proved here survives into deep learning.</p>
</section>
<section id="copyright-and-attribution" class="level1 unnumbered">
<h1 class="unnumbered">Copyright and attribution</h1>
<p>This document adapts the storyline, structure, and notation of <em>Lecture 2: Exponential Dispersion Family and Generalized Linear Models</em> from the summer school <strong>Deep Learning for Actuarial Modeling</strong> (Scognamiglio, Maggi and Wüthrich, Università Cattolica del Sacro Cuore, Milano, 2026), part of the project <em>AI Tools for Actuaries</em>, used under CC BY-NC 4.0. Changes made: the Poisson claim-frequency thread is recast as the Bernoulli default thread on the public Bondora loan book, the code is Python where the original is R, the out-of-time validation contrast, the quasi-complete separation remark, the scorecard points aside, and the grouped binomial equivalence are new, and the offsets-versus-weights section is replaced by its Bernoulli counterpart. The original lecture notes are available at <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5162304" class="uri">https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5162304</a>.</p>
</section>
<section id="references" class="level1 unnumbered">
<h1 class="unnumbered">References</h1>
<ul>
<li>Gneiting, T. (2011). Making and evaluating point forecasts. <em>Journal of the American Statistical Association</em> 106(494), 746-762.</li>
<li>Gourieroux, C., Monfort, A. and Trognon, A. (1984). Pseudo maximum likelihood methods: theory. <em>Econometrica</em> 52(3), 681-700.</li>
<li>Nelder, J.A. and Wedderburn, R.W.M. (1972). Generalized linear models. <em>Journal of the Royal Statistical Society, Series A</em> 135(3), 370-384.</li>
<li>Wüthrich, M.V. and Merz, M. (2023). <em>Statistical Foundations of Actuarial Learning and its Applications</em>. Springer.</li>
<li>Scognamiglio, S., Maggi, M. and Wüthrich, M.V. (2026). <em>Deep Learning for Actuarial Modeling</em>, SSRN 5162304.</li>
</ul>
</section>

</main>
<!-- /main column -->
</div> <!-- /content -->




</body></html>