<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mario Ervedosa, adapting Scognamiglio, Maggi and Wüthrich">
<meta name="dcterms.date" content="2026-09-01">

<title>Credit Lecture 3: Deep Learning, an Overview</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>



  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../lectures/lecture.css">
</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#why-deep-learning-in-credit-risk" id="toc-why-deep-learning-in-credit-risk" class="nav-link" data-scroll-target="#why-deep-learning-in-credit-risk"><span class="header-section-number">1</span> Why deep learning in credit risk?</a>
  <ul class="collapse">
  <li><a href="#the-scorecard-and-its-hand-crafted-features" id="toc-the-scorecard-and-its-hand-crafted-features" class="nav-link" data-scroll-target="#the-scorecard-and-its-hand-crafted-features"><span class="header-section-number">1.1</span> The scorecard and its hand-crafted features</a></li>
  <li><a href="#the-curse-of-dimensionality-arrives-as-a-column-count" id="toc-the-curse-of-dimensionality-arrives-as-a-column-count" class="nav-link" data-scroll-target="#the-curse-of-dimensionality-arrives-as-a-column-count"><span class="header-section-number">1.2</span> The curse of dimensionality arrives as a column count</a></li>
  <li><a href="#historical-perspective" id="toc-historical-perspective" class="nav-link" data-scroll-target="#historical-perspective"><span class="header-section-number">1.3</span> Historical perspective</a></li>
  <li><a href="#what-the-regulator-asks-in-return" id="toc-what-the-regulator-asks-in-return" class="nav-link" data-scroll-target="#what-the-regulator-asks-in-return"><span class="header-section-number">1.4</span> What the regulator asks in return</a></li>
  </ul></li>
  <li><a href="#representation-learning-the-core-principle" id="toc-representation-learning-the-core-principle" class="nav-link" data-scroll-target="#representation-learning-the-core-principle"><span class="header-section-number">2</span> Representation learning: the core principle</a>
  <ul class="collapse">
  <li><a href="#the-idea-stated-formally" id="toc-the-idea-stated-formally" class="nav-link" data-scroll-target="#the-idea-stated-formally"><span class="header-section-number">2.1</span> The idea, stated formally</a></li>
  <li><a href="#the-credit-card-portfolio" id="toc-the-credit-card-portfolio" class="nav-link" data-scroll-target="#the-credit-card-portfolio"><span class="header-section-number">2.2</span> The credit card portfolio</a></li>
  <li><a href="#pre-processing-and-one-decision-that-turned-out-to-matter" id="toc-pre-processing-and-one-decision-that-turned-out-to-matter" class="nav-link" data-scroll-target="#pre-processing-and-one-decision-that-turned-out-to-matter"><span class="header-section-number">2.3</span> Pre-processing, and one decision that turned out to matter</a></li>
  <li><a href="#three-representations-two-dimensions-each" id="toc-three-representations-two-dimensions-each" class="nav-link" data-scroll-target="#three-representations-two-dimensions-each"><span class="header-section-number">2.4</span> Three representations, two dimensions each</a></li>
  <li><a href="#what-the-comparison-shows" id="toc-what-the-comparison-shows" class="nav-link" data-scroll-target="#what-the-comparison-shows"><span class="header-section-number">2.5</span> What the comparison shows</a></li>
  <li><a href="#why-the-autoencoder-loses-measured-rather-than-asserted" id="toc-why-the-autoencoder-loses-measured-rather-than-asserted" class="nav-link" data-scroll-target="#why-the-autoencoder-loses-measured-rather-than-asserted"><span class="header-section-number">2.6</span> Why the autoencoder loses, measured rather than asserted</a></li>
  </ul></li>
  <li><a href="#feed-forward-networks-generalise-the-logistic-glm" id="toc-feed-forward-networks-generalise-the-logistic-glm" class="nav-link" data-scroll-target="#feed-forward-networks-generalise-the-logistic-glm"><span class="header-section-number">3</span> Feed-forward networks generalise the logistic GLM</a>
  <ul class="collapse">
  <li><a href="#a-single-layer-is-a-scorecard" id="toc-a-single-layer-is-a-scorecard" class="nav-link" data-scroll-target="#a-single-layer-is-a-scorecard"><span class="header-section-number">3.1</span> A single layer is a scorecard</a></li>
  <li><a href="#depth-and-what-the-layers-do" id="toc-depth-and-what-the-layers-do" class="nav-link" data-scroll-target="#depth-and-what-the-layers-do"><span class="header-section-number">3.2</span> Depth, and what the layers do</a></li>
  </ul></li>
  <li><a href="#architectures-beyond-the-tabular-cross-section" id="toc-architectures-beyond-the-tabular-cross-section" class="nav-link" data-scroll-target="#architectures-beyond-the-tabular-cross-section"><span class="header-section-number">4</span> Architectures beyond the tabular cross-section</a>
  <ul class="collapse">
  <li><a href="#from-vectors-to-tensors" id="toc-from-vectors-to-tensors" class="nav-link" data-scroll-target="#from-vectors-to-tensors"><span class="header-section-number">4.1</span> From vectors to tensors</a></li>
  <li><a href="#convolutional-networks-and-an-honest-word-about-credit" id="toc-convolutional-networks-and-an-honest-word-about-credit" class="nav-link" data-scroll-target="#convolutional-networks-and-an-honest-word-about-credit"><span class="header-section-number">4.2</span> Convolutional networks, and an honest word about credit</a></li>
  <li><a href="#recurrent-networks-and-behavioural-scoring" id="toc-recurrent-networks-and-behavioural-scoring" class="nav-link" data-scroll-target="#recurrent-networks-and-behavioural-scoring"><span class="header-section-number">4.3</span> Recurrent networks and behavioural scoring</a></li>
  <li><a href="#embedding-layers-for-categorical-covariates" id="toc-embedding-layers-for-categorical-covariates" class="nav-link" data-scroll-target="#embedding-layers-for-categorical-covariates"><span class="header-section-number">4.4</span> Embedding layers for categorical covariates</a></li>
  <li><a href="#autoencoders-attention-and-interpretable-networks" id="toc-autoencoders-attention-and-interpretable-networks" class="nav-link" data-scroll-target="#autoencoders-attention-and-interpretable-networks"><span class="header-section-number">4.5</span> Autoencoders, attention and interpretable networks</a></li>
  </ul></li>
  <li><a href="#combined-actuarial-neural-network" id="toc-combined-actuarial-neural-network" class="nav-link" data-scroll-target="#combined-actuarial-neural-network"><span class="header-section-number">5</span> Combined actuarial neural network</a>
  <ul class="collapse">
  <li><a href="#the-scorecard-the-credit-committee-already-approved" id="toc-the-scorecard-the-credit-committee-already-approved" class="nav-link" data-scroll-target="#the-scorecard-the-credit-committee-already-approved"><span class="header-section-number">5.1</span> The scorecard the credit committee already approved</a></li>
  <li><a href="#the-degenerate-cann-is-already-industry-practice" id="toc-the-degenerate-cann-is-already-industry-practice" class="nav-link" data-scroll-target="#the-degenerate-cann-is-already-industry-practice"><span class="header-section-number">5.2</span> The degenerate CANN is already industry practice</a></li>
  </ul></li>
  <li><a href="#takeaways-and-outlook" id="toc-takeaways-and-outlook" class="nav-link" data-scroll-target="#takeaways-and-outlook">Takeaways and outlook</a></li>
  <li><a href="#copyright-and-attribution" id="toc-copyright-and-attribution" class="nav-link" data-scroll-target="#copyright-and-attribution">Copyright and attribution</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Credit Lecture 3: Deep Learning, an Overview</h1>
<p class="subtitle lead">Deep Learning for Actuarial Modelling: a credit risk companion</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mario Ervedosa, adapting Scognamiglio, Maggi and Wüthrich </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 1, 2026</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>We stand back from the fitted models of the first two credit lectures and ask what deep learning is for. Lecture 3 of Deep Learning for Actuarial Modeling answers with representation learning, i.e.&nbsp;the actuary supplies raw data and the architecture learns what to extract, and this companion transplants that answer to credit risk. The authors’ Fashion-MNIST comparison is replaced by a wide anonymised credit card portfolio, on which principal components, an autoencoder and a supervised feature extractor each compress 1,158 covariates to two dimensions. The autoencoder reconstructs the portfolio far better than the principal components and discriminates default far worse, which is the result the rest of the series is built to avoid. The lecture closes on the architectures that follow, and on the combined actuarial neural network, whose GLM baseline is the scorecard a credit committee has already approved.</p>
  </div>
</div>


</header>


<section id="introduction" class="level1 unnumbered">
<h1 class="unnumbered">Introduction</h1>
<p>The first two credit lectures built a probability-of-default model the classical way. The first chose covariates by inspection, banded borrower age by hand, and read an interaction off a Simpson’s paradox in declared income. The second supplied the distributional theory underneath those choices, and in doing so it also exposed their cost, since the seven age bands had to be merged to six before maximum likelihood would behave. Every one of those decisions was taken by a person looking at a plot.</p>
<p>This lecture stands back and asks what deep learning offers instead. The answer the course gives is <strong>representation learning</strong>: rather than hand-crafting the features a regression consumes, the actuary hands raw data to an architecture and lets the training algorithm decide what to extract. Lecture 3 of the course develops that idea, builds the feed-forward network as a generalisation of the GLM, surveys the architectures that specialise it to sequences and images, and closes on the combined actuarial neural network (CANN), which adds a learned correction to a fitted GLM baseline. This companion follows the same arc for credit.</p>
<p>Two things here are ours rather than the authors’. The first is the register: an overview lecture delivered as slides is a sequence of claims, and a document has to argue for them, so the material is recast as prose. The second is the evidence. The authors motivate representation learning with Fashion-MNIST, where a deep autoencoder separates ten balanced clothing classes that principal components leave smeared together. Credit has no Fashion-MNIST, and it does have wide anonymised portfolios, so we run the same comparison on 1,214 unlabelled features from a credit card book and report what happens. The result does not flatter the autoencoder, and it turns out to be the most useful thing in the lecture.</p>
</section>
<section id="why-deep-learning-in-credit-risk" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Why deep learning in credit risk?</h1>
<section id="the-scorecard-and-its-hand-crafted-features" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="the-scorecard-and-its-hand-crafted-features"><span class="header-section-number">1.1</span> The scorecard and its hand-crafted features</h2>
<p>Credit scoring has a mature and highly disciplined feature engineering tradition, which is precisely why it is the right place to see what representation learning replaces. The classical scorecard takes each candidate variable, bins it into coarse classes, replaces each class by its weight of evidence, and admits the variable only if the binning is monotone, populated at every level and stable across time. The procedure is transparent, auditable and slow, and every step of it is a decision recorded in a model development document.</p>
<p>The second credit lecture ran a miniature version of that procedure without naming it. Borrower age was cut into seven bands at boundaries chosen by eye from a default-rate plot. The oldest band held thirteen loans and no defaults, which drove its coefficient towards minus infinity, so the two oldest bands were merged into <code>61+</code>. Missing home ownership and missing employment duration were assigned an explicit <code>missing</code> level, on the judgement that an applicant who skips a field differs from one who fills it in. Each decision was defensible on its own, and together they are the model’s feature engineering. A network would have made none of them.</p>
</section>
<section id="the-curse-of-dimensionality-arrives-as-a-column-count" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="the-curse-of-dimensionality-arrives-as-a-column-count"><span class="header-section-number">1.2</span> The curse of dimensionality arrives as a column count</h2>
<p>Hand-classing works while the covariate count is small enough for a person to look at every variable. Credit data left that regime some time ago.</p>
<p>The credit card portfolio this lecture uses carries 1,214 anonymised features per account, arranged in four blocks: 48 on-us attributes, 664 transaction attributes, 452 bureau attributes and 50 bureau enquiry attributes. Two of the bureau columns arrive as strings and are empty for every account, so 1,212 columns are numeric and enter the design matrix below. Nobody classed 1,214 variables by hand, and nobody will. The transaction block alone is almost certainly a set of aggregates computed over a customer-month panel before the file was released, which is to say somebody’s feature engineering has already happened and has been frozen into the data; that reading is an inference from the shape of the columns rather than a documented fact, and it should be hedged accordingly. Meanwhile a telematics feed, a text field, a bureau timeline or a transaction stream arrives with no natural finite covariate list at all.</p>
<p>Consequently the actuarial question shifts. Instead of asking which transformation of which variable to admit, we ask what the architecture should be allowed to learn, and how to tell whether what it learned is worth having.</p>
</section>
<section id="historical-perspective" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="historical-perspective"><span class="header-section-number">1.3</span> Historical perspective</h2>
<p>The course sets out the machine learning strand of the history, and we take it as theirs: the McCulloch-Pitts neuron in 1943, Rosenblatt’s perceptron in 1958, the first AI winter after Minsky and Papert in 1969, the popularisation of back-propagation by Rumelhart, Hinton and Williams in 1986, the universal approximation theorems of Cybenko and Hornik between 1989 and 1991, long short-term memory and LeNet-5 in the late 1990s, AlexNet’s 2012 breakthrough in computer vision, sequence-to-sequence models and residual networks between 2014 and 2016, the Transformer in 2017, and foundation models from 2020. Their scaling-laws slide makes the point that compute, data and depth improve performance together and predictably.</p>
<p>Credit risk has its own strand, and it is older than the actuarial one. Discriminant analysis on financial ratios dates to Altman’s 1968 Z-score, and logistic regression entered consumer credit scoring in the late 1970s and early 1980s, which is why the logistic GLM of the second lecture is the industry’s incumbent rather than one option among many. Basel II made the internal ratings based approach a capital methodology in 2004, and in doing so it attached a regulatory apparatus to the PD model that no insurance pricing model carries. Machine learning classifiers were benchmarked against scorecards by Baesens and co-authors in 2003 and again by Lessmann and co-authors in 2015, with the consistent finding that the gains are real and modest. Deep learning arrived later here than in vision or language, and the reason is not technical.</p>
</section>
<section id="what-the-regulator-asks-in-return" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="what-the-regulator-asks-in-return"><span class="header-section-number">1.4</span> What the regulator asks in return</h2>
<p>The reason is that a credit decision is a decision about a person, and it has to be explainable to that person. A declined applicant is entitled to know why. A supervisor reviewing an IRB model expects each risk driver to have an economic rationale, a stable relationship to default, and a documented rank ordering. Under the EU AI Act, creditworthiness assessment of natural persons sits in Annex III among the high-risk uses, with obligations on data governance, documentation and human oversight attached. The European Banking Authority’s 2021 discussion paper on machine learning for IRB models, and its 2023 follow-up report, take the same line from the prudential side: the technique is not prohibited, and the burden of explanation rises with its complexity.</p>
<p>Hence the architectures this course spends most of its time on are exactly the ones a credit modeller needs. LocalGLMnet learns a GLM whose coefficients vary with the covariates, so every prediction decomposes into per-variable contributions that read like a scorecard’s points. The CANN keeps the approved GLM as its baseline and learns only a correction to it. Both are attempts to buy the flexibility of a network without surrendering the account of itself that a credit model has to give.</p>
</section>
</section>
<section id="representation-learning-the-core-principle" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Representation learning: the core principle</h1>
<section id="the-idea-stated-formally" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="the-idea-stated-formally"><span class="header-section-number">2.1</span> The idea, stated formally</h2>
<p>Representation learning is the machine learning technique in which the algorithm designs the features. Given covariates <span class="math inline">\(\boldsymbol{X} \in \mathbb{R}^{q}\)</span> and a response <span class="math inline">\(D\)</span>, we seek a mapping</p>
<p><span class="math display">\[
\phi : \mathbb{R}^{q} \to \mathbb{R}^{p},
\qquad
\boldsymbol{Z} = \phi(\boldsymbol{X}),
\qquad p \ll q,
\]</span></p>
<p>such that simple predictors acting on <span class="math inline">\(\boldsymbol{Z}\)</span> perform well (Bengio, Courville and Vincent, 2013). The classical members of this family are principal component analysis and partial least squares, both linear. Deep learning is the version in which <span class="math inline">\(\phi\)</span> is a composition of many non-linear layers, so the features of one layer are built from the features of the layer below, and the hierarchy is what lets a modest parameter count express an intricate transformation.</p>
<p>Depth earns its place through that hierarchy. A shallow network can approximate a complicated function, and to do so it needs to be very wide, in the way a step function approximates a diagonal line only by taking many steps. Deeper layers instead compose: early layers detect simple structure and later layers combine it into abstractions, which is visible directly in the convolutional filters that Zeiler and Fergus (2014) visualised, where layer one finds edges and layer five finds objects.</p>
<p>The word “simple” in the definition above is doing quiet work, and the rest of this section is about it. A representation is good relative to a task, so a compression that is excellent for one purpose can be useless for another. The authors’ Fashion-MNIST example picks a case where the two purposes coincide. Credit, as we are about to see, is not so obliging.</p>
</section>
<section id="the-credit-card-portfolio" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="the-credit-card-portfolio"><span class="header-section-number">2.2</span> The credit card portfolio</h2>
<p>The dataset is an anonymised credit card book of 96,806 accounts, released as a development and validation pair, with a <code>bad_flag</code> on the development file at 1.42 per cent and no flag at all on the validation file. It is the opposite of Bondora in every respect that matters here. The features carry no meaning a modeller could interpret, so there is no GLM story to tell about any coefficient, and the 1.42 per cent bad rate reproduces the rare-event regime of the course’s claim counts rather than Bondora’s 29 per cent. That combination, wide and anonymous and imbalanced, is exactly the regime in which hand-crafted features are impossible and automated ones are the only option on the table.</p>
<p>One structural feature of the file matters for what follows. A block of 626 columns, comprising every on-us and transaction attribute, is missing together for the same 25,231 accounts, or 26.1 per cent of the book. Those accounts have no on-us record and are described by bureau data alone. The missingness is therefore a fact about the account rather than a defect in the file, and a representation of this portfolio has to accommodate two populations described by different variables.</p>
<div id="fb8b77ea" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> time</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> polars <span class="im">as</span> pl</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn <span class="im">as</span> nn</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.decomposition <span class="im">import</span> PCA</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> roc_auc_score</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>dat <span class="op">=</span> pl.read_parquet(<span class="st">"../data/credit_card_dev.parquet"</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>feat <span class="op">=</span> [c <span class="cf">for</span> c, t <span class="kw">in</span> <span class="bu">zip</span>(dat.columns, dat.dtypes)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> t <span class="op">!=</span> pl.String <span class="kw">and</span> c <span class="kw">not</span> <span class="kw">in</span> (<span class="st">"account_number"</span>, <span class="st">"bad_flag"</span>)]</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> dat[<span class="st">"bad_flag"</span>].to_numpy().astype(np.float32)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> dat.select(feat).to_numpy().astype(np.float32)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>dat<span class="sc">.</span>height<span class="sc">:,}</span><span class="ss"> accounts, </span><span class="sc">{</span><span class="bu">len</span>(feat)<span class="sc">:,}</span><span class="ss"> numeric features, "</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"bad rate </span><span class="sc">{</span>y<span class="sc">.</span>mean()<span class="sc">:.4%}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>96,806 accounts, 1,212 numeric features, bad rate 1.4173%</code></pre>
</div>
</div>
</section>
<section id="pre-processing-and-one-decision-that-turned-out-to-matter" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="pre-processing-and-one-decision-that-turned-out-to-matter"><span class="header-section-number">2.3</span> Pre-processing, and one decision that turned out to matter</h2>
<p>The design matrix is built in four steps, all fitted on the learning sample alone. Missing values are replaced by the column median, the columns are centred and scaled, the 54 columns that are constant on the learning sample are dropped, and the standardised values are clipped to <span class="math inline">\(\pm 10\)</span> standard deviations.</p>
<p>The clipping is the step worth stating openly, because it is the one that decided whether the supervised network below trained at all. Several of these columns are monetary aggregates with extremely heavy right tails, and after standardisation a handful of accounts sit hundreds of standard deviations from the mean. Gradient descent on such a matrix takes enormous steps on the batches containing those rows, and in a diagnostic run without the clip, not reproduced in this document, the supervised network never recovered from them and finished at a test AUC of about 0.62, below the principal components it should have beaten. Clipping at ten standard deviations left the ranking of every account intact and lifted it to the 0.82 reported below. The course’s own covariate pre-processing section says to standardise; on credit data with monetary tails, saying so is not quite enough.</p>
<div id="a5f266d2" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">1</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>perm <span class="op">=</span> rng.permutation(<span class="bu">len</span>(X))</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>n_learn <span class="op">=</span> <span class="bu">int</span>(<span class="fl">0.8</span> <span class="op">*</span> <span class="bu">len</span>(X))</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>learn, test <span class="op">=</span> perm[:n_learn], perm[n_learn:]</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>med <span class="op">=</span> np.nan_to_num(np.nanmedian(X[learn], axis<span class="op">=</span><span class="dv">0</span>))</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> np.where(np.isnan(X), med, X)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>mu, sd <span class="op">=</span> X[learn].mean(<span class="dv">0</span>), X[learn].std(<span class="dv">0</span>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>keep <span class="op">=</span> sd <span class="op">&gt;</span> <span class="dv">0</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> np.clip((X[:, keep] <span class="op">-</span> mu[keep]) <span class="op">/</span> sd[keep], <span class="op">-</span><span class="dv">10</span>, <span class="dv">10</span>).astype(np.float32)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"design matrix </span><span class="sc">{</span>X<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">:,}</span><span class="ss"> x </span><span class="sc">{</span>X<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">:,}</span><span class="ss"> "</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"(dropped </span><span class="sc">{</span><span class="bu">int</span>((<span class="op">~</span>keep).<span class="bu">sum</span>())<span class="sc">}</span><span class="ss"> constant columns)"</span>)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"learn </span><span class="sc">{</span><span class="bu">len</span>(learn)<span class="sc">:,}</span><span class="ss"> accounts, </span><span class="sc">{</span><span class="bu">int</span>(y[learn].<span class="bu">sum</span>())<span class="sc">:,}</span><span class="ss"> bad "</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"(</span><span class="sc">{</span>y[learn]<span class="sc">.</span>mean()<span class="sc">:.4%}</span><span class="ss">);  "</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"test </span><span class="sc">{</span><span class="bu">len</span>(test)<span class="sc">:,}</span><span class="ss"> accounts, </span><span class="sc">{</span><span class="bu">int</span>(y[test].<span class="bu">sum</span>())<span class="sc">:,}</span><span class="ss"> bad "</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"(</span><span class="sc">{</span>y[test]<span class="sc">.</span>mean()<span class="sc">:.4%}</span><span class="ss">)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>design matrix 96,806 x 1,158 (dropped 54 constant columns)
learn 77,444 accounts, 1,113 bad (1.4372%);  test 19,362 accounts, 259 bad (1.3377%)</code></pre>
</div>
</div>
<p>The split is random, since this file carries no origination date. The out-of-time contrast that dominated the second lecture is therefore unavailable here, and everything below should be read as the flattering case.</p>
</section>
<section id="three-representations-two-dimensions-each" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="three-representations-two-dimensions-each"><span class="header-section-number">2.4</span> Three representations, two dimensions each</h2>
<p>We compress 1,158 covariates to two dimensions three times over, and then judge each compression by the same standard. Two dimensions is a brutal bottleneck, chosen because it is the authors’ choice and because it can be plotted; the point of the exercise is the comparison rather than the absolute level.</p>
<p>The three mappings differ only in what trains them. <strong>Principal components</strong> minimise linear reconstruction error and are the optimal linear compression at any given width. The <strong>autoencoder</strong> minimises non-linear reconstruction error, passing the covariates through <span class="math inline">\(1158 \to 256 \to 64 \to 2\)</span> and back out again, and it never sees the default flag. The <strong>supervised extractor</strong> is a feed-forward network with a two-neuron penultimate layer, trained on the Bernoulli deviance with dropout and early stopping, so its two features are learned against the response.</p>
<p>Each representation is then scored the same way. A logistic GLM is fitted to the two codes on the learning sample and evaluated on the test sample, using the Bernoulli deviance in <span class="math inline">\(10^{-2}\)</span> units and the AUC, as the second lecture did. The GLM readout is the course’s own architecture read backwards, since a network is a feature extractor composed with a GLM, and holding the readout fixed isolates the quality of the features.</p>
<div id="5a5bd5ec" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> readout(Z, label):</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    fit <span class="op">=</span> sm.GLM(y[learn], sm.add_constant(Z[learn]),</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                 family<span class="op">=</span>sm.families.Binomial()).fit()</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    p <span class="op">=</span> np.clip(fit.predict(sm.add_constant(Z[test])), <span class="fl">1e-7</span>, <span class="dv">1</span> <span class="op">-</span> <span class="fl">1e-7</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    dev <span class="op">=</span> <span class="dv">100</span> <span class="op">*</span> <span class="dv">2</span> <span class="op">*</span> np.mean(<span class="op">-</span>y[test] <span class="op">*</span> np.log(p) <span class="op">-</span> (<span class="dv">1</span> <span class="op">-</span> y[test]) <span class="op">*</span> np.log(<span class="dv">1</span> <span class="op">-</span> p))</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    auc <span class="op">=</span> roc_auc_score(y[test], p)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>label<span class="sc">:24s}</span><span class="ss"> AUC </span><span class="sc">{</span>auc<span class="sc">:.3f}</span><span class="ss">   deviance </span><span class="sc">{</span>dev<span class="sc">:6.3f}</span><span class="ss">"</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> auc</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>p0 <span class="op">=</span> y[learn].mean()</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>dev0 <span class="op">=</span> <span class="dv">100</span> <span class="op">*</span> <span class="dv">2</span> <span class="op">*</span> np.mean(<span class="op">-</span>y[test] <span class="op">*</span> np.log(p0) <span class="op">-</span> (<span class="dv">1</span> <span class="op">-</span> y[test]) <span class="op">*</span> np.log(<span class="dv">1</span> <span class="op">-</span> p0))</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'null model'</span><span class="sc">:24s}</span><span class="ss"> AUC   -     deviance </span><span class="sc">{</span>dev0<span class="sc">:6.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>null model               AUC   -     deviance 14.207</code></pre>
</div>
</div>
<div id="9ba61a61" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>pca <span class="op">=</span> PCA(n_components<span class="op">=</span><span class="dv">2</span>, random_state<span class="op">=</span><span class="dv">1</span>).fit(X[learn])</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>Z_pca <span class="op">=</span> pca.transform(X)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>recon <span class="op">=</span> pca.inverse_transform(Z_pca)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>mse_pca <span class="op">=</span> np.mean((X[test] <span class="op">-</span> recon[test]) <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"PCA: </span><span class="sc">{</span>pca<span class="sc">.</span>explained_variance_ratio_<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:.1%}</span><span class="ss"> of variance retained, "</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"test reconstruction MSE </span><span class="sc">{</span>mse_pca<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>auc_pca <span class="op">=</span> readout(Z_pca, <span class="st">"PCA codes"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>PCA: 11.5% of variance retained, test reconstruction MSE 0.524
PCA codes                AUC 0.737   deviance 13.510</code></pre>
</div>
</div>
<p>The autoencoder trains on the learning sample for 60 epochs of Adam over mini-batches of 1,024 accounts, on the CPU with every seed fixed, so the numbers below reproduce on re-render.</p>
<div id="0f105a0f" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> fit_autoencoder(seed<span class="op">=</span><span class="dv">1</span>, epochs<span class="op">=</span><span class="dv">60</span>, batch<span class="op">=</span><span class="dv">1024</span>):</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    torch.manual_seed(seed)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    q <span class="op">=</span> X.shape[<span class="dv">1</span>]</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    net <span class="op">=</span> nn.Sequential(</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>        nn.Linear(q, <span class="dv">256</span>), nn.ReLU(), nn.Linear(<span class="dv">256</span>, <span class="dv">64</span>), nn.ReLU(),</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>        nn.Linear(<span class="dv">64</span>, <span class="dv">2</span>),                                   <span class="co"># the bottleneck</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>        nn.Linear(<span class="dv">2</span>, <span class="dv">64</span>), nn.ReLU(), nn.Linear(<span class="dv">64</span>, <span class="dv">256</span>), nn.ReLU(),</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>        nn.Linear(<span class="dv">256</span>, q))</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    Xt <span class="op">=</span> torch.tensor(X)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    opt, mse <span class="op">=</span> torch.optim.Adam(net.parameters()), nn.MSELoss()</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    gen <span class="op">=</span> torch.Generator().manual_seed(seed)</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    idx <span class="op">=</span> torch.tensor(learn)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(epochs):</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>        order <span class="op">=</span> idx[torch.randperm(<span class="bu">len</span>(idx), generator<span class="op">=</span>gen)]</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> chunk <span class="kw">in</span> order.split(batch):</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>            opt.zero_grad()</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>            mse(net(Xt[chunk]), Xt[chunk]).backward()</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>            opt.step()</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>    net.<span class="bu">eval</span>()</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> torch.no_grad():</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>        held <span class="op">=</span> <span class="bu">float</span>(np.mean([mse(net(Xt[c]), Xt[c]).item()</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>                              <span class="cf">for</span> c <span class="kw">in</span> torch.tensor(test).split(<span class="dv">8192</span>)]))</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>        Z <span class="op">=</span> torch.cat([net[:<span class="dv">5</span>](Xt[i:i <span class="op">+</span> <span class="dv">8192</span>])</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>                       <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>, <span class="bu">len</span>(Xt), <span class="dv">8192</span>)]).numpy()</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> Z, held</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>t0 <span class="op">=</span> time.time()</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>Z_ae, mse_ae <span class="op">=</span> fit_autoencoder()</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"autoencoder: test reconstruction MSE </span><span class="sc">{</span>mse_ae<span class="sc">:.3f}</span><span class="ss">, "</span></span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span><span class="dv">1</span> <span class="op">-</span> mse_ae <span class="op">/</span> mse_pca<span class="sc">:.0%}</span><span class="ss"> below PCA  [</span><span class="sc">{</span>time<span class="sc">.</span>time() <span class="op">-</span> t0<span class="sc">:.0f}</span><span class="ss">s]"</span>)</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>auc_ae <span class="op">=</span> readout(Z_ae, <span class="st">"autoencoder codes"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>autoencoder: test reconstruction MSE 0.407, 22% below PCA  [115s]
autoencoder codes        AUC 0.644   deviance 14.052</code></pre>
</div>
</div>
<p>The supervised extractor uses the same machinery the next lecture develops in full: a validation slice carved out of the learning sample, checkpointing on the validation deviance, and early stopping once twenty epochs pass without improvement. Dropout at 0.3 is included because 1,113 bad accounts against 1,158 covariates is a regime in which a network memorises quickly.</p>
<div id="ea5dc324" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> fit_supervised(seed<span class="op">=</span><span class="dv">1</span>, epochs<span class="op">=</span><span class="dv">60</span>, batch<span class="op">=</span><span class="dv">1024</span>, patience<span class="op">=</span><span class="dv">20</span>):</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    torch.manual_seed(seed)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    encoder <span class="op">=</span> nn.Sequential(</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>        nn.Linear(X.shape[<span class="dv">1</span>], <span class="dv">64</span>), nn.ReLU(), nn.Dropout(<span class="fl">0.3</span>),</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>        nn.Linear(<span class="dv">64</span>, <span class="dv">16</span>), nn.ReLU(), nn.Dropout(<span class="fl">0.3</span>),</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>        nn.Linear(<span class="dv">16</span>, <span class="dv">2</span>))                                   <span class="co"># the bottleneck</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    net <span class="op">=</span> nn.Sequential(encoder, nn.Linear(<span class="dv">2</span>, <span class="dv">1</span>))</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    Xt, yt <span class="op">=</span> torch.tensor(X), torch.tensor(y).unsqueeze(<span class="dv">1</span>)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    gen <span class="op">=</span> torch.Generator().manual_seed(seed)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    cut <span class="op">=</span> <span class="bu">int</span>(<span class="fl">0.2</span> <span class="op">*</span> <span class="bu">len</span>(learn))</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    val, fit <span class="op">=</span> torch.tensor(learn[:cut]), torch.tensor(learn[cut:])</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    opt, bce <span class="op">=</span> torch.optim.Adam(net.parameters(), lr<span class="op">=</span><span class="fl">3e-4</span>), nn.BCEWithLogitsLoss()</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>    best, best_epoch, state, hist <span class="op">=</span> np.inf, <span class="dv">0</span>, <span class="va">None</span>, []</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> epoch <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, epochs <span class="op">+</span> <span class="dv">1</span>):</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>        net.train()</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> chunk <span class="kw">in</span> fit[torch.randperm(<span class="bu">len</span>(fit), generator<span class="op">=</span>gen)].split(batch):</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>            opt.zero_grad()</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>            bce(net(Xt[chunk]), yt[chunk]).backward()</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>            opt.step()</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>        net.<span class="bu">eval</span>()</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>        <span class="cf">with</span> torch.no_grad():</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>            hist.append((<span class="dv">200</span> <span class="op">*</span> bce(net(Xt[fit]), yt[fit]).item(),</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>                         <span class="dv">200</span> <span class="op">*</span> bce(net(Xt[val]), yt[val]).item()))</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> hist[<span class="op">-</span><span class="dv">1</span>][<span class="dv">1</span>] <span class="op">&lt;</span> best:</span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a>            best, best_epoch <span class="op">=</span> hist[<span class="op">-</span><span class="dv">1</span>][<span class="dv">1</span>], epoch</span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a>            state <span class="op">=</span> {k: v.clone() <span class="cf">for</span> k, v <span class="kw">in</span> net.state_dict().items()}</span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> epoch <span class="op">-</span> best_epoch <span class="op">&gt;=</span> patience:</span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a>            <span class="cf">break</span></span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a>    net.load_state_dict(state)</span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a>    net.<span class="bu">eval</span>()</span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> torch.no_grad():</span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a>        Z <span class="op">=</span> torch.cat([encoder(Xt[i:i <span class="op">+</span> <span class="dv">8192</span>])</span>
<span id="cb11-33"><a href="#cb11-33" aria-hidden="true" tabindex="-1"></a>                       <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>, <span class="bu">len</span>(Xt), <span class="dv">8192</span>)]).numpy()</span>
<span id="cb11-34"><a href="#cb11-34" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> Z, np.array(hist), best_epoch</span>
<span id="cb11-35"><a href="#cb11-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-36"><a href="#cb11-36" aria-hidden="true" tabindex="-1"></a>t0 <span class="op">=</span> time.time()</span>
<span id="cb11-37"><a href="#cb11-37" aria-hidden="true" tabindex="-1"></a>Z_sup, hist, stop <span class="op">=</span> fit_supervised()</span>
<span id="cb11-38"><a href="#cb11-38" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"supervised extractor: validation optimum at epoch </span><span class="sc">{</span>stop<span class="sc">}</span><span class="ss"> of "</span></span>
<span id="cb11-39"><a href="#cb11-39" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span><span class="bu">len</span>(hist)<span class="sc">}</span><span class="ss"> run  [</span><span class="sc">{</span>time<span class="sc">.</span>time() <span class="op">-</span> t0<span class="sc">:.0f}</span><span class="ss">s]"</span>)</span>
<span id="cb11-40"><a href="#cb11-40" aria-hidden="true" tabindex="-1"></a>auc_sup <span class="op">=</span> readout(Z_sup, <span class="st">"supervised features"</span>)</span>
<span id="cb11-41"><a href="#cb11-41" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"correlation of the two supervised coordinates: "</span></span>
<span id="cb11-42"><a href="#cb11-42" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>np<span class="sc">.</span>corrcoef(Z_sup[:, <span class="dv">0</span>], Z_sup[:, <span class="dv">1</span>])[<span class="dv">0</span>, <span class="dv">1</span>]<span class="sc">:+.2f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>supervised extractor: validation optimum at epoch 9 of 29 run  [25s]
supervised features      AUC 0.820   deviance 12.328
correlation of the two supervised coordinates: -0.97</code></pre>
</div>
</div>
</section>
<section id="what-the-comparison-shows" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="what-the-comparison-shows"><span class="header-section-number">2.5</span> What the comparison shows</h2>
<p>The autoencoder wins the contest it was entered for and loses the one that matters. Its test reconstruction error of 0.407 is 22 per cent below the 0.524 that two principal components achieve, so the non-linear compression does capture structure the optimal linear compression of the same width cannot reach. It is a better summary of the portfolio by its own standard. Then the readout reverses the ranking. A logistic GLM on the autoencoder’s two codes scores an AUC of 0.644 against 0.737 for the principal components, and its test deviance of 14.052 sits barely below the null model’s 14.207. Two dimensions of unsupervised non-linear compression have discarded almost all of the default signal in the book.</p>
<p>The supervised extractor, at the same two dimensions and through the same readout, reaches an AUC of 0.820 and a deviance of 12.328. The data are identical, the bottleneck width is identical, and the only thing that changed is the loss that trained the mapping.</p>
<div id="4efd1ec0" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>panels <span class="op">=</span> [(<span class="ss">f"PCA, AUC </span><span class="sc">{</span>auc_pca<span class="sc">:.3f}</span><span class="ss">"</span>, Z_pca),</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>          (<span class="ss">f"autoencoder, AUC </span><span class="sc">{</span>auc_ae<span class="sc">:.3f}</span><span class="ss">"</span>, Z_ae),</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>          (<span class="ss">f"supervised FNN, AUC </span><span class="sc">{</span>auc_sup<span class="sc">:.3f}</span><span class="ss">"</span>, Z_sup)]</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>good, bad <span class="op">=</span> y <span class="op">==</span> <span class="dv">0</span>, y <span class="op">==</span> <span class="dv">1</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>fig, axs <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="fl">3.2</span>))</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, (title, Z) <span class="kw">in</span> <span class="bu">zip</span>(axs, panels):</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>    ax.scatter(Z[good, <span class="dv">0</span>], Z[good, <span class="dv">1</span>], s<span class="op">=</span><span class="dv">1</span>, c<span class="op">=</span><span class="st">"#8A8377"</span>, alpha<span class="op">=</span><span class="fl">0.03</span>, lw<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    ax.scatter(Z[bad, <span class="dv">0</span>], Z[bad, <span class="dv">1</span>], s<span class="op">=</span><span class="dv">3</span>, c<span class="op">=</span><span class="st">"#8C2F1E"</span>, alpha<span class="op">=</span><span class="fl">0.5</span>, lw<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>    lo, hi <span class="op">=</span> np.percentile(Z, <span class="fl">0.2</span>, axis<span class="op">=</span><span class="dv">0</span>), np.percentile(Z, <span class="fl">99.8</span>, axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>    ax.set_xlim(lo[<span class="dv">0</span>], hi[<span class="dv">0</span>])<span class="op">;</span> ax.set_ylim(lo[<span class="dv">1</span>], hi[<span class="dv">1</span>])</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>    ax.set_title(title, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>    ax.set_xticks([])<span class="op">;</span> ax.set_yticks([])</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> spine <span class="kw">in</span> ax.spines.values():</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>        spine.set_visible(<span class="va">False</span>)</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_credit-deep-learning-overview_files/figure-html/cell-8-output-1.png" width="1335" height="464" class="figure-img"></p>
<figcaption>Each panel plots all 96,806 accounts in the two dimensions of one representation: 95,434 good accounts in grey and 1,372 bad accounts overplotted in red. Bad accounts are drawn on top and at a larger marker size, so the eye sees them out of proportion to their 1.42 per cent share of the book. Axes are unlabelled because the coordinates are arbitrary; the axis limits trim the outer 0.2 per cent of each representation so the bulk is visible. Panel scales are not comparable with one another.</figcaption>
</figure>
</div>
</div>
</div>
<p>The figure says the same thing without any statistic. Under the principal components the bad accounts crowd towards one edge of the cloud while remaining thoroughly mixed with the good ones. Under the autoencoder they scatter along the spikes of a star-shaped manifold with no region that is distinctively theirs, which is what an AUC of 0.644 looks like. Under the supervised extractor the whole book collapses onto a ridge and the bad accounts occupy one end of it.</p>
<p>That collapse is worth a remark of its own. The correlation between the supervised extractor’s two coordinates is <span class="math inline">\(-0.97\)</span>, so the network given two dimensions used approximately one. There is a single thing to predict and the deviance rewards nothing else, hence the extractor learns a scalar score and the second neuron is close to redundant. An unsupervised objective faces no such pressure and spreads itself over whatever the covariance structure offers.</p>
<div id="267fad57" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>fig, axs <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="fl">2.8</span>), sharey<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, (title, Z) <span class="kw">in</span> <span class="bu">zip</span>(axs, panels):</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    score <span class="op">=</span> Z[:, <span class="dv">0</span>] <span class="op">*</span> np.sign(np.corrcoef(Z[:, <span class="dv">0</span>], y)[<span class="dv">0</span>, <span class="dv">1</span>])</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    decile <span class="op">=</span> np.searchsorted(np.quantile(score, np.linspace(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">11</span>)[<span class="dv">1</span>:<span class="op">-</span><span class="dv">1</span>]), score)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    rate <span class="op">=</span> np.array([<span class="dv">100</span> <span class="op">*</span> y[decile <span class="op">==</span> k].mean() <span class="cf">for</span> k <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">10</span>)])</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    ax.bar(<span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">11</span>), rate, color<span class="op">=</span><span class="st">"#8A8377"</span>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    ax.bar([<span class="dv">10</span>], [rate[<span class="dv">9</span>]], color<span class="op">=</span><span class="st">"#8C2F1E"</span>)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    ax.axhline(<span class="dv">100</span> <span class="op">*</span> y.mean(), color<span class="op">=</span><span class="st">"#3B4A75"</span>, ls<span class="op">=</span><span class="st">"--"</span>, lw<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    ax.set_title(title.split(<span class="st">","</span>)[<span class="dv">0</span>], fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>    ax.set_xticks([<span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">10</span>])<span class="op">;</span> ax.set_xlabel(<span class="st">"decile of first coordinate"</span>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> spine <span class="kw">in</span> (<span class="st">"top"</span>, <span class="st">"right"</span>):</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>        ax.spines[spine].set_visible(<span class="va">False</span>)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>axs[<span class="dv">0</span>].set_ylabel(<span class="st">"bad rate (%)"</span>)</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_credit-deep-learning-overview_files/figure-html/cell-9-output-1.png" width="1336" height="406" class="figure-img"></p>
<figcaption>Observed bad rate by decile of each representation’s first coordinate, on a shared vertical scale, with the portfolio’s 1.42 per cent rate marked by the dashed line and the top decile in red. Each coordinate is oriented so that higher means riskier. The supervised representation ramps monotonically to 7.5 per cent in the top decile; the two unsupervised representations peak before their top decile and then fall back.</figcaption>
</figure>
</div>
</div>
</div>
<p>The decile view adds the detail an AUC hides. The supervised score ramps monotonically from 0.1 per cent in its safest decile to 7.5 per cent in its riskiest, a lift of 5.3 times the portfolio rate, which is the shape a credit committee expects of a scorecard. The PCA score peaks in its eighth decile and the autoencoder score in its ninth, and both then fall back in the tenth, so neither is monotone in default risk. A rating system built on either would need its grades reordered by hand before anyone could use it.</p>
</section>
<section id="why-the-autoencoder-loses-measured-rather-than-asserted" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="why-the-autoencoder-loses-measured-rather-than-asserted"><span class="header-section-number">2.6</span> Why the autoencoder loses, measured rather than asserted</h2>
<p>The mechanism is general, and here it can be checked. Reconstruction error is dominated by the directions carrying the most variance and by the blocks holding the most columns, whereas default is a rare event that need not live in either. The four column blocks let us test that directly, by measuring how much individual default signal each block carries per column against how much of the leading principal component’s loading it attracts.</p>
<div id="c44be64a" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> block_of(name):</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> name.startswith(<span class="st">"bureau_enquiry"</span>): <span class="cf">return</span> <span class="st">"bureau enquiry"</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> name.startswith(<span class="st">"bureau"</span>): <span class="cf">return</span> <span class="st">"bureau"</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> name.startswith(<span class="st">"onus"</span>): <span class="cf">return</span> <span class="st">"on-us"</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="st">"transaction"</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>kept <span class="op">=</span> np.array([block_of(f) <span class="cf">for</span> f, k <span class="kw">in</span> <span class="bu">zip</span>(feat, keep) <span class="cf">if</span> k])</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>signal <span class="op">=</span> np.array([<span class="bu">abs</span>(roc_auc_score(y, X[:, j]) <span class="op">-</span> <span class="fl">0.5</span>)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>                   <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(X.shape[<span class="dv">1</span>])])</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>loading <span class="op">=</span> pca.components_[<span class="dv">0</span>] <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> b <span class="kw">in</span> [<span class="st">"on-us"</span>, <span class="st">"transaction"</span>, <span class="st">"bureau"</span>, <span class="st">"bureau enquiry"</span>]:</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>    m <span class="op">=</span> kept <span class="op">==</span> b</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>b<span class="sc">:15s}</span><span class="ss"> </span><span class="sc">{</span>m<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:4d}</span><span class="ss"> columns (</span><span class="sc">{</span>m<span class="sc">.</span><span class="bu">sum</span>() <span class="op">/</span> <span class="bu">len</span>(kept)<span class="sc">:5.1%}</span><span class="ss">)   "</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"mean |AUC-0.5| </span><span class="sc">{</span>signal[m]<span class="sc">.</span>mean()<span class="sc">:.4f}</span><span class="ss">   "</span></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"PC1 loading share </span><span class="sc">{</span>loading[m]<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>on-us             47 columns ( 4.1%)   mean |AUC-0.5| 0.0721   PC1 loading share 0.006
transaction      658 columns (56.8%)   mean |AUC-0.5| 0.0132   PC1 loading share 0.006
bureau           408 columns (35.2%)   mean |AUC-0.5| 0.0302   PC1 loading share 0.970
bureau enquiry    45 columns ( 3.9%)   mean |AUC-0.5| 0.0710   PC1 loading share 0.018</code></pre>
</div>
</div>
<p>The numbers are stark. The two blocks carrying the most default signal per column are the 47 on-us attributes and the 45 bureau enquiry attributes, each averaging an individual AUC about 0.072 away from a coin flip. Between them they are 8 per cent of the matrix, and they attract 2.4 per cent of the leading principal component’s loading. That component instead puts 97 per cent of its weight on the bureau block, which is middling per column and large. Meanwhile the transaction block is 56.8 per cent of the matrix and averages 0.013, so more than half the covariates carry almost no individual default signal at all while consuming more than half of any reconstruction budget.</p>
<p>Consequently an unsupervised representation of this portfolio is largely a representation of the bureau block, and default does not live there in proportion. What the bureau columns actually measure cannot be checked, since the file is anonymised, so treat any account of why they dominate the variance as inference rather than as a finding; the loading share itself is measured. The general result stands whatever they turn out to be. Wherever the loudest variation in a dataset is not the variation the response cares about, reconstruction and discrimination pull apart, and only the objective that names the response gets the second one right.</p>
<p>This is why the course trains its feature extractor on the deviance. The next lecture builds exactly that network, and the reason it is worth building rather than pre-training an autoencoder is the 0.644 above.</p>
</section>
</section>
<section id="feed-forward-networks-generalise-the-logistic-glm" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Feed-forward networks generalise the logistic GLM</h1>
<section id="a-single-layer-is-a-scorecard" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="a-single-layer-is-a-scorecard"><span class="header-section-number">3.1</span> A single layer is a scorecard</h2>
<p>The architecture the rest of the series depends on can be introduced from where the second lecture stopped. Draw the covariates as a column of input nodes, connect each to a single output node with its own weight, sum, and pass the sum through an inverse link. The result is</p>
<p><span class="math display">\[
\boldsymbol{X} ~\mapsto~ \mu_{\vartheta}(\boldsymbol{X})
= g^{-1}\left( \vartheta_0 + \langle \vartheta, \boldsymbol{X} \rangle \right),
\]</span></p>
<p>which is the GLM of the second lecture written as a network. With the logit link and one-hot encoded bands as inputs it is more specific still: it is a scorecard, whose weights are the points awarded per attribute and whose intercept is the base score. A single-layer network is therefore not a new model class for credit at all, and the course’s point is the converse one, that a network is the object a scorecard sits inside.</p>
</section>
<section id="depth-and-what-the-layers-do" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="depth-and-what-the-layers-do"><span class="header-section-number">3.2</span> Depth, and what the layers do</h2>
<p>Depth means several transformations applied in sequence. Write <span class="math inline">\(\boldsymbol{z}^{(m)} : \mathbb{R}^{q_{m-1}} \to \mathbb{R}^{q_m}\)</span> for the <span class="math inline">\(m\)</span>-th hidden layer, with <span class="math inline">\(q_m\)</span> neurons, and compose them, <span class="math inline">\(\boldsymbol{z}^{(d:1)} = \boldsymbol{z}^{(d)} \circ \cdots \circ \boldsymbol{z}^{(1)}\)</span>. The regression function becomes</p>
<p><span class="math display">\[
\boldsymbol{X} ~\mapsto~ \mu_{\vartheta}(\boldsymbol{X})
= g^{-1}\left( w_0^{(d+1)}
+ \langle \boldsymbol{w}^{(d+1)}, \boldsymbol{z}^{(d:1)}(\boldsymbol{X}) \rangle \right),
\]</span></p>
<p>which is the equation the second lecture closed on. Read from the right, the composition is the feature extractor and the final layer is a GLM on the features it produces. Read from the left, the whole thing is one parametrised family fitted by gradient descent. Both readings are used constantly, and the first is what licenses stripping the last layer off a trained network and feeding its features to something else, e.g.&nbsp;a gradient boosting machine or, as in the section above, a logistic GLM.</p>
<p>Inside each layer the transformation happens in two steps. The <strong>pre-activation</strong> is an affine map, <span class="math inline">\(\boldsymbol{w}_0^{(m)} + W^{(m)} \boldsymbol{x} \in \mathbb{R}^{q_m}\)</span>, with weight matrix <span class="math inline">\(W^{(m)} \in \mathbb{R}^{q_m \times q_{m-1}}\)</span> and bias <span class="math inline">\(\boldsymbol{w}_0^{(m)}\)</span>. The <strong>post-activation</strong> applies a non-linear function <span class="math inline">\(\phi\)</span> componentwise,</p>
<p><span class="math display">\[
\boldsymbol{x} ~\mapsto~ \boldsymbol{z}^{(m)}(\boldsymbol{x})
= \phi\left( \boldsymbol{w}_0^{(m)} + W^{(m)} \boldsymbol{x} \right)
\in \mathbb{R}^{q_m},
\]</span></p>
<p>so every individual neuron is itself a GLM with <span class="math inline">\(\phi\)</span> as its inverse link. The non-linearity is what makes depth worth having, since a composition of affine maps is affine and a network without activations collapses to the single-layer scorecard above however many layers it has.</p>
<p>The next lecture develops all of this properly, counts the parameters, states the universality theorems and fits the network to the Bondora book. Here it is enough to have the shape.</p>
</section>
</section>
<section id="architectures-beyond-the-tabular-cross-section" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Architectures beyond the tabular cross-section</h1>
<section id="from-vectors-to-tensors" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="from-vectors-to-tensors"><span class="header-section-number">4.1</span> From vectors to tensors</h2>
<p>Everything so far treats a borrower as a vector. Credit data often has more structure than that, and the architectures in this section are the ones that respect it. A time series of statements is a matrix <span class="math inline">\(\boldsymbol{X}_{1:t} \in \mathbb{R}^{t \times q}\)</span>, an image is a three-dimensional array, and a panel is a set of sequences of differing length.</p>
<p>This series has one dataset of each kind, which is worth setting out plainly because it determines which lectures can demonstrate what. Bondora is a pure cross-section: 45 application-time columns per loan, one row per borrower. The credit card portfolio is also a cross-section, although a peculiar one, since its 664 transaction attributes are aggregates that somebody computed over a history before releasing the file. The Amex book is the genuine article, 5,531,451 customer-month statements across 458,913 customers, up to 13 statements each, right-aligned on a common March 2018 cut-off, with 190 anonymised risk variables per statement. A customer there is a <span class="math inline">\(13 \times 190\)</span> tensor.</p>
<p>The credit card file and the Amex panel therefore sit at the two ends of one choice. Either a human decides which windows and which summaries to compute and hands the model a wide cross-section, or the model reads the sequence and learns the summaries. The demo above is a warning about the first route, since 56.8 per cent of that matrix turned out to carry almost no individual default signal, and nobody downstream can tell which aggregation decision cost them what.</p>
</section>
<section id="convolutional-networks-and-an-honest-word-about-credit" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="convolutional-networks-and-an-honest-word-about-credit"><span class="header-section-number">4.2</span> Convolutional networks, and an honest word about credit</h2>
<p>A convolutional layer replaces the full connectivity of a network with a window. One filter of kernel size <span class="math inline">\(K\)</span> is applied at every position of the input, so a one-dimensional convolution over a statement history computes</p>
<p><span class="math display">\[
z_{u,j}^{(1)} = \phi\left( w_{0,j}^{(1)}
+ \sum_{k=1}^{K} \langle \boldsymbol{w}_{k,j}^{(1)}, \boldsymbol{X}_{u-1+k} \rangle \right),
\]</span></p>
<p>for filter <span class="math inline">\(j\)</span> at position <span class="math inline">\(u\)</span>. Two properties follow. Local connectivity keeps the parameter count small, and parameter sharing means a pattern is recognised wherever in the window it occurs.</p>
<p>That second property is the one with a credit use. A filter of width three over a delinquency sequence can learn the shape “two months late and then cured” and fire on it whether it happened in month two or month eleven, which is exactly the kind of behavioural pattern a hand-built aggregate such as “maximum delinquency in the last twelve months” flattens away.</p>
<p>The two-dimensional case is thinner here, and it is better to say so than to manufacture a use. Credit has no pixel grid. Geographic default surfaces are the honest exception, and at the granularity a lender actually holds they are usually too sparse to convolve. Telematics heatmaps are an insurance example rather than a credit one. Consequently the convolutional material in this course earns its place in credit through the one-dimensional case and through the vocabulary it gives the attention lectures.</p>
</section>
<section id="recurrent-networks-and-behavioural-scoring" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="recurrent-networks-and-behavioural-scoring"><span class="header-section-number">4.3</span> Recurrent networks and behavioural scoring</h2>
<p>A recurrent layer carries a hidden state forward,</p>
<p><span class="math display">\[
z_{u,j}^{(1)} = \phi\left( w_{0,j}^{(1)}
+ \langle \boldsymbol{w}_j^{(1)}, \boldsymbol{X}_u \rangle
+ \langle \boldsymbol{v}_j^{(1)}, \boldsymbol{z}_{u-1}^{(1)} \rangle \right),
\]</span></p>
<p>so the state at time <span class="math inline">\(u\)</span> summarises everything up to <span class="math inline">\(u\)</span> and the parameters are shared across time. Stated in the language a credit modeller already has, the hidden state is a learned filtration of the account’s history, and behavioural scoring is the problem it was built for. Long short-term memory (Hochreiter and Schmidhuber, 1997) and the simpler gated recurrent unit add gates so that a delinquency eleven months ago can still reach the prediction, which plain recurrence struggles with.</p>
<p>The choice between convolution and recurrence follows from what matters in the data. Convolutions suit local patterns and translation invariance and parallelise well; recurrence suits genuine temporal causality, variable history lengths and long-range dependence. Both are superseded for most purposes by attention, which the transformer lectures take up.</p>
</section>
<section id="embedding-layers-for-categorical-covariates" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="embedding-layers-for-categorical-covariates"><span class="header-section-number">4.4</span> Embedding layers for categorical covariates</h2>
<p>Categorical covariates are where credit and insurance meet most directly. One-hot encoding, which the second lecture used for country, education and employment duration, expresses the prior that the levels are orthogonal, so nothing learned about Estonia informs the estimate for Finland. Actuarial practice has a standard answer to that, namely Bühlmann credibility, which shrinks a level’s estimate towards the collective.</p>
<p>An embedding layer is the network’s version. Each level is assigned a dense vector of modest dimension, the vectors are trained with the rest of the model, and levels that behave alike end up close together. The payoff grows with cardinality, and credit is full of high-cardinality fields where a one-hot column per level is hopeless: postcode, employer, merchant category, dealer, broker. Richman and Wüthrich (2024) regularise these embeddings by variational inference, which recovers the credibility shrinkage explicitly and is the right reference for anyone who has to defend an embedding to a model risk function.</p>
</section>
<section id="autoencoders-attention-and-interpretable-networks" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="autoencoders-attention-and-interpretable-networks"><span class="header-section-number">4.5</span> Autoencoders, attention and interpretable networks</h2>
<p>Three further ideas belong in the overview, and each has its own lecture later.</p>
<p>The <strong>autoencoder</strong> is the unsupervised architecture the demo above used: a network trained to reproduce its own input through a bottleneck, performing a non-linear analogue of principal components without the orthonormality constraint. The bottleneck encodes the prior that the data lie near a low-dimensional manifold. As measured above, that prior is about the covariates rather than about default.</p>
<p><strong>Attention</strong> (Vaswani et al., 2017) computes <span class="math inline">\(\mathrm{softmax}(QK^{\top}/\sqrt{d})\,V\)</span> from query, key and value matrices, letting every element of a sequence attend to every other and producing contextualised representations. It parallelises where recurrence cannot and reaches arbitrarily far back. The Credibility Transformer lectures build it in full, and the Amex panel is the dataset in this series it was made for.</p>
<p><strong>LocalGLMnet</strong> (Richman and Wüthrich, 2023) is the interpretability architecture, and in credit it is arguably the most important idea in the course. A network learns coefficients <span class="math inline">\(w_j(\boldsymbol{X})\)</span> that vary with the covariates, and the prediction is <span class="math inline">\(\sum_j w_j(\boldsymbol{X}) X_j\)</span>, so every individual decision decomposes into per-variable contributions. A lender that has to issue reason codes with a declined application needs precisely that decomposition, and getting it from a fitted structure rather than from a post hoc attribution method is a materially stronger position in front of a supervisor.</p>
</section>
</section>
<section id="combined-actuarial-neural-network" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Combined actuarial neural network</h1>
<section id="the-scorecard-the-credit-committee-already-approved" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="the-scorecard-the-credit-committee-already-approved"><span class="header-section-number">5.1</span> The scorecard the credit committee already approved</h2>
<p>The CANN (Wüthrich and Merz, 2019) resolves the tension this lecture opened with. GLMs are interpretable and may miss structure; networks find structure and explain themselves poorly. Rather than choosing, the CANN adds them:</p>
<p><span class="math display">\[
\mu^{\mathrm{CANN}}(\boldsymbol{X})
= g^{-1}\Bigl(
\underbrace{\langle \widehat{\vartheta}^{\,\mathrm{MLE}}, \boldsymbol{X} \rangle}_{\text{GLM baseline}}
+ \underbrace{\langle \boldsymbol{w}^{(d+1)}, \boldsymbol{z}^{(d:1)}(\boldsymbol{X}) \rangle}_{\text{network correction}}
\Bigr).
\]</span></p>
<p>Training runs in two steps. First the GLM is fitted by maximum likelihood and its parameters are frozen, which for a PD model means the logistic GLM of the second lecture with the logit as canonical link. Then the network is trained to learn what the GLM left on the table, entering the linear predictor as an additive term. He and co-authors (2016) supply the reading that makes the architecture feel inevitable: the GLM term is a skip connection, the network term is the residual branch, and the CANN is a residual network whose skip path happens to be a model somebody has already signed off.</p>
<p>That last clause is why the CANN travels better in credit than almost anything else in the course. A network fitted from scratch replaces an approved model, and replacing an approved PD model means a new development document, a new validation, a new use test and a supervisory conversation. A CANN keeps the approved model as its baseline and adds an increment, so the increment is the thing to be measured, bounded, monitored and, if it misbehaves, switched off. The GLM also keeps predictions sane wherever the network has learned nothing useful, and the size of the correction is itself a diagnostic that says where the scorecard is thin.</p>
</section>
<section id="the-degenerate-cann-is-already-industry-practice" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="the-degenerate-cann-is-already-industry-practice"><span class="header-section-number">5.2</span> The degenerate CANN is already industry practice</h2>
<p>The second credit lecture ended on a piece of standing practice: when a scorecard’s ranking survives a shift in the book while its level does not, lenders keep the coefficients and recalibrate the intercept to the current central tendency. In CANN notation that is a correction term restricted to a constant. Reading it that way makes the generalisation obvious, since a constant correction repairs the level everywhere and a learned correction repairs it where it is actually wrong.</p>
<p>One caution carries over from the next lecture. The balance property, i.e. that fitted probabilities sum to observed defaults on the learning sample, holds because the canonical-link GLM’s score equations force it. Adding a network term to the linear predictor breaks those equations, so a CANN inherits its baseline’s calibration only in the sense that it starts from it. Auto-calibration has to be imposed rather than assumed, which is the subject of the calibration lecture.</p>
</section>
</section>
<section id="takeaways-and-outlook" class="level1 unnumbered">
<h1 class="unnumbered">Takeaways and outlook</h1>
<p>Representation learning is the principle that carries the rest of this series, and this lecture’s contribution is to show it is conditional. On a wide anonymised credit card book, a non-linear autoencoder compressed 1,158 covariates to two dimensions and reconstructed the portfolio 22 per cent better than the optimal linear compression of the same width, while a logistic readout on its codes discriminated default barely better than the base rate. The supervised extractor at the same width reached an AUC of 0.820. The measurement in the last section explains it: the blocks with the most default signal per column hold 8 per cent of the matrix and attract 2.4 per cent of the leading principal component, so an objective that follows the variance follows the wrong thing.</p>
<p>Hence the practical rule for credit. Automated feature learning is worth having, and it has to be trained against the loss the model will be judged by. Every architecture in the remaining lectures does exactly that, and the ones that matter most here (entity embeddings for high-cardinality fields, LocalGLMnet for per-decision reason codes, the CANN for an increment on an approved scorecard) are the ones that buy flexibility without giving up the account of itself a credit model has to be able to give.</p>
<p>The next lecture stops surveying and starts fitting. It builds the feed-forward network in full on the Bondora book, states the universality theorems, works through gradient descent and early stopping, and finds out what a network does to the balance property the second lecture proved.</p>
</section>
<section id="copyright-and-attribution" class="level1 unnumbered">
<h1 class="unnumbered">Copyright and attribution</h1>
<p>This document adapts the storyline, structure and notation of <em>Lecture 3: Deep Learning: An Overview</em> from the summer school <strong>Deep Learning for Actuarial Modeling</strong> (Scognamiglio, Maggi and Wüthrich, Università Cattolica del Sacro Cuore, Milano, 2026), part of the project <em>AI Tools for Actuaries</em>, used under CC BY-NC 4.0. Changes made: the slide sequence is recast as prose, the Fashion-MNIST representation-learning example is replaced by an original PCA against autoencoder against supervised extractor comparison on a public credit card portfolio, none of the authors’ figures are reproduced and both figures here are computed from the credit data, the credit scoring history, the regulatory section, the per-block signal measurement, the credit readings of the convolutional and embedding material and the degenerate-CANN observation are new, and the code is Python where the course uses R. The original lecture notes are available at <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5162304" class="uri">https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5162304</a>.</p>
</section>
<section id="references" class="level1 unnumbered">
<h1 class="unnumbered">References</h1>
<ul>
<li>Altman, E.I. (1968). Financial ratios, discriminant analysis and the prediction of corporate bankruptcy. <em>Journal of Finance</em> 23(4), 589-609.</li>
<li>Baesens, B., Van Gestel, T., Viaene, S., Stepanova, M., Suykens, J. and Vanthienen, J. (2003). Benchmarking state-of-the-art classification algorithms for credit scoring. <em>Journal of the Operational Research Society</em> 54(6), 627-635.</li>
<li>Basel Committee on Banking Supervision (2006). <em>International Convergence of Capital Measurement and Capital Standards: a Revised Framework, Comprehensive Version</em>. Bank for International Settlements.</li>
<li>Bengio, Y., Courville, A. and Vincent, P. (2013). Representation learning: a review and new perspectives. <em>IEEE Transactions on Pattern Analysis and Machine Intelligence</em> 35(8), 1798-1828.</li>
<li>Cybenko, G. (1989). Approximation by superpositions of a sigmoidal function. <em>Mathematics of Control, Signals and Systems</em> 2(4), 303-314.</li>
<li>European Banking Authority (2021). <em>Discussion paper on machine learning for IRB models</em>. EBA/DP/2021/04, and its 2023 follow-up report.</li>
<li>European Union (2024). Regulation (EU) 2024/1689 laying down harmonised rules on artificial intelligence, Annex III.</li>
<li>He, K., Zhang, X., Ren, S. and Sun, J. (2016). Deep residual learning for image recognition. <em>Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition</em>, 770-778.</li>
<li>Hochreiter, S. and Schmidhuber, J. (1997). Long short-term memory. <em>Neural Computation</em> 9(8), 1735-1780.</li>
<li>Hornik, K. (1991). Approximation capabilities of multilayer feedforward networks. <em>Neural Networks</em> 4(2), 251-257.</li>
<li>LeCun, Y., Bottou, L., Bengio, Y. and Haffner, P. (1998). Gradient-based learning applied to document recognition. <em>Proceedings of the IEEE</em> 86(11), 2278-2324.</li>
<li>Lessmann, S., Baesens, B., Seow, H.-V. and Thomas, L.C. (2015). Benchmarking state-of-the-art classification algorithms for credit scoring: an update of research. <em>European Journal of Operational Research</em> 247(1), 124-136.</li>
<li>Richman, R. and Wüthrich, M.V. (2023). LocalGLMnet: interpretable deep learning for tabular data. <em>Scandinavian Actuarial Journal</em> 2023(1), 71-95.</li>
<li>Richman, R. and Wüthrich, M.V. (2024). High-cardinality categorical covariates in network regressions. <em>Japanese Journal of Statistics and Data Science</em> 7(2), 921-965.</li>
<li>Vaswani, A., Shazeer, N., Parmar, N., Uszkoreit, J., Jones, L., Gomez, A.N., Kaiser, L. and Polosukhin, I. (2017). Attention is all you need. <em>Advances in Neural Information Processing Systems</em> 30.</li>
<li>Wiginton, J.C. (1980). A note on the comparison of logit and discriminant models of consumer credit behavior. <em>Journal of Financial and Quantitative Analysis</em> 15(3), 757-770.</li>
<li>Wüthrich, M.V. and Merz, M. (2019). Editorial: Yes, we CANN! <em>ASTIN Bulletin</em> 49(1), 1-3.</li>
<li>Wüthrich, M.V. and Merz, M. (2023). <em>Statistical Foundations of Actuarial Learning and its Applications</em>. Springer.</li>
<li>Zeiler, M.D.&nbsp;and Fergus, R. (2014). Visualizing and understanding convolutional networks. <em>Computer Vision - ECCV 2014</em>, 818-833. Springer.</li>
<li>Scognamiglio, S., Maggi, M. and Wüthrich, M.V. (2026). <em>Deep Learning for Actuarial Modeling</em>, SSRN 5162304.</li>
</ul>
</section>

</main>
<!-- /main column -->
</div> <!-- /content -->




</body></html>