<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mario Ervedosa, adapting Scognamiglio, Maggi and Wüthrich">
<meta name="dcterms.date" content="2026-09-02">

<title>Credit Lecture 7: Balance Property, Auto-Calibration and Lift Charts</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>



  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../lectures/lecture.css">
</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#unbiasedness-in-a-credit-model" id="toc-unbiasedness-in-a-credit-model" class="nav-link" data-scroll-target="#unbiasedness-in-a-credit-model"><span class="header-section-number">1</span> Unbiasedness in a credit model</a>
  <ul class="collapse">
  <li><a href="#global-statistical-unbiasedness" id="toc-global-statistical-unbiasedness" class="nav-link" data-scroll-target="#global-statistical-unbiasedness"><span class="header-section-number">1.1</span> Global statistical unbiasedness</a></li>
  <li><a href="#the-balance-property" id="toc-the-balance-property" class="nav-link" data-scroll-target="#the-balance-property"><span class="header-section-number">1.2</span> The balance property</a></li>
  <li><a href="#where-the-credit-series-stands" id="toc-where-the-credit-series-stands" class="nav-link" data-scroll-target="#where-the-credit-series-stands"><span class="header-section-number">1.3</span> Where the credit series stands</a></li>
  <li><a href="#in-sample-balance-does-not-deliver-out-of-sample-unbiasedness" id="toc-in-sample-balance-does-not-deliver-out-of-sample-unbiasedness" class="nav-link" data-scroll-target="#in-sample-balance-does-not-deliver-out-of-sample-unbiasedness"><span class="header-section-number">1.4</span> In-sample balance does not deliver out-of-sample unbiasedness</a></li>
  </ul></li>
  <li><a href="#auto-calibration" id="toc-auto-calibration" class="nav-link" data-scroll-target="#auto-calibration"><span class="header-section-number">2</span> Auto-calibration</a>
  <ul class="collapse">
  <li><a href="#a-predictor-that-balances-exactly-and-cross-finances-badly" id="toc-a-predictor-that-balances-exactly-and-cross-finances-badly" class="nav-link" data-scroll-target="#a-predictor-that-balances-exactly-and-cross-finances-badly"><span class="header-section-number">2.1</span> A predictor that balances exactly and cross-finances badly</a></li>
  <li><a href="#the-actual-versus-predicted-plot" id="toc-the-actual-versus-predicted-plot" class="nav-link" data-scroll-target="#the-actual-versus-predicted-plot"><span class="header-section-number">2.2</span> The actual versus predicted plot</a></li>
  <li><a href="#local-regression-and-isotonic-regression" id="toc-local-regression-and-isotonic-regression" class="nav-link" data-scroll-target="#local-regression-and-isotonic-regression"><span class="header-section-number">2.3</span> Local regression and isotonic regression</a></li>
  </ul></li>
  <li><a href="#repairing-calibration" id="toc-repairing-calibration" class="nav-link" data-scroll-target="#repairing-calibration"><span class="header-section-number">3</span> Repairing calibration</a>
  <ul class="collapse">
  <li><a href="#two-cautions-before-a-recalibration-reaches-production" id="toc-two-cautions-before-a-recalibration-reaches-production" class="nav-link" data-scroll-target="#two-cautions-before-a-recalibration-reaches-production"><span class="header-section-number">3.1</span> Two cautions before a recalibration reaches production</a></li>
  </ul></li>
  <li><a href="#discrimination-and-the-gini-coefficient" id="toc-discrimination-and-the-gini-coefficient" class="nav-link" data-scroll-target="#discrimination-and-the-gini-coefficient"><span class="header-section-number">4</span> Discrimination and the Gini coefficient</a></li>
  <li><a href="#lift-charts" id="toc-lift-charts" class="nav-link" data-scroll-target="#lift-charts"><span class="header-section-number">5</span> Lift charts</a>
  <ul class="collapse">
  <li><a href="#the-double-lift-chart" id="toc-the-double-lift-chart" class="nav-link" data-scroll-target="#the-double-lift-chart"><span class="header-section-number">5.1</span> The double lift chart</a></li>
  </ul></li>
  <li><a href="#murphys-score-decomposition" id="toc-murphys-score-decomposition" class="nav-link" data-scroll-target="#murphys-score-decomposition"><span class="header-section-number">6</span> Murphy’s score decomposition</a></li>
  <li><a href="#calibration-under-vintage-drift" id="toc-calibration-under-vintage-drift" class="nav-link" data-scroll-target="#calibration-under-vintage-drift"><span class="header-section-number">7</span> Calibration under vintage drift</a></li>
  <li><a href="#takeaways-and-outlook" id="toc-takeaways-and-outlook" class="nav-link" data-scroll-target="#takeaways-and-outlook">Takeaways and outlook</a></li>
  <li><a href="#copyright-and-attribution" id="toc-copyright-and-attribution" class="nav-link" data-scroll-target="#copyright-and-attribution">Copyright and attribution</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Credit Lecture 7: Balance Property, Auto-Calibration and Lift Charts</h1>
<p class="subtitle lead">Deep Learning for Actuarial Modelling: a credit risk companion</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mario Ervedosa, adapting Scognamiglio, Maggi and Wüthrich </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 2, 2026</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>Lecture 7 of Deep Learning for Actuarial Modeling collects the calibration vocabulary the earlier lectures kept borrowing, and this companion pays off a debt the fourth and fifth credit lecture recorded explicitly. Three properties nest. Global statistical unbiasedness is out-of-sample and unverifiable on one dataset; the balance property is in-sample, exact for the canonical-link GLM and missed by 0.69 per cent by the network; auto-calibration asks that every price cohort finance its own defaults, which is what the supervisory expectation on a rating system is really asking for. The repair hierarchy follows, from a one-parameter intercept shift that fixes the aggregate to an isotonic recalibration that fixes every cohort. We then show that the Gini coefficient, which every credit validation pack leads on, is invariant to any strictly monotone transform of the predictions and therefore cannot see either defect: cubing the GLM’s fitted PDs leaves its Gini unchanged at 0.4364 while the portfolio’s expected loss falls by 82 per cent. Lift charts, the double lift chart and Murphy’s decomposition close the lecture, and the out-of-time window supplies a model whose discrimination is intact while its level is 35 per cent too high.</p>
  </div>
</div>


</header>


<section id="introduction" class="level1 unnumbered">
<h1 class="unnumbered">Introduction</h1>
<p>The fourth and fifth credit lecture left a promissory note. Its network beat the logistic GLM out-of-sample and, in the same breath, overshot the observed default count by 237 loans where the canonical-link GLM had been exact, and the text deferred the repair to “the calibration companion”. The sixth lecture then proved that ensembling cannot discharge the debt, because the mean of an ensemble’s predictions is the mean of its members’ means. This lecture is that companion, and it arrives with the credit reading of calibration already half written, because a rating system whose estimated PDs miss realised default rates grade by grade has a finding written against it.</p>
<p>Three properties are on the table and they nest, which is the organising claim. Global statistical unbiasedness is an out-of-sample statement about the fitting procedure, so a lender cannot check it. The balance property is its in-sample counterpart, which is cheap to verify and exact for a maximum likelihood GLM under the canonical link. Auto-calibration is stronger than both. Whereas balance constrains the portfolio as a whole, auto-calibration demands that every price cohort be self-financing on its own. Consequently we show what each property buys with a predictor built from the Bondora book, which satisfies the balance property exactly while charging its safest decile 13.7 percentage points more than that decile costs and its riskiest 23.4 percentage points less.</p>
<p>The diagnostics then follow the source deck: the actual versus predicted plot under quantile binning, its smooth versions under local and isotonic regression, the lift chart, the double lift chart, and Murphy’s score decomposition. One appendix of the course deserves promotion to the main argument here. Although the Gini coefficient is the headline discrimination measure in every credit validation pack, it is purely rank based, and it is therefore blind by construction to everything this lecture is about.</p>
<p>Two conventions carry over from the credit series and differ from the course. There is no exposure offset, since <code>default_12m</code> is a zero-one flag over a fixed twelve-month window, so every bin average below is an unweighted default rate and the case weights <span class="math inline">\(v_i\)</span> of the source deck are all one. Second, the Bondora book defaults at about 29 per cent, so deciles are richly populated and these diagnostics are stable. On a low-default portfolio, by contrast, each grade carries single-digit default counts, so decile binning collapses and the regulatory apparatus reaches for exact binomial tests instead. That machinery belongs to the IRB lecture rather than to this one.</p>
<div id="e5bdfd93" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Imports and shared settings</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> polars <span class="im">as</span> pl</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.optimize <span class="im">import</span> brentq</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.isotonic <span class="im">import</span> IsotonicRegression</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> roc_auc_score, roc_curve</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.nonparametric.smoothers_lowess <span class="im">import</span> lowess</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>BLUE, RED, GREY <span class="op">=</span> <span class="st">"#3B4A75"</span>, <span class="st">"#8C2F1E"</span>, <span class="st">"#8A8377"</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>plt.rcParams.update({<span class="st">"figure.dpi"</span>: <span class="dv">150</span>, <span class="st">"font.size"</span>: <span class="dv">9</span>,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"axes.spines.top"</span>: <span class="va">False</span>, <span class="st">"axes.spines.right"</span>: <span class="va">False</span>})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="unbiasedness-in-a-credit-model" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Unbiasedness in a credit model</h1>
<p>The source deck opens by observing that unbiasedness matters in actuarial pricing whatever meaning one attaches to the word, and it then lists four meanings. Each has a credit counterpart worth naming before the formal definitions begin.</p>
<p>An in-sample bias has to be avoided during model selection, since a predictor chosen on its in-sample loss generalises poorly. Indeed the credit series has already met this in the guise of encoding leakage, where the sixth lecture measured up to 1.33 deviance points of pure illusion that an in-sample check could not see. Separately, an estimated regression model should carry no statistical bias, so that the average level is right; for a lender that level is the portfolio’s expected loss and the capital plan built on it. Third, the intercept of a GLM is called the bias term in machine learning, and it turns out to be the instrument of the first repair below. Fourth, algorithmic decision making raises the question of unfair discrimination, which in consumer lending is a live regulatory concern in its own right and is out of scope here.</p>
<section id="global-statistical-unbiasedness" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="global-statistical-unbiasedness"><span class="header-section-number">1.1</span> Global statistical unbiasedness</h2>
<p>An estimated model <span class="math inline">\(\widehat{\mu}_{\mathcal{L}}\)</span>, fitted on a learning sample <span class="math inline">\(\mathcal{L} = (Y_i, \boldsymbol{X}_i, v_i)_{i=1}^n\)</span>, is globally statistically unbiased if</p>
<p><span class="math display">\[
\mathbb{E}\left[v\,\widehat{\mu}_{\mathcal{L}}(\boldsymbol{X})\right]
= \mathbb{E}\left[v\,Y\right],
\]</span></p>
<p>for a new observation <span class="math inline">\((Y, \boldsymbol{X}, v)\)</span> independent of <span class="math inline">\(\mathcal{L}\)</span>. Two features of the definition decide how useful it is in practice. It is an out-of-sample statement, since the expectation runs over fresh data rather than over the fitted sample, and verifying it requires both knowledge of <span class="math inline">\(\mathbb{E}[vY]\)</span> and the ability to resample <span class="math inline">\(\mathcal{L}\)</span>. Consequently a lender holding one loan book and one history cannot check it directly. Consequently the property is a statement about the fitting procedure, and it is not a test a validator can run.</p>
</section>
<section id="the-balance-property" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="the-balance-property"><span class="header-section-number">1.2</span> The balance property</h2>
<p>The in-sample counterpart is verifiable, and it is the one a scorecard team has always used.</p>
<p><strong>Definition.</strong> A fitting procedure <span class="math inline">\(\mathcal{L} \mapsto \widehat{\mu}_{\mathcal{L}}\)</span> satisfies the balance property if, for almost every realisation of the learning sample,</p>
<p><span class="math display">\[
\sum_{i=1}^n v_i\, \widehat{\mu}_{\mathcal{L}}(\boldsymbol{X}_i)
= \sum_{i=1}^n v_i Y_i .
\]</span></p>
<p>Since <span class="math inline">\(v_i \equiv 1\)</span> here and <span class="math inline">\(Y_i\)</span> is the default flag, the left side is the sum of fitted PDs while the right side is the observed default count. The property was introduced in credibility theory by Bühlmann and Gisler (2005) and is studied in general form by Lindholm and Wüthrich (2025). Crucially it needs no knowledge of the true mean, because it is a re- allocation of the portfolio’s total defaults across borrowers rather than a claim about their level. The second credit lecture proved that a maximum likelihood GLM under the canonical link satisfies it, and called the result calibration in the large. For the Bernoulli response of a PD model that canonical link is the logit.</p>
<p>The mathematical result is sharp in a way worth restating. Balance holds for the canonical link and, in general, for that link alone; a probit or complementary log-log fit to the same data is a maximum likelihood fit that does not balance. Where balance fails, the standard repair adjusts the intercept. Furthermore a repair may be needed even where it held, because the forward default level can shift for reasons the covariates do not carry, which is the concept-drift problem of Brauer, Menzel and Wüthrich (2025).</p>
</section>
<section id="where-the-credit-series-stands" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="where-the-credit-series-stands"><span class="header-section-number">1.3</span> Where the credit series stands</h2>
<p>We rebuild the fourth and fifth lecture’s two models exactly, with the same modelling frame, the same seeds, and the same architecture, so that every number below reconciles with that lecture exactly.</p>
<div id="3b9f7c15" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Modelling table, design matrix and splits (lecture 4/5, unchanged)</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>dat <span class="op">=</span> pl.read_parquet(<span class="st">"../data/bondora_pd.parquet"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>model_dat <span class="op">=</span> (</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    dat.<span class="bu">filter</span>(pl.col(<span class="st">"Age"</span>).is_not_null() <span class="op">&amp;</span> (pl.col(<span class="st">"IncomeTotal"</span>) <span class="op">&gt;</span> <span class="dv">0</span>))</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    .with_columns(logIncome<span class="op">=</span>pl.col(<span class="st">"IncomeTotal"</span>).log())</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(pl.col(<span class="st">"Education"</span>) <span class="op">!=</span> <span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>g <span class="op">=</span> model_dat.select(</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"default_12m"</span>, <span class="st">"Age"</span>, <span class="st">"logIncome"</span>, <span class="st">"Country"</span>, <span class="st">"Education"</span>,</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>     <span class="st">"HomeOwnershipType"</span>, <span class="st">"NewCreditCustomer"</span>, <span class="st">"VerificationType"</span>,</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>     <span class="st">"EmploymentDurationCurrentEmployer"</span>, <span class="st">"LoanDate"</span>]).to_pandas()</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>g[<span class="st">"AgeClass"</span>] <span class="op">=</span> pd.cut(</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    g[<span class="st">"Age"</span>], [<span class="dv">18</span>, <span class="dv">20</span>, <span class="dv">25</span>, <span class="dv">30</span>, <span class="dv">40</span>, <span class="dv">50</span>, <span class="dv">60</span>, <span class="dv">101</span>],</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    labels<span class="op">=</span>[<span class="st">"18-20"</span>, <span class="st">"21-25"</span>, <span class="st">"26-30"</span>, <span class="st">"31-40"</span>, <span class="st">"41-50"</span>, <span class="st">"51-60"</span>, <span class="st">"61+"</span>],</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    include_lowest<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>ho <span class="op">=</span> g[<span class="st">"HomeOwnershipType"</span>]</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>g[<span class="st">"HomeOwnership"</span>] <span class="op">=</span> np.where(ho.isna() <span class="op">|</span> (ho <span class="op">==</span> <span class="op">-</span><span class="dv">1</span>), <span class="st">"missing"</span>,</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>                              ho.fillna(<span class="op">-</span><span class="dv">1</span>).astype(<span class="bu">int</span>).astype(<span class="bu">str</span>))</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>g[<span class="st">"EmploymentDuration"</span>] <span class="op">=</span> g[<span class="st">"EmploymentDurationCurrentEmployer"</span>].fillna(<span class="st">"missing"</span>)</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>g[<span class="st">"AgeCens"</span>] <span class="op">=</span> g[<span class="st">"Age"</span>].clip(upper<span class="op">=</span><span class="dv">70</span>)</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>onehot <span class="op">=</span> pd.get_dummies(</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>    pd.DataFrame({</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Country"</span>: g[<span class="st">"Country"</span>],</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Education"</span>: g[<span class="st">"Education"</span>].astype(<span class="bu">int</span>).astype(<span class="bu">str</span>),</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>        <span class="st">"HomeOwnership"</span>: g[<span class="st">"HomeOwnership"</span>],</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>        <span class="st">"VerificationType"</span>: g[<span class="st">"VerificationType"</span>].astype(<span class="bu">int</span>).astype(<span class="bu">str</span>),</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>        <span class="st">"EmploymentDuration"</span>: g[<span class="st">"EmploymentDuration"</span>],</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>    }), prefix_sep<span class="op">=</span><span class="st">":"</span>)</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>X_all <span class="op">=</span> pd.concat([</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>    g[[<span class="st">"AgeCens"</span>, <span class="st">"logIncome"</span>]],</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>    g[<span class="st">"NewCreditCustomer"</span>].astype(<span class="bu">float</span>),</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>    onehot.astype(<span class="bu">float</span>),</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>y_all <span class="op">=</span> g[<span class="st">"default_12m"</span>].astype(<span class="bu">float</span>)</span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">1</span>)</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>perm <span class="op">=</span> rng.permutation(<span class="bu">len</span>(g))</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>n_learn <span class="op">=</span> <span class="bu">int</span>(<span class="fl">0.8</span> <span class="op">*</span> <span class="bu">len</span>(g))</span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>idx_learn_r, idx_test_r <span class="op">=</span> perm[:n_learn], perm[n_learn:]</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>learn_r, test_r <span class="op">=</span> g.iloc[idx_learn_r], g.iloc[idx_test_r]</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a>cutoff <span class="op">=</span> g[<span class="st">"LoanDate"</span>].quantile(<span class="fl">0.8</span>)</span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a>mask_t <span class="op">=</span> (g[<span class="st">"LoanDate"</span>] <span class="op">&lt;=</span> cutoff).to_numpy()</span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a>learn_t, test_t <span class="op">=</span> g[mask_t], g[<span class="op">~</span>mask_t]</span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"modelling sample n = </span><span class="sc">{</span><span class="bu">len</span>(g)<span class="sc">:,}</span><span class="ss">;  q0 = </span><span class="sc">{</span>X_all<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">}</span><span class="ss"> covariates"</span>)</span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"random split: learn </span><span class="sc">{</span><span class="bu">len</span>(learn_r)<span class="sc">:,}</span><span class="ss"> / test </span><span class="sc">{</span><span class="bu">len</span>(test_r)<span class="sc">:,}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>modelling sample n = 148,667;  q0 = 38 covariates
random split: learn 118,933 / test 29,734</code></pre>
</div>
</div>
<div id="53cbc6fc" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>GLM, network and evaluation helpers (lecture 4/5, unchanged)</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>FORMULA <span class="op">=</span> (<span class="st">"default_12m ~ AgeClass + logIncome + Country + C(Education)"</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>           <span class="st">" + C(HomeOwnership) + NewCreditCustomer + C(VerificationType)"</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>           <span class="st">" + C(EmploymentDuration)"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>glm_r <span class="op">=</span> smf.glm(FORMULA, data<span class="op">=</span>learn_r, family<span class="op">=</span>sm.families.Binomial()).fit()</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>glm_t <span class="op">=</span> smf.glm(FORMULA, data<span class="op">=</span>learn_t, family<span class="op">=</span>sm.families.Binomial()).fit()</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> bernoulli_deviance(pred, obs):</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    eps <span class="op">=</span> <span class="fl">1e-12</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    p <span class="op">=</span> np.clip(np.asarray(pred, <span class="bu">float</span>), eps, <span class="dv">1</span> <span class="op">-</span> eps)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> np.asarray(obs, <span class="bu">float</span>)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="dv">100</span> <span class="op">*</span> <span class="dv">2</span> <span class="op">*</span> np.mean(<span class="op">-</span>y <span class="op">*</span> np.log(p) <span class="op">-</span> (<span class="dv">1</span> <span class="op">-</span> y) <span class="op">*</span> np.log(<span class="dv">1</span> <span class="op">-</span> p))</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> gini(pred, obs):</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="dv">2</span> <span class="op">*</span> roc_auc_score(obs, pred) <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> make_fnn(q0, widths, seed):</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>    torch.manual_seed(seed)</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>    layers, q_prev <span class="op">=</span> [], q0</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> q_m <span class="kw">in</span> widths:</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>        layers <span class="op">+=</span> [torch.nn.Linear(q_prev, q_m), torch.nn.Tanh()]</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>        q_prev <span class="op">=</span> q_m</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>    layers <span class="op">+=</span> [torch.nn.Linear(q_prev, <span class="dv">1</span>), torch.nn.Sigmoid()]</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> torch.nn.Sequential(<span class="op">*</span>layers)</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> train_fnn(X_learn, y_learn, seed<span class="op">=</span><span class="dv">7</span>, epochs<span class="op">=</span><span class="dv">500</span>, batch<span class="op">=</span><span class="dv">5000</span>, patience<span class="op">=</span><span class="dv">50</span>):</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>    p <span class="op">=</span> np.random.default_rng(seed).permutation(<span class="bu">len</span>(X_learn))</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>    tr, va <span class="op">=</span> p[:<span class="bu">int</span>(<span class="fl">0.9</span> <span class="op">*</span> <span class="bu">len</span>(p))], p[<span class="bu">int</span>(<span class="fl">0.9</span> <span class="op">*</span> <span class="bu">len</span>(p)):]</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>    m_hat, s_hat <span class="op">=</span> X_learn.iloc[tr].mean(), X_learn.iloc[tr].std()</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>    s_hat <span class="op">=</span> s_hat.replace(<span class="dv">0</span>, <span class="fl">1.0</span>)</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> prep(df):</span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> torch.tensor(((df <span class="op">-</span> m_hat) <span class="op">/</span> s_hat).to_numpy(dtype<span class="op">=</span>np.float32))</span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>    Xtr, Xva <span class="op">=</span> prep(X_learn.iloc[tr]), prep(X_learn.iloc[va])</span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a>    ytr <span class="op">=</span> torch.tensor(y_learn.iloc[tr].to_numpy(dtype<span class="op">=</span>np.float32)).unsqueeze(<span class="dv">1</span>)</span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a>    yva <span class="op">=</span> torch.tensor(y_learn.iloc[va].to_numpy(dtype<span class="op">=</span>np.float32)).unsqueeze(<span class="dv">1</span>)</span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a>    model <span class="op">=</span> make_fnn(X_learn.shape[<span class="dv">1</span>], widths<span class="op">=</span>(<span class="dv">20</span>, <span class="dv">15</span>, <span class="dv">10</span>), seed<span class="op">=</span>seed)</span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a>    opt <span class="op">=</span> torch.optim.NAdam(model.parameters())</span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a>    bce <span class="op">=</span> torch.nn.BCELoss()</span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a>    gen <span class="op">=</span> torch.Generator().manual_seed(seed)</span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a>    best, best_epoch, best_state <span class="op">=</span> np.inf, <span class="dv">0</span>, <span class="va">None</span></span>
<span id="cb4-43"><a href="#cb4-43" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> epoch <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, epochs <span class="op">+</span> <span class="dv">1</span>):</span>
<span id="cb4-44"><a href="#cb4-44" aria-hidden="true" tabindex="-1"></a>        model.train()</span>
<span id="cb4-45"><a href="#cb4-45" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> chunk <span class="kw">in</span> torch.randperm(<span class="bu">len</span>(Xtr), generator<span class="op">=</span>gen).split(batch):</span>
<span id="cb4-46"><a href="#cb4-46" aria-hidden="true" tabindex="-1"></a>            opt.zero_grad()</span>
<span id="cb4-47"><a href="#cb4-47" aria-hidden="true" tabindex="-1"></a>            bce(model(Xtr[chunk]), ytr[chunk]).backward()</span>
<span id="cb4-48"><a href="#cb4-48" aria-hidden="true" tabindex="-1"></a>            opt.step()</span>
<span id="cb4-49"><a href="#cb4-49" aria-hidden="true" tabindex="-1"></a>        model.<span class="bu">eval</span>()</span>
<span id="cb4-50"><a href="#cb4-50" aria-hidden="true" tabindex="-1"></a>        <span class="cf">with</span> torch.no_grad():</span>
<span id="cb4-51"><a href="#cb4-51" aria-hidden="true" tabindex="-1"></a>            v <span class="op">=</span> <span class="dv">200</span> <span class="op">*</span> bce(model(Xva), yva).item()</span>
<span id="cb4-52"><a href="#cb4-52" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> v <span class="op">&lt;</span> best:</span>
<span id="cb4-53"><a href="#cb4-53" aria-hidden="true" tabindex="-1"></a>            best, best_epoch <span class="op">=</span> v, epoch</span>
<span id="cb4-54"><a href="#cb4-54" aria-hidden="true" tabindex="-1"></a>            best_state <span class="op">=</span> {k: t.clone() <span class="cf">for</span> k, t <span class="kw">in</span> model.state_dict().items()}</span>
<span id="cb4-55"><a href="#cb4-55" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> epoch <span class="op">-</span> best_epoch <span class="op">&gt;=</span> patience:</span>
<span id="cb4-56"><a href="#cb4-56" aria-hidden="true" tabindex="-1"></a>            <span class="cf">break</span></span>
<span id="cb4-57"><a href="#cb4-57" aria-hidden="true" tabindex="-1"></a>    model.load_state_dict(best_state)</span>
<span id="cb4-58"><a href="#cb4-58" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> model, (m_hat, s_hat), best_epoch</span>
<span id="cb4-59"><a href="#cb4-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-60"><a href="#cb4-60" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> fnn_predict(model, scaler, X):</span>
<span id="cb4-61"><a href="#cb4-61" aria-hidden="true" tabindex="-1"></a>    m_hat, s_hat <span class="op">=</span> scaler</span>
<span id="cb4-62"><a href="#cb4-62" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> torch.no_grad():</span>
<span id="cb4-63"><a href="#cb4-63" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> model(torch.tensor(</span>
<span id="cb4-64"><a href="#cb4-64" aria-hidden="true" tabindex="-1"></a>            ((X <span class="op">-</span> m_hat) <span class="op">/</span> s_hat).to_numpy(dtype<span class="op">=</span>np.float32))).squeeze(<span class="dv">1</span>).numpy()</span>
<span id="cb4-65"><a href="#cb4-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-66"><a href="#cb4-66" aria-hidden="true" tabindex="-1"></a>X_learn_r <span class="op">=</span> X_all.iloc[idx_learn_r]</span>
<span id="cb4-67"><a href="#cb4-67" aria-hidden="true" tabindex="-1"></a>fnn_r, sc_r, stop_r <span class="op">=</span> train_fnn(X_learn_r, y_all.iloc[idx_learn_r])</span>
<span id="cb4-68"><a href="#cb4-68" aria-hidden="true" tabindex="-1"></a>y_learn <span class="op">=</span> y_all.iloc[idx_learn_r].to_numpy()</span>
<span id="cb4-69"><a href="#cb4-69" aria-hidden="true" tabindex="-1"></a>y_test <span class="op">=</span> y_all.iloc[idx_test_r].to_numpy()</span>
<span id="cb4-70"><a href="#cb4-70" aria-hidden="true" tabindex="-1"></a>p_glm_l <span class="op">=</span> glm_r.fittedvalues.to_numpy()</span>
<span id="cb4-71"><a href="#cb4-71" aria-hidden="true" tabindex="-1"></a>p_glm_t <span class="op">=</span> glm_r.predict(test_r).to_numpy()</span>
<span id="cb4-72"><a href="#cb4-72" aria-hidden="true" tabindex="-1"></a>p_fnn_l <span class="op">=</span> fnn_predict(fnn_r, sc_r, X_learn_r)</span>
<span id="cb4-73"><a href="#cb4-73" aria-hidden="true" tabindex="-1"></a>p_fnn_t <span class="op">=</span> fnn_predict(fnn_r, sc_r, X_all.iloc[idx_test_r])</span>
<span id="cb4-74"><a href="#cb4-74" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"network early-stopped at epoch </span><span class="sc">{</span>stop_r<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>network early-stopped at epoch 71</code></pre>
</div>
</div>
<p>The reference numbers reproduce the fourth and fifth lecture exactly, which is the check that licenses everything below.</p>
<div id="b27feb06" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> report(label, pred, obs):</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>label<span class="sc">}</span><span class="ss">: deviance </span><span class="sc">{</span>bernoulli_deviance(pred, obs)<span class="sc">:7.3f}</span><span class="ss">   "</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"AUC </span><span class="sc">{</span>roc_auc_score(obs, pred)<span class="sc">:.4f}</span><span class="ss">   Gini </span><span class="sc">{</span>gini(pred, obs)<span class="sc">:.4f}</span><span class="ss">   "</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"mean PD </span><span class="sc">{</span>np<span class="sc">.</span>mean(pred)<span class="sc">:.5f}</span><span class="ss"> vs observed </span><span class="sc">{</span>np<span class="sc">.</span>mean(obs)<span class="sc">:.5f}</span><span class="ss">"</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>report(<span class="st">"GLM, in-sample"</span>, p_glm_l, y_learn)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>report(<span class="st">"GLM, test     "</span>, p_glm_t, y_test)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>report(<span class="st">"FNN, in-sample"</span>, p_fnn_l, y_learn)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>report(<span class="st">"FNN, test     "</span>, p_fnn_t, y_test)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>GLM, in-sample: deviance 106.641   AUC 0.7263   Gini 0.4525   mean PD 0.28878 vs observed 0.28878
GLM, test     : deviance 108.197   AUC 0.7182   Gini 0.4364   mean PD 0.28878 vs observed 0.29209
FNN, in-sample: deviance 104.606   AUC 0.7416   Gini 0.4831   mean PD 0.29077 vs observed 0.28878
FNN, test     : deviance 107.621   AUC 0.7241   Gini 0.4481   mean PD 0.29111 vs observed 0.29209</code></pre>
</div>
</div>
<p>Now the balance property itself, in-sample, where it is a statement about counts rather than rates.</p>
<div id="a9464bcc" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> lbl, p <span class="kw">in</span> [(<span class="st">"GLM"</span>, p_glm_l), (<span class="st">"FNN"</span>, p_fnn_l)]:</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>lbl<span class="sc">}</span><span class="ss">: sum of fitted PDs </span><span class="sc">{</span>p<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:10,.2f}</span><span class="ss">   "</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"observed defaults </span><span class="sc">{</span>y_learn<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:,.0f}</span><span class="ss">   "</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"relative miss </span><span class="sc">{</span>(p.<span class="bu">sum</span>() <span class="op">/</span> y_learn.<span class="bu">sum</span>() <span class="op">-</span> <span class="dv">1</span>) <span class="op">*</span> <span class="dv">100</span><span class="sc">:+.4f}</span><span class="ss">%"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>GLM: sum of fitted PDs  34,345.00   observed defaults 34,345   relative miss -0.0000%
FNN: sum of fitted PDs  34,582.23   observed defaults 34,345   relative miss +0.6907%</code></pre>
</div>
</div>
<p>The GLM reproduces the 34,345 observed defaults to machine precision, as the score equations require. The network’s fitted PDs, by contrast, sum to 34,582, an overshoot of 237 defaults or 0.69 per cent of the portfolio’s total, which it commits while holding the better deviance. Read as an expected loss, a 0.69 per cent overstatement of a book’s default count is small enough to survive a glance and large enough to matter in a capital plan. Moreover it is entirely invisible in the deviance table above, because deviance rewards the fit at every borrower and never audits the total. The sixth lecture’s twenty-network ensemble misses by <span class="math inline">\(-0.42\)</span> per cent, which is the average of its members’ misses. Hence averaging compresses the seed-to-seed dispersion in the miss, although it leaves the shared component untouched.</p>
</section>
<section id="in-sample-balance-does-not-deliver-out-of-sample-unbiasedness" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="in-sample-balance-does-not-deliver-out-of-sample-unbiasedness"><span class="header-section-number">1.4</span> In-sample balance does not deliver out-of-sample unbiasedness</h2>
<p>The distinction between the two properties is easy to state and easier to forget, so it is worth measuring. The GLM balances exactly on the learning sample. Applied to the held-out test sample it does not.</p>
<div id="62251f98" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> lbl, p <span class="kw">in</span> [(<span class="st">"GLM"</span>, p_glm_t), (<span class="st">"FNN"</span>, p_fnn_t)]:</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>lbl<span class="sc">}</span><span class="ss">: sum of predicted PDs </span><span class="sc">{</span>p<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:9,.2f}</span><span class="ss">   "</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"observed defaults </span><span class="sc">{</span>y_test<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:,.0f}</span><span class="ss">   "</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"relative miss </span><span class="sc">{</span>(p.<span class="bu">sum</span>() <span class="op">/</span> y_test.<span class="bu">sum</span>() <span class="op">-</span> <span class="dv">1</span>) <span class="op">*</span> <span class="dv">100</span><span class="sc">:+.4f}</span><span class="ss">%"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>GLM: sum of predicted PDs  8,586.44   observed defaults 8,685   relative miss -1.1348%
FNN: sum of predicted PDs  8,655.72   observed defaults 8,685   relative miss -0.3371%</code></pre>
</div>
</div>
<p>On the test sample the exactly balanced GLM understates the observed 8,685 defaults by 1.13 per cent, whereas the network that overshot in- sample understates by only 0.34 per cent. The arithmetic is unremarkable, because the test sample happens to default at 29.21 per cent against the learning sample’s 28.88 per cent, and an 80/20 random split of 148,667 loans leaves that much sampling variation in the response level alone. The reading is the one the definitions imply. An in-sample identity constrains the fit, although it makes no promise about a fresh sample. Consequently a validator who checks calibration in the large on the development sample has verified an algebraic property of the estimator rather than the accuracy of the level.</p>
</section>
</section>
<section id="auto-calibration" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Auto-calibration</h1>
<p><strong>Definition.</strong> A regression function <span class="math inline">\(\mu: \mathcal{X} \to \mathbb{R}\)</span> is auto-calibrated for <span class="math inline">\((Y, \boldsymbol{X})\)</span> if, almost surely,</p>
<p><span class="math display">\[
\mu(\boldsymbol{X}) = \mathbb{E}\left[\left. Y \,\right|\, \mu(\boldsymbol{X})\right].
\]</span></p>
<p>The condition asks that the set of borrowers who receive a given PD default at that rate. Every price cohort is then self-financing for its own claims, so no systematic cross-financing runs between cohorts. In insurance pricing that is the requirement that a tariff cell collect the premium its own claims cost; in credit it is the requirement that a rating grade’s assigned PD match the default rate realised inside the grade, which is what a supervisor examines grade by grade when it tests the calibration of a rating system.</p>
<p>Auto-calibration is strictly stronger than the balance property, because averaging the defining identity over the portfolio recovers balance in expectation, whereas balance says nothing about any individual cohort. Since the gap between the two is where a credit model does its real damage, it is worth building one from the Bondora book directly.</p>
<section id="a-predictor-that-balances-exactly-and-cross-finances-badly" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="a-predictor-that-balances-exactly-and-cross-finances-badly"><span class="header-section-number">2.1</span> A predictor that balances exactly and cross-finances badly</h2>
<p>Take the GLM’s test predictions and shrink them towards the portfolio mean by a factor <span class="math inline">\(\lambda\)</span>,</p>
<p><span class="math display">\[
\widehat{\mu}_\lambda(\boldsymbol{X}_i)
= \bar{p} + \lambda \left( \widehat{\mu}^{\rm GLM}(\boldsymbol{X}_i) - \bar{p} \right),
\qquad \bar{p} = \frac{1}{m}\sum_{t=1}^m \widehat{\mu}^{\rm GLM}(\boldsymbol{X}_t).
\]</span></p>
<p>Because the transform is affine about the mean, the sum of predictions is unchanged for every <span class="math inline">\(\lambda\)</span> and the balance property survives exactly. It is also strictly increasing, so it preserves the risk ranking perfectly, and every rank-based statistic with it.</p>
<div id="a8260e88" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> msc_isotonic(pred, obs):</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Miscalibration in deviance points: loss less the isotonically recalibrated loss."""</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    rc <span class="op">=</span> IsotonicRegression(out_of_bounds<span class="op">=</span><span class="st">"clip"</span>).fit(pred, obs).predict(pred)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> bernoulli_deviance(pred, obs) <span class="op">-</span> bernoulli_deviance(rc, obs)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>p_bar <span class="op">=</span> p_glm_t.mean()</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> []</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> lam <span class="kw">in</span> (<span class="fl">1.0</span>, <span class="fl">0.6</span>, <span class="fl">0.3</span>):</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>    q <span class="op">=</span> p_bar <span class="op">+</span> lam <span class="op">*</span> (p_glm_t <span class="op">-</span> p_bar)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>    rows.append({<span class="st">"lambda"</span>: lam, <span class="st">"mean PD"</span>: q.mean(),</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"sum vs GLM"</span>: q.<span class="bu">sum</span>() <span class="op">/</span> p_glm_t.<span class="bu">sum</span>() <span class="op">-</span> <span class="dv">1</span>,</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Gini"</span>: gini(q, y_test),</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"deviance"</span>: bernoulli_deviance(q, y_test),</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"miscalibration"</span>: msc_isotonic(q, y_test),</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"min PD"</span>: q.<span class="bu">min</span>(), <span class="st">"max PD"</span>: q.<span class="bu">max</span>()})</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pd.DataFrame(rows).to_string(index<span class="op">=</span><span class="va">False</span>, float_format<span class="op">=</span><span class="kw">lambda</span> v: <span class="ss">f"</span><span class="sc">{</span>v<span class="sc">:.4f}</span><span class="ss">"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> lambda  mean PD  sum vs GLM   Gini  deviance  miscalibration  min PD  max PD
 1.0000   0.2888      0.0000 0.4364  108.1972          0.3310  0.0533  0.8273
 0.6000   0.2888      0.0000 0.4364  110.1371          2.2709  0.1475  0.6119
 0.3000   0.2888      0.0000 0.4364  114.2788          6.4126  0.2181  0.4503</code></pre>
</div>
</div>
<p>At <span class="math inline">\(\lambda = 0.3\)</span> the predictor is exactly as balanced as the GLM, its mean PD is identical to five decimals, and its Gini coefficient is identical at 0.4364. Its out-of-sample deviance has nevertheless deteriorated by 6.1 points, from 108.20 to 114.28, while the isotonic miscalibration term has risen from 0.33 to 6.41 deviance points. Therefore the whole of the damage sits in auto-calibration, and the decile picture shows where.</p>
<div id="b1f51862" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Decile binning helper</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> decile_table(pred, obs, k<span class="op">=</span><span class="dv">10</span>):</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Quantile-bin on the predictor; return bin counts, barycentres and actuals."""</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    qq <span class="op">=</span> np.quantile(pred, np.arange(k <span class="op">+</span> <span class="dv">1</span>) <span class="op">/</span> k)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    b <span class="op">=</span> np.ones(<span class="bu">len</span>(pred), <span class="bu">int</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> t <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, k):</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>        b <span class="op">=</span> b <span class="op">+</span> (pred <span class="op">&gt;</span> qq[t]).astype(<span class="bu">int</span>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    rows <span class="op">=</span> [{<span class="st">"bin"</span>: j, <span class="st">"n"</span>: <span class="bu">int</span>((b <span class="op">==</span> j).<span class="bu">sum</span>()),</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>             <span class="st">"pred"</span>: pred[b <span class="op">==</span> j].mean(), <span class="st">"obs"</span>: obs[b <span class="op">==</span> j].mean()}</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>            <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, k <span class="op">+</span> <span class="dv">1</span>)]</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> pd.DataFrame(rows), b</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div id="5e4ce2b3" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>q_shrunk <span class="op">=</span> p_bar <span class="op">+</span> <span class="fl">0.3</span> <span class="op">*</span> (p_glm_t <span class="op">-</span> p_bar)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="fl">7.6</span>, <span class="fl">3.5</span>), sharex<span class="op">=</span><span class="va">True</span>, sharey<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, (lbl, p) <span class="kw">in</span> <span class="bu">zip</span>(axes, [(<span class="st">"GLM"</span>, p_glm_t), (<span class="vs">r"GLM shrunk, </span><span class="dv">$</span><span class="er">\</span><span class="vs">lambda=0</span><span class="dv">.</span><span class="vs">3</span><span class="dv">$</span><span class="vs">"</span>, q_shrunk)]):</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    t, _ <span class="op">=</span> decile_table(p, y_test)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    lim <span class="op">=</span> [<span class="fl">0.0</span>, <span class="fl">0.68</span>]</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    ax.plot(lim, lim, color<span class="op">=</span><span class="st">"#C8A96A"</span>, lw<span class="op">=</span><span class="fl">1.2</span>, zorder<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    ax.plot(t[<span class="st">"pred"</span>], t[<span class="st">"obs"</span>], <span class="st">"o-"</span>, ms<span class="op">=</span><span class="dv">4</span>, lw<span class="op">=</span><span class="dv">1</span>, color<span class="op">=</span>BLUE, zorder<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    ax.set_xlim(lim)<span class="op">;</span> ax.set_ylim(lim)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">"predicted PD (decile barycentre)"</span>)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>    ax.set_title(lbl, fontsize<span class="op">=</span><span class="dv">9</span>, loc<span class="op">=</span><span class="st">"left"</span>)</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"observed default rate"</span>)</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_credit-calibration_files/figure-html/cell-10-output-1.png" width="1129" height="510" class="figure-img"></p>
<figcaption>Actual against predicted default rate by decile of the predictor, out-of-sample. The left panel is the logistic GLM, whose deciles sit close to the diagonal. The right panel is the same GLM shrunk 70 per cent towards the portfolio mean, which holds the balance property exactly and preserves the risk ranking exactly. Its lowest decile is charged 23.3 per cent against a realised 9.6, and its highest is charged 38.9 against a realised 62.3, so the safest decile pays 13.7 percentage points more than it costs while the riskiest pays 23.4 points less.</figcaption>
</figure>
</div>
</div>
</div>
<p>Every dot below the diagonal is a cohort paying more than it costs, while every dot above it is a cohort paying less, so the vertical gap is the transfer. The shrunk predictor is thus the course’s cross-financing cartoon drawn from a real loan book, and it makes the hierarchy concrete. Global unbiasedness constrains the level in expectation, the balance property constrains the level in sample, and auto-calibration constrains every cohort. A credit model can satisfy the first two exactly and still misprice its safest borrowers by a factor of 2.4.</p>
</section>
<section id="the-actual-versus-predicted-plot" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="the-actual-versus-predicted-plot"><span class="header-section-number">2.2</span> The actual versus predicted plot</h2>
<p>The diagnostic used above is the actual versus predicted plot, and its recipe is worth stating precisely, because the binning variable decides what the plot means. One puts the observations <span class="math inline">\(Y\)</span> on the vertical axis against the predictions <span class="math inline">\(\widehat{\mu}(\boldsymbol{X})\)</span> on the horizontal, bins on quantiles of the predictions to reduce volatility, and takes empirical means within each bin for both. The horizontal coordinate of each dot is therefore the barycentre of the predictions in that decile rather than the decile’s midpoint. Furthermore, where the model has been fitted on <span class="math inline">\(\mathcal{L}\)</span>, the plot belongs on the test sample <span class="math inline">\(\mathcal{T}\)</span>, because an in-sample version flatters a flexible model.</p>
<div id="3ce4505a" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>tab_glm, _ <span class="op">=</span> decile_table(p_glm_t, y_test)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>tab_fnn, _ <span class="op">=</span> decile_table(p_fnn_t, y_test)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>show <span class="op">=</span> pd.concat([tab_glm.set_index(<span class="st">"bin"</span>), tab_fnn.set_index(<span class="st">"bin"</span>)],</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>                 axis<span class="op">=</span><span class="dv">1</span>, keys<span class="op">=</span>[<span class="st">"GLM"</span>, <span class="st">"FNN"</span>])</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(show.to_string(float_format<span class="op">=</span><span class="kw">lambda</span> v: <span class="ss">f"</span><span class="sc">{</span>v<span class="sc">:.4f}</span><span class="ss">"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      GLM                 FNN              
        n   pred    obs     n   pred    obs
bin                                        
1    2974 0.1020 0.0962  2974 0.0764 0.0989
2    2973 0.1282 0.1419  2973 0.1105 0.1228
3    2976 0.1495 0.1505  2973 0.1430 0.1534
4    2971 0.1735 0.1871  2975 0.1758 0.1825
5    2974 0.2056 0.2135  2973 0.2160 0.2193
6    2972 0.2577 0.2756  2972 0.2696 0.2736
7    2975 0.3331 0.3445  2974 0.3395 0.3315
8    2972 0.4144 0.4051  2973 0.4166 0.4218
9    2973 0.5020 0.4837  2973 0.5092 0.4968
10   2974 0.6218 0.6227  2974 0.6544 0.6204</code></pre>
</div>
</div>
<div id="df7f924a" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="fl">7.6</span>, <span class="fl">3.5</span>), sharex<span class="op">=</span><span class="va">True</span>, sharey<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, (lbl, t) <span class="kw">in</span> <span class="bu">zip</span>(axes, [(<span class="st">"GLM"</span>, tab_glm), (<span class="st">"FNN"</span>, tab_fnn)]):</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    lim <span class="op">=</span> [<span class="fl">0.05</span>, <span class="fl">0.70</span>]</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    ax.plot(lim, lim, color<span class="op">=</span><span class="st">"#C8A96A"</span>, lw<span class="op">=</span><span class="fl">1.2</span>, zorder<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    ax.plot(t[<span class="st">"pred"</span>], t[<span class="st">"obs"</span>], <span class="st">"o-"</span>, ms<span class="op">=</span><span class="dv">4</span>, lw<span class="op">=</span><span class="dv">1</span>, color<span class="op">=</span>BLUE, zorder<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    ax.set_xlim(lim)<span class="op">;</span> ax.set_ylim(lim)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">"predicted PD (decile barycentre)"</span>)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    ax.set_title(lbl, fontsize<span class="op">=</span><span class="dv">9</span>, loc<span class="op">=</span><span class="st">"left"</span>)</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"observed default rate"</span>)</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()<span class="op">;</span> plt.show()</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> lbl, t <span class="kw">in</span> [(<span class="st">"GLM"</span>, tab_glm), (<span class="st">"FNN"</span>, tab_fnn)]:</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>lbl<span class="sc">}</span><span class="ss">: actuals monotone </span><span class="sc">{</span><span class="bu">bool</span>(np.<span class="bu">all</span>(np.diff(t[<span class="st">'obs'</span>]) <span class="op">&gt;</span> <span class="dv">0</span>))<span class="sc">}</span><span class="ss">;  "</span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"largest within-decile miss </span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">abs</span>(t[<span class="st">'obs'</span>] <span class="op">-</span> t[<span class="st">'pred'</span>])<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.4f}</span><span class="ss">;  "</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"predicted spread </span><span class="sc">{</span>t[<span class="st">'pred'</span>]<span class="sc">.</span>iloc[<span class="op">-</span><span class="dv">1</span>] <span class="op">/</span> t[<span class="st">'pred'</span>]<span class="sc">.</span>iloc[<span class="dv">0</span>]<span class="sc">:.2f}</span><span class="ss">x, "</span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"realised spread </span><span class="sc">{</span>t[<span class="st">'obs'</span>]<span class="sc">.</span>iloc[<span class="op">-</span><span class="dv">1</span>] <span class="op">/</span> t[<span class="st">'obs'</span>]<span class="sc">.</span>iloc[<span class="dv">0</span>]<span class="sc">:.2f}</span><span class="ss">x"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_credit-calibration_files/figure-html/cell-12-output-1.png" width="1129" height="511" class="figure-img"></p>
<figcaption>Actual against predicted plot by decile binning on the random split’s test sample, GLM in the left panel and network in the right. Both sets of actuals are monotone in the predictor, so both models rank risk correctly at decile resolution. The GLM’s largest within-decile miss is 1.8 percentage points and the network’s is 3.4, at the two ends of its range: the network charges its lowest decile 7.6 per cent against a realised 9.9 and its highest 65.4 against a realised 62.0.</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>GLM: actuals monotone True;  largest within-decile miss 0.0183;  predicted spread 6.10x, realised spread 6.48x
FNN: actuals monotone True;  largest within-decile miss 0.0340;  predicted spread 8.57x, realised spread 6.28x</code></pre>
</div>
</div>
<p>The two models fail in opposite directions, which the spreads name. Since the GLM’s top decile is charged 6.10 times its bottom decile and realises 6.48, it under-spreads, and its extreme cohorts are slightly under-differentiated. The network, conversely, charges 8.57 times and realises 6.28, so it over-spreads, and roughly a quarter of the discrimination it claims at the extremes is not there. For a lender the two errors are not interchangeable. Under-spreading leaves margin on the table at the good end while pricing the bad end too kindly, whereas over-spreading declines business that would have performed and, at the top of the range, over-provisions against a risk the cohort does not carry.</p>
</section>
<section id="local-regression-and-isotonic-regression" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="local-regression-and-isotonic-regression"><span class="header-section-number">2.3</span> Local regression and isotonic regression</h2>
<p>Decile binning imposes ten bins by fiat, so two smoother readings of the same question are worth having. Local regression (Loader, 1999) fits a low-degree polynomial inside a moving window whose bandwidth is chosen so that the window holds a nearest-neighbour fraction <span class="math inline">\(\alpha\)</span> of the data. The course uses <code>locfit</code> in R with quadratic splines at <span class="math inline">\(\alpha =
10\%\)</span>, whereas the Python counterpart here is <code>lowess</code>, which is locally linear. The substantive hyper-parameters are nonetheless the same, and both smoothers are sensitive to them, which is the objection.</p>
<p>Isotonic regression, by contrast, answers the same question with no hyper-parameter at all. It returns the monotone step function closest to the actuals in squared error, its blocks are found by pool-adjacent- violators, and the result is exactly the recalibrated predictor <span class="math inline">\(\mu_{\rm rc}(\boldsymbol{X}) = \mathbb{E}[Y \mid \mu(\boldsymbol{X})]\)</span> that the definition of auto-calibration asks for. Fitted on the sample it is being read on, it is therefore empirically auto-calibrated by construction, which is the point Wüthrich and Ziegel (2024) make.</p>
<div id="24b08128" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="fl">7.6</span>, <span class="fl">3.5</span>), sharex<span class="op">=</span><span class="va">True</span>, sharey<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, (lbl, p) <span class="kw">in</span> <span class="bu">zip</span>(axes, [(<span class="st">"GLM"</span>, p_glm_t), (<span class="st">"FNN"</span>, p_fnn_t)]):</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>    lo <span class="op">=</span> lowess(y_test, p, frac<span class="op">=</span><span class="fl">0.1</span>, it<span class="op">=</span><span class="dv">0</span>, delta<span class="op">=</span><span class="fl">0.001</span>, return_sorted<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    rc <span class="op">=</span> IsotonicRegression(out_of_bounds<span class="op">=</span><span class="st">"clip"</span>).fit(p, y_test).predict(p)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    order <span class="op">=</span> np.argsort(p)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    lim <span class="op">=</span> [<span class="fl">0.0</span>, <span class="fl">0.85</span>]</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>    ax.plot(lim, lim, color<span class="op">=</span><span class="st">"#C8A96A"</span>, lw<span class="op">=</span><span class="fl">1.2</span>, zorder<span class="op">=</span><span class="dv">1</span>, label<span class="op">=</span><span class="st">"auto-calibration"</span>)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>    ax.plot(lo[:, <span class="dv">0</span>], lo[:, <span class="dv">1</span>], color<span class="op">=</span>GREY, lw<span class="op">=</span><span class="fl">1.2</span>, zorder<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">"local regression"</span>)</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>    ax.plot(p[order], rc[order], color<span class="op">=</span>BLUE, lw<span class="op">=</span><span class="fl">1.4</span>, zorder<span class="op">=</span><span class="dv">3</span>, label<span class="op">=</span><span class="st">"isotonic"</span>)</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>    ax.set_xlim(lim)<span class="op">;</span> ax.set_ylim(lim)</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">"predicted PD"</span>)<span class="op">;</span> ax.set_title(lbl, fontsize<span class="op">=</span><span class="dv">9</span>, loc<span class="op">=</span><span class="st">"left"</span>)</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"observed default rate"</span>)</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].legend(fontsize<span class="op">=</span><span class="fl">7.5</span>, frameon<span class="op">=</span><span class="va">False</span>, loc<span class="op">=</span><span class="st">"upper left"</span>)</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()<span class="op">;</span> plt.show()</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> lbl, p <span class="kw">in</span> [(<span class="st">"GLM"</span>, p_glm_t), (<span class="st">"FNN"</span>, p_fnn_t)]:</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>    rc <span class="op">=</span> IsotonicRegression(out_of_bounds<span class="op">=</span><span class="st">"clip"</span>).fit(p, y_test).predict(p)</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>lbl<span class="sc">}</span><span class="ss">: isotonic blocks </span><span class="sc">{</span>np<span class="sc">.</span>unique(rc)<span class="sc">.</span>size<span class="sc">:3d}</span><span class="ss">;  "</span></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"largest |prediction - recalibrated| </span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">abs</span>(p <span class="op">-</span> rc)<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.4f}</span><span class="ss">;  "</span></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"miscalibration </span><span class="sc">{</span>msc_isotonic(p, y_test)<span class="sc">:.4f}</span><span class="ss"> deviance points"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_credit-calibration_files/figure-html/cell-13-output-1.png" width="1129" height="511" class="figure-img"></p>
<figcaption>Smooth actual against predicted readings on the test sample. The grey line is a locally linear regression at a nearest-neighbour fraction of 10 per cent, the blue step function is an isotonic regression of the actuals on the predictions, and the gold diagonal is exact auto-calibration. Both models track the diagonal closely across the bulk of the range. Above a predicted 0.6 the network’s isotonic curve flattens beneath the diagonal, charging that tail a mean 67.4 per cent against a realised 64.1, and both step functions then jump to 1.0 in their terminal block, which is the end-of-range overfitting the next section has to handle.</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>GLM: isotonic blocks  48;  largest |prediction - recalibrated| 0.1783;  miscalibration 0.3310 deviance points
FNN: isotonic blocks  50;  largest |prediction - recalibrated| 0.0935;  miscalibration 0.4014 deviance points</code></pre>
</div>
</div>
<p>Both models come out close to auto-calibrated on this book. Although the isotonic recalibration moves the GLM’s predictions by as much as 17.8 percentage points and the network’s by 9.4, it buys only 0.33 and 0.40 deviance points respectively, because those largest moves fall in the sparse top tail. Against a total deviance of 108, a miscalibration of a third of a point is 0.3 per cent of the loss, so the Bondora fits leave very little on the table at cohort level. A repair can only recover what miscalibration costs, which is the constraint the next section runs into.</p>
</section>
</section>
<section id="repairing-calibration" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Repairing calibration</h1>
<p>Two repairs are available, and they sit in a hierarchy. Since both are applied after the fit, neither disturbs the model that produced the ranking.</p>
<p>The intercept correction adds a constant on the linear predictor scale, choosing <span class="math inline">\(c\)</span> so that the mean prediction matches the observed rate. It has one parameter and it restores the balance property exactly, although it can do nothing about any individual cohort. In the third credit lecture’s vocabulary it is therefore the degenerate combined actuarial neural network, whose network component is switched off.</p>
<p>The isotonic recalibration replaces <span class="math inline">\(\widehat{\mu}\)</span> by <span class="math inline">\(\widehat{\mu}_{\rm rc} = \widehat{\mathbb{E}}[Y \mid \widehat{\mu}]\)</span>, estimated by isotonic regression. It restores auto-calibration empirically on whatever sample it was fitted on, and therefore restores balance as a by-product. Moreover, because it is monotone, it leaves the risk ranking untouched up to the ties it creates.</p>
<div id="d37e04c3" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> logit(p):</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>    p <span class="op">=</span> np.clip(p, <span class="fl">1e-12</span>, <span class="dv">1</span> <span class="op">-</span> <span class="fl">1e-12</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.log(p <span class="op">/</span> (<span class="dv">1</span> <span class="op">-</span> p))</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> expit(x):</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="dv">1</span> <span class="op">/</span> (<span class="dv">1</span> <span class="op">+</span> np.exp(<span class="op">-</span>x))</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>c_star <span class="op">=</span> brentq(<span class="kw">lambda</span> c: expit(logit(p_fnn_l) <span class="op">+</span> c).mean() <span class="op">-</span> y_learn.mean(), <span class="op">-</span><span class="dv">5</span>, <span class="dv">5</span>)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>p_ic_l, p_ic_t <span class="op">=</span> expit(logit(p_fnn_l) <span class="op">+</span> c_star), expit(logit(p_fnn_t) <span class="op">+</span> c_star)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>iso_L <span class="op">=</span> IsotonicRegression(out_of_bounds<span class="op">=</span><span class="st">"clip"</span>).fit(p_fnn_l, y_learn)</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>p_iso_l, p_iso_t <span class="op">=</span> iso_L.predict(p_fnn_l), iso_L.predict(p_fnn_t)</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"intercept shift on the logit scale: c* = </span><span class="sc">{</span>c_star<span class="sc">:+.6f}</span><span class="ss">"</span>)</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"isotonic recalibration: </span><span class="sc">{</span>np<span class="sc">.</span>unique(p_iso_l)<span class="sc">.</span>size<span class="sc">}</span><span class="ss"> distinct step heights "</span></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"fitted on the learning sample; applied to the test sample it assigns "</span></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"exactly zero to </span><span class="sc">{</span>(p_iso_t <span class="op">==</span> <span class="dv">0</span>)<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">}</span><span class="ss"> loans and exactly one to "</span></span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>(p_iso_t <span class="op">==</span> <span class="dv">1</span>)<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">}</span><span class="ch">\n</span><span class="ss">"</span>)</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> []</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> lbl, pl_, pt_ <span class="kw">in</span> [(<span class="st">"FNN, as fitted"</span>, p_fnn_l, p_fnn_t),</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>                      (<span class="st">"FNN + intercept"</span>, p_ic_l, p_ic_t),</span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>                      (<span class="st">"FNN + isotonic"</span>, p_iso_l, p_iso_t),</span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>                      (<span class="st">"GLM, for reference"</span>, p_glm_l, p_glm_t)]:</span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>    rows.append({<span class="st">"predictor"</span>: lbl,</span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"balance miss, learn %"</span>: (pl_.<span class="bu">sum</span>() <span class="op">/</span> y_learn.<span class="bu">sum</span>() <span class="op">-</span> <span class="dv">1</span>) <span class="op">*</span> <span class="dv">100</span>,</span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"balance miss, test %"</span>: (pt_.<span class="bu">sum</span>() <span class="op">/</span> y_test.<span class="bu">sum</span>() <span class="op">-</span> <span class="dv">1</span>) <span class="op">*</span> <span class="dv">100</span>,</span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"deviance, learn"</span>: bernoulli_deviance(pl_, y_learn),</span>
<span id="cb22-28"><a href="#cb22-28" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"deviance, test"</span>: bernoulli_deviance(pt_, y_test),</span>
<span id="cb22-29"><a href="#cb22-29" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Gini, test"</span>: gini(pt_, y_test)})</span>
<span id="cb22-30"><a href="#cb22-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pd.DataFrame(rows).to_string(index<span class="op">=</span><span class="va">False</span>, float_format<span class="op">=</span><span class="kw">lambda</span> v: <span class="ss">f"</span><span class="sc">{</span>v<span class="sc">:.4f}</span><span class="ss">"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>intercept shift on the logit scale: c* = -0.011504
isotonic recalibration: 105 distinct step heights fitted on the learning sample; applied to the test sample it assigns exactly zero to 5 loans and exactly one to 2

         predictor  balance miss, learn %  balance miss, test %  deviance, learn  deviance, test  Gini, test
    FNN, as fitted                 0.6907               -0.3371         104.6061        107.6206      0.4481
   FNN + intercept                 0.0000               -1.0208         104.6038        107.6251      0.4481
    FNN + isotonic                 0.0000               -0.9643         104.4753        107.9825      0.4480
GLM, for reference                -0.0000               -1.1348         106.6412        108.1972      0.4364</code></pre>
</div>
</div>
<p>Three results deserve reading slowly. The intercept correction does its job exactly, driving the in-sample balance miss from <span class="math inline">\(+0.69\)</span> per cent to zero and moving the in-sample deviance by 0.002 points and the test deviance by 0.005, which makes it the cheapest repair in this series. The direction of that in-sample move is guaranteed, because it follows from the arithmetic. Matching the mean prediction to the observed rate is precisely the score equation for a free intercept over the offset <span class="math inline">\(\log(\widehat{\mu}/(1 - \widehat{\mu}))\)</span>. Hence <span class="math inline">\(c^*\)</span> is the maximum likelihood intercept and the in-sample deviance can only improve. The isotonic recalibration also balances in-sample and improves the in-sample deviance by 0.13 points, and out of sample it is worse than the network it repaired, 107.98 against 107.62. Fitting 105 step heights on the learning sample overfits the recalibration itself, which is exactly the end-of-range overfitting that Wüthrich and Ziegel warn about. Since the miscalibration available to recover was only 0.40 points to begin with, there was never much room for the repair to pay for its own estimation.</p>
<p>The third result is the sharper one. Enforcing in-sample balance made out-of-sample balance worse, taking the network’s test miss from <span class="math inline">\(-0.34\)</span> per cent to <span class="math inline">\(-1.02\)</span> per cent, which lands it beside the GLM’s <span class="math inline">\(-1.13\)</span>. The network’s in-sample overshoot had been partly offsetting the test sample’s higher default rate, and removing the overshoot removed the offset. Hence a balance correction should be understood as the removal of an in-sample artefact rather than as an improvement in the level, and a model owner who claims the latter is claiming something the split cannot support.</p>
<section id="two-cautions-before-a-recalibration-reaches-production" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="two-cautions-before-a-recalibration-reaches-production"><span class="header-section-number">3.1</span> Two cautions before a recalibration reaches production</h2>
<p>An isotonic recalibration assigns each block the observed default rate inside it, so a block containing no defaults receives a PD of exactly zero. On the test sample above the recalibrated network assigns exactly zero to five loans and exactly one to two more. A PD of zero is inadmissible in a regulatory model, because the CRR carries a floor of 0.03 per cent on non-defaulted exposures. It is also inadmissible arithmetically, since a single default inside such a block makes the log likelihood infinite. Any production recalibration therefore needs a floor and a cap, and the choice of both is a modelling decision to be documented rather than a default to be inherited from a library.</p>
<p>Second, because both repairs are monotone in the original score, neither can correct a ranking error. Where the actuals are non-monotone in the predictor, as the course’s own motor example finds and this book does not, isotonic regression imposes monotonicity by pooling the offending cohorts. Consequently the reported curve looks calibrated while the underlying model still ranks two cohorts the wrong way round. The diagnosis for a ranking failure is the lift chart below, and the remedy is a better model.</p>
</section>
</section>
<section id="discrimination-and-the-gini-coefficient" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Discrimination and the Gini coefficient</h1>
<p>Every credit validation pack this author has read leads on the Gini coefficient, and the course confines it to an appendix with a warning. The warning deserves the main text.</p>
<p>The Gini coefficient of a PD model is a linear rescaling of the area under the ROC curve,</p>
<p><span class="math display">\[
{\rm Gini} = 2\,{\rm AUC} - 1 ,
\]</span></p>
<p>so the two carry identical information, and the credit convention simply puts a random model at zero rather than at one half. On the random split the GLM scores 0.4364 out-of-sample against the network’s 0.4481, a difference of 1.2 Gini points that a scorecard team would regard as real and modest.</p>
<p>Both statistics are computed from the ordering of the predictions alone. Consequently any strictly increasing transform of a model’s predictions leaves the Gini coefficient exactly unchanged, whatever it does to the level, to the spread, or to the expected loss the model implies. Since that claim is exact rather than approximate, the demonstration takes one line per transform.</p>
<div id="5f96aff2" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>transforms <span class="op">=</span> {</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"as fitted"</span>: p_glm_t,</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"cubed"</span>: p_glm_t <span class="op">**</span> <span class="dv">3</span>,</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"square root"</span>: np.sqrt(p_glm_t),</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"halved"</span>: p_glm_t <span class="op">/</span> <span class="dv">2</span>,</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"logit shifted by +1"</span>: expit(logit(p_glm_t) <span class="op">+</span> <span class="dv">1</span>),</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> [{<span class="st">"transform"</span>: k, <span class="st">"Gini"</span>: gini(v, y_test), <span class="st">"AUC"</span>: roc_auc_score(y_test, v),</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>         <span class="st">"deviance"</span>: bernoulli_deviance(v, y_test), <span class="st">"mean PD"</span>: v.mean(),</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>         <span class="st">"balance miss %"</span>: (v.<span class="bu">sum</span>() <span class="op">/</span> y_test.<span class="bu">sum</span>() <span class="op">-</span> <span class="dv">1</span>) <span class="op">*</span> <span class="dv">100</span>,</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>         <span class="st">"miscalibration"</span>: msc_isotonic(v, y_test)}</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> k, v <span class="kw">in</span> transforms.items()]</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pd.DataFrame(rows).to_string(index<span class="op">=</span><span class="va">False</span>, float_format<span class="op">=</span><span class="kw">lambda</span> v: <span class="ss">f"</span><span class="sc">{</span>v<span class="sc">:.4f}</span><span class="ss">"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          transform   Gini    AUC  deviance  mean PD  balance miss %  miscalibration
          as fitted 0.4364 0.7182  108.1972   0.2888         -1.1348          0.3310
              cubed 0.4364 0.7182  197.3050   0.0520        -82.1814         89.4388
        square root 0.4364 0.7182  131.2633   0.5157         76.5441         23.3972
             halved 0.4364 0.7182  123.9271   0.1444        -50.5674         16.0609
logit shifted by +1 0.4364 0.7182  126.8943   0.4886         67.2621         19.0281</code></pre>
</div>
</div>
<p>Cubing the GLM’s fitted PDs leaves the Gini coefficient at 0.4364 and the AUC at 0.7182, to four decimals, while the implied default count falls by 82 per cent and the deviance rises from 108.20 to 197.31. Similarly, halving them leaves the Gini identical, although it now understates the book’s defaults by half. A validation report that leads on Gini, and reports it alone, cannot distinguish any of these five models from one another, and one of them would understate a portfolio’s expected loss by four fifths.</p>
<div id="151f5860" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="fl">7.6</span>, <span class="fl">3.6</span>))</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Marker shapes carry the two grey series apart, so the panels survive a</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="co"># greyscale print without the distinction resting on hue.</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>styles <span class="op">=</span> [(<span class="st">"as fitted"</span>, BLUE, <span class="st">"-"</span>, <span class="fl">1.8</span>, <span class="st">""</span>), (<span class="st">"cubed"</span>, RED, <span class="st">"--"</span>, <span class="fl">1.1</span>, <span class="st">""</span>),</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>          (<span class="st">"square root"</span>, GREY, <span class="st">"-."</span>, <span class="fl">1.1</span>, <span class="st">"v"</span>), (<span class="st">"halved"</span>, RED, <span class="st">":"</span>, <span class="fl">1.3</span>, <span class="st">""</span>),</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>          (<span class="st">"logit shifted by +1"</span>, GREY, <span class="st">"-"</span>, <span class="fl">1.1</span>, <span class="st">"s"</span>)]</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k, col, ls, lw, mk <span class="kw">in</span> styles:</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    fpr, tpr, _ <span class="op">=</span> roc_curve(y_test, transforms[k])</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>].plot(fpr, tpr, color<span class="op">=</span>col, ls<span class="op">=</span>ls, lw<span class="op">=</span>lw, label<span class="op">=</span>k,</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>                 marker<span class="op">=</span>mk, markersize<span class="op">=</span><span class="fl">3.5</span>, markevery<span class="op">=</span><span class="fl">0.12</span>)</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].plot([<span class="dv">0</span>, <span class="dv">1</span>], [<span class="dv">0</span>, <span class="dv">1</span>], color<span class="op">=</span><span class="st">"#C8A96A"</span>, lw<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xlabel(<span class="st">"false positive rate"</span>)<span class="op">;</span> axes[<span class="dv">0</span>].set_ylabel(<span class="st">"true positive rate"</span>)</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"ROC curves, all five coincide"</span>, fontsize<span class="op">=</span><span class="dv">9</span>, loc<span class="op">=</span><span class="st">"left"</span>)</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].legend(fontsize<span class="op">=</span><span class="dv">7</span>, frameon<span class="op">=</span><span class="va">False</span>, loc<span class="op">=</span><span class="st">"lower right"</span>)</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k, col, ls, lw, mk <span class="kw">in</span> styles:</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>    v <span class="op">=</span> transforms[k]</span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>    rc <span class="op">=</span> IsotonicRegression(out_of_bounds<span class="op">=</span><span class="st">"clip"</span>).fit(v, y_test).predict(v)</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>    o <span class="op">=</span> np.argsort(v)</span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">1</span>].plot(v[o], rc[o], color<span class="op">=</span>col, ls<span class="op">=</span>ls, lw<span class="op">=</span>lw, label<span class="op">=</span>k,</span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a>                 marker<span class="op">=</span>mk, markersize<span class="op">=</span><span class="fl">3.5</span>, markevery<span class="op">=</span><span class="fl">0.12</span>)</span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].plot([<span class="dv">0</span>, <span class="dv">1</span>], [<span class="dv">0</span>, <span class="dv">1</span>], color<span class="op">=</span><span class="st">"#C8A96A"</span>, lw<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xlim(<span class="dv">0</span>, <span class="dv">1</span>)<span class="op">;</span> axes[<span class="dv">1</span>].set_ylim(<span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xlabel(<span class="st">"predicted PD"</span>)<span class="op">;</span> axes[<span class="dv">1</span>].set_ylabel(<span class="st">"observed default rate"</span>)</span>
<span id="cb26-25"><a href="#cb26-25" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"Calibration curves, all five differ"</span>, fontsize<span class="op">=</span><span class="dv">9</span>, loc<span class="op">=</span><span class="st">"left"</span>)</span>
<span id="cb26-26"><a href="#cb26-26" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_credit-calibration_files/figure-html/cell-16-output-1.png" width="1129" height="527" class="figure-img"></p>
<figcaption>The same five predictors under two lenses. The left panel holds the ROC curves of all five, which coincide exactly because each is a strictly increasing transform of the others, so all five score a Gini of 0.4364. The right panel holds their isotonic calibration curves against the gold diagonal, where the cubed and halved variants (red) sit far above the diagonal and the square-root and logit-shifted variants (grey, marked with triangles and squares) far below. Discrimination cannot see the difference; calibration is the whole difference.</figcaption>
</figure>
</div>
</div>
</div>
<p>The course adds a second warning of a different kind. Because the Gini score is not a strictly consistent scoring function for the mean, minimising it does not identify the best predictive model, and a model selected on Gini alone has been selected on a criterion that the true regression function need not optimise. The practical corollary for a credit team is that Gini answers exactly one question, namely whether the score ranks risk correctly, and that the balance property, the actual versus predicted plot, and the decomposition below answer the others. Furthermore Brauer and Wüthrich (2025) treat the awkward cases of ties and case weights, both of which bite on a grouped credit portfolio.</p>
</section>
<section id="lift-charts" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Lift charts</h1>
<p>A lift chart carries the same statistics as the actual versus predicted plot in a layout built for comparing models. One bins on the predictor as before, then plots both the binned prediction averages and the binned response averages against the bin labels, so the horizontal axis is ordinal. Goldburd et al.&nbsp;(2020) read three things off it, and all three transfer to a scorecard unchanged.</p>
<p>Auto-calibration shows as agreement between the predictions and the actuals within each bin. Monotonicity shows as an increasing sequence of actuals, which under auto-calibration is what a correct risk ranking looks like. Discrimination, finally, shows as the gap between the lowest and the highest bin, which is the lift, so a model that separates the book more sharply has more of it.</p>
<div id="b3b85765" class="cell" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="fl">7.6</span>, <span class="fl">3.5</span>), sharey<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, (lbl, t) <span class="kw">in</span> <span class="bu">zip</span>(axes, [(<span class="st">"GLM"</span>, tab_glm), (<span class="st">"FNN"</span>, tab_fnn)]):</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>    ax.plot(t[<span class="st">"bin"</span>], t[<span class="st">"pred"</span>], <span class="st">"o"</span>, ms<span class="op">=</span><span class="dv">5</span>, color<span class="op">=</span><span class="st">"#C8873A"</span>, label<span class="op">=</span><span class="st">"predicted"</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>    ax.plot(t[<span class="st">"bin"</span>], t[<span class="st">"obs"</span>], <span class="st">"^"</span>, ms<span class="op">=</span><span class="dv">5</span>, color<span class="op">=</span>BLUE, label<span class="op">=</span><span class="st">"actual"</span>)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>    ax.vlines(t[<span class="st">"bin"</span>], np.minimum(t[<span class="st">"pred"</span>], t[<span class="st">"obs"</span>]),</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>              np.maximum(t[<span class="st">"pred"</span>], t[<span class="st">"obs"</span>]), color<span class="op">=</span>GREY, lw<span class="op">=</span><span class="fl">0.8</span>, zorder<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>    ax.set_xticks(<span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">11</span>))</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">"decile of the predictor"</span>)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>    ax.set_title(lbl, fontsize<span class="op">=</span><span class="dv">9</span>, loc<span class="op">=</span><span class="st">"left"</span>)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"default rate"</span>)</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].legend(fontsize<span class="op">=</span><span class="dv">8</span>, frameon<span class="op">=</span><span class="va">False</span>, loc<span class="op">=</span><span class="st">"upper left"</span>)</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()<span class="op">;</span> plt.show()</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> lbl, t <span class="kw">in</span> [(<span class="st">"GLM"</span>, tab_glm), (<span class="st">"FNN"</span>, tab_fnn)]:</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>lbl<span class="sc">}</span><span class="ss">: realised lift </span><span class="sc">{</span>t[<span class="st">'obs'</span>]<span class="sc">.</span>iloc[<span class="op">-</span><span class="dv">1</span>] <span class="op">/</span> t[<span class="st">'obs'</span>]<span class="sc">.</span>iloc[<span class="dv">0</span>]<span class="sc">:.3f}</span><span class="ss">x   "</span></span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"predicted lift </span><span class="sc">{</span>t[<span class="st">'pred'</span>]<span class="sc">.</span>iloc[<span class="op">-</span><span class="dv">1</span>] <span class="op">/</span> t[<span class="st">'pred'</span>]<span class="sc">.</span>iloc[<span class="dv">0</span>]<span class="sc">:.3f}</span><span class="ss">x   "</span></span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"mean |actual - predicted| </span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">abs</span>(t[<span class="st">'obs'</span>] <span class="op">-</span> t[<span class="st">'pred'</span>])<span class="sc">.</span>mean()<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_credit-calibration_files/figure-html/cell-17-output-1.png" width="1129" height="511" class="figure-img"></p>
<figcaption>Lift charts on the random split’s test sample, GLM in the left panel and network in the right. Orange circles are the binned prediction averages and blue triangles the binned realised default rates. Both models produce monotone actuals, so both rank correctly at this resolution. The network’s predictions fan wider than its actuals at both ends, which is the over-spread the decile table measured; the GLM’s sit inside its actuals at the bottom end.</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>GLM: realised lift 6.476x   predicted lift 6.098x   mean |actual - predicted| 0.0100
FNN: realised lift 6.276x   predicted lift 8.568x   mean |actual - predicted| 0.0119</code></pre>
</div>
</div>
<p>The course’s own example separates the three readings cleanly, with its first model better calibrated and its second both monotone and more discriminating, so its lift charts recommend the second. The Bondora comparison, however, is less tidy, and the reason is instructive. Since both models are monotone and both realise a lift close to 6.3 to 6.5 times, the difference between them lives almost entirely in how honestly they report their own spread. The network’s mean absolute bin miss of 1.19 percentage points is a fifth larger than the GLM’s 1.00, and its extra 1.2 Gini points came from the same widened range that costs it that calibration.</p>
<section id="the-double-lift-chart" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="the-double-lift-chart"><span class="header-section-number">5.1</span> The double lift chart</h2>
<p>A double lift chart puts both models in one picture by binning on their disagreement. With strictly positive predictions from Model 1 and Model 2, compute the ratios</p>
<p><span class="math display">\[
\kappa_t = \frac{\widehat{\mu}_2(\boldsymbol{X}_t)}{\widehat{\mu}_1(\boldsymbol{X}_t)},
\qquad 1 \le t \le m,
\]</span></p>
<p>and quantile-bin on <span class="math inline">\(\kappa\)</span>. The lowest bin holds the risks that Model 2 judges most favourably relative to Model 1, whereas the highest bin holds those it judges most harshly. The actuals then adjudicate, because the bins are selected precisely where the two models disagree.</p>
<div id="87573423" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>kappa <span class="op">=</span> p_fnn_t <span class="op">/</span> p_glm_t</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>qk <span class="op">=</span> np.quantile(kappa, np.arange(<span class="dv">11</span>) <span class="op">/</span> <span class="dv">10</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>bk <span class="op">=</span> np.ones(<span class="bu">len</span>(kappa), <span class="bu">int</span>)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> t0 <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">10</span>):</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>    bk <span class="op">=</span> bk <span class="op">+</span> (kappa <span class="op">&gt;</span> qk[t0]).astype(<span class="bu">int</span>)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>dl <span class="op">=</span> pd.DataFrame([{<span class="st">"bin"</span>: j, <span class="st">"n"</span>: <span class="bu">int</span>((bk <span class="op">==</span> j).<span class="bu">sum</span>()), <span class="st">"kappa"</span>: kappa[bk <span class="op">==</span> j].mean(),</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"GLM"</span>: p_glm_t[bk <span class="op">==</span> j].mean(), <span class="st">"FNN"</span>: p_fnn_t[bk <span class="op">==</span> j].mean(),</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"actual"</span>: y_test[bk <span class="op">==</span> j].mean()} <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">11</span>)])</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(dl.to_string(index<span class="op">=</span><span class="va">False</span>, float_format<span class="op">=</span><span class="kw">lambda</span> v: <span class="ss">f"</span><span class="sc">{</span>v<span class="sc">:.4f}</span><span class="ss">"</span>))</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>w_glm, w_fnn <span class="op">=</span> (dl[<span class="st">"GLM"</span>] <span class="op">-</span> dl[<span class="st">"actual"</span>]).<span class="bu">abs</span>(), (dl[<span class="st">"FNN"</span>] <span class="op">-</span> dl[<span class="st">"actual"</span>]).<span class="bu">abs</span>()</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">kappa ranges from </span><span class="sc">{</span>kappa<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.3f}</span><span class="ss"> to </span><span class="sc">{</span>kappa<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"mean absolute bin miss: GLM </span><span class="sc">{</span>w_glm<span class="sc">.</span>mean()<span class="sc">:.4f}</span><span class="ss">, FNN </span><span class="sc">{</span>w_fnn<span class="sc">.</span>mean()<span class="sc">:.4f}</span><span class="ss">; "</span></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"the network is closer in </span><span class="sc">{</span>(w_fnn <span class="op">&lt;</span> w_glm)<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">}</span><span class="ss"> of 10 bins"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> bin    n  kappa    GLM    FNN  actual
   1 2974 0.6150 0.2055 0.1262  0.1681
   2 2973 0.7566 0.2197 0.1664  0.1978
   3 2973 0.8405 0.2462 0.2071  0.2166
   4 2974 0.9051 0.3033 0.2748  0.2848
   5 2973 0.9648 0.3358 0.3241  0.3209
   6 2974 1.0168 0.3610 0.3672  0.3578
   7 2973 1.0657 0.3748 0.3993  0.3925
   8 2973 1.1245 0.3326 0.3738  0.3495
   9 2973 1.2096 0.2924 0.3533  0.3340
  10 2974 1.5145 0.2164 0.3189  0.2989

kappa ranges from 0.192 to 3.037
mean absolute bin miss: GLM 0.0284, FNN 0.0176; the network is closer in 6 of 10 bins</code></pre>
</div>
</div>
<div id="ad158ded" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">6.6</span>, <span class="fl">3.6</span>))</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>ax.plot(dl[<span class="st">"bin"</span>], dl[<span class="st">"GLM"</span>], <span class="st">"s-"</span>, ms<span class="op">=</span><span class="dv">4</span>, lw<span class="op">=</span><span class="dv">1</span>, color<span class="op">=</span>GREY, label<span class="op">=</span><span class="st">"GLM"</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>ax.plot(dl[<span class="st">"bin"</span>], dl[<span class="st">"FNN"</span>], <span class="st">"o-"</span>, ms<span class="op">=</span><span class="dv">4</span>, lw<span class="op">=</span><span class="dv">1</span>, color<span class="op">=</span>RED, label<span class="op">=</span><span class="st">"FNN"</span>)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>ax.plot(dl[<span class="st">"bin"</span>], dl[<span class="st">"actual"</span>], <span class="st">"^-"</span>, ms<span class="op">=</span><span class="dv">5</span>, lw<span class="op">=</span><span class="fl">1.4</span>, color<span class="op">=</span>BLUE, label<span class="op">=</span><span class="st">"actual"</span>)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>ax.set_xticks(<span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">11</span>))</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="vs">r"decile of </span><span class="dv">$</span><span class="er">\</span><span class="vs">kappa = </span><span class="dv">\w</span><span class="vs">idehat{</span><span class="dv">\m</span><span class="vs">u}</span><span class="dv">^</span><span class="vs">{</span><span class="ch">\r</span><span class="vs">m FNN} / </span><span class="dv">\w</span><span class="vs">idehat{</span><span class="dv">\m</span><span class="vs">u}</span><span class="dv">^</span><span class="vs">{</span><span class="ch">\r</span><span class="vs">m GLM}</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"default rate"</span>)</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>ax.legend(fontsize<span class="op">=</span><span class="dv">8</span>, frameon<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_credit-calibration_files/figure-html/cell-19-output-1.png" width="979" height="527" class="figure-img"></p>
<figcaption>Double lift chart on the test sample, binned on the ratio of the network’s prediction to the GLM’s. Where the two models disagree most, in the outer bins, the actuals side with the network: in the tenth bin the network charges 31.9 per cent against the GLM’s 21.6 and the cohort realises 29.9. In the first bin the network charges 12.6 against the GLM’s 20.6 and the cohort realises 16.8, so there the truth sits between them and slightly nearer the GLM.</figcaption>
</figure>
</div>
</div>
</div>
<p>The verdict favours the network, with qualifications. Its mean absolute bin miss of 1.76 percentage points beats the GLM’s 2.84, and it is closer in six bins of ten. Nevertheless the two extreme bins carry the weight of the finding. In the tenth bin, where the network is most pessimistic relative to the GLM, it misses by 2.0 percentage points against the GLM’s 8.3; in the first bin, where it is most optimistic, it misses by 4.2 against the GLM’s 3.7. Hence the network’s disagreements are right where it marks a risk up, and roughly a coin toss where it marks one down, which is a more useful summary of a model comparison than either model’s headline deviance. Since both models have weaknesses, the honest conclusion is the course’s own. A genuinely better model would beat both.</p>
</section>
</section>
<section id="murphys-score-decomposition" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Murphy’s score decomposition</h1>
<p>The diagnostics above are graphical, whereas the decomposition makes the same split arithmetic. Choose a strictly consistent scoring function <span class="math inline">\(L\)</span> for mean estimation. Murphy (1973) partitions its expectation into</p>
<p><span class="math display">\[
\mathbb{E}\left[L(Y, \mu(\boldsymbol{X}))\right]
= {\sf UNC}_L - {\sf DSC}_L + {\sf MSC}_L ,
\]</span></p>
<p>with uncertainty, discrimination and miscalibration given by</p>
<p><span class="math display">\[
\begin{aligned}
{\sf UNC}_L &amp;= \mathbb{E}\left[L(Y, \mu_0)\right] \ge 0, \\
{\sf DSC}_L &amp;= \mathbb{E}\left[L(Y, \mu_0)\right]
- \mathbb{E}\left[L(Y, \mu_{\rm rc}(\boldsymbol{X}))\right] \ge 0, \\
{\sf MSC}_L &amp;= \mathbb{E}\left[L(Y, \mu(\boldsymbol{X}))\right]
- \mathbb{E}\left[L(Y, \mu_{\rm rc}(\boldsymbol{X}))\right] \ge 0,
\end{aligned}
\]</span></p>
<p>where <span class="math inline">\(\mu_0\)</span> is the best constant predictor and <span class="math inline">\(\mu_{\rm
rc}(\boldsymbol{X}) = \mathbb{E}[Y \mid \mu(\boldsymbol{X})]\)</span> is the recalibrated version. Strict consistency gives all three signs. Uncertainty belongs to the data, so no model can improve it, while discrimination is what the model earns by separating the book, and miscalibration is what it gives back by mispricing the cohorts it has separated.</p>
<p>Credit modelling knows this partition under another name. With the squared-error scoring function the score is the Brier score, and its three terms are the reliability, resolution, and uncertainty of the classical Brier decomposition, which is the form Murphy’s 1973 paper states. Reliability is miscalibration, while resolution is discrimination. The log-loss version below is nonetheless more useful here, because it is the Bernoulli deviance the credit series has been quoting throughout, so multiplying by 200 puts the decomposition on exactly that scale.</p>
<div id="128c2308" class="cell" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> model_diagnostics.scoring <span class="im">import</span> LogLoss, SquaredError, decompose</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>preds <span class="op">=</span> pd.DataFrame({<span class="st">"GLM"</span>: p_glm_t, <span class="st">"FNN"</span>: p_fnn_t})</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, sf, scale <span class="kw">in</span> [(<span class="st">"Bernoulli deviance (log loss x 200)"</span>, LogLoss(), <span class="dv">200</span>),</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>                        (<span class="st">"Brier score (squared error)"</span>, SquaredError(), <span class="dv">1</span>)]:</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>    d <span class="op">=</span> decompose(y_obs<span class="op">=</span>y_test, y_pred<span class="op">=</span>preds, scoring_function<span class="op">=</span>sf).to_pandas()</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> c <span class="kw">in</span> [<span class="st">"miscalibration"</span>, <span class="st">"discrimination"</span>, <span class="st">"uncertainty"</span>, <span class="st">"score"</span>]:</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>        d[c] <span class="op">=</span> d[c] <span class="op">*</span> scale</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss">, test sample"</span>)</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(d.to_string(index<span class="op">=</span><span class="va">False</span>, float_format<span class="op">=</span><span class="kw">lambda</span> v: <span class="ss">f"</span><span class="sc">{</span>v<span class="sc">:.4f}</span><span class="ss">"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Bernoulli deviance (log loss x 200), test sample
model  miscalibration  discrimination  uncertainty    score
  GLM          0.3310         12.9363     120.8025 108.1972
  FNN          0.4014         13.5833     120.8025 107.6206

Brier score (squared error), test sample
model  miscalibration  discrimination  uncertainty  score
  GLM          0.0006          0.0267       0.2068 0.1807
  FNN          0.0007          0.0280       0.2068 0.1794</code></pre>
</div>
</div>
<p>On the deviance scale the reading is immediate. Uncertainty is 120.80 points for both models, because it depends on the response alone. The network then earns 13.58 points of discrimination against the GLM’s 12.94, and gives back 0.40 points of miscalibration against the GLM’s 0.33, so its score of 107.62 beats the GLM’s 108.20 by 0.58 points. The miscalibration terms reproduce the isotonic figures computed earlier exactly, which they should, since <code>decompose</code> estimates <span class="math inline">\(\mu_{\rm rc}\)</span> by isotonic regression exactly as the earlier cell did.</p>
<p>The credit conclusion is a proportion. Since the network buys 0.64 points of extra discrimination and pays only 0.07 points of extra miscalibration for it, the trade is comfortably worth making on this book, and the recalibration machinery is close to unnecessary. That verdict is specific to a portfolio defaulting at 29 per cent with a well-populated covariate space. Where the miscalibration term is instead a material fraction of the score, as the shrunk predictor’s 6.41 points against a score of 114.28 illustrates, the ranking is fine while the prices are wrong, so only a recalibration will fix it.</p>
</section>
<section id="calibration-under-vintage-drift" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Calibration under vintage drift</h1>
<p>Every result so far sits on the random split, where the learning and test samples are exchangeable. Since the second and the fourth and fifth credit lectures both carried an out-of-time contrast, and calibration is where that contrast does its worst damage, it belongs here too.</p>
<div id="c10167fc" class="cell" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>X_learn_t <span class="op">=</span> X_all[mask_t]</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>fnn_oot, sc_oot, stop_oot <span class="op">=</span> train_fnn(X_learn_t, y_all[mask_t])</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>y_oot <span class="op">=</span> y_all[<span class="op">~</span>mask_t].to_numpy()</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>p_glm_oot <span class="op">=</span> glm_t.predict(test_t).to_numpy()</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>p_fnn_oot <span class="op">=</span> fnn_predict(fnn_oot, sc_oot, X_all[<span class="op">~</span>mask_t])</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>report(<span class="st">"GLM, out-of-time test"</span>, p_glm_oot, y_oot)</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>report(<span class="st">"FNN, out-of-time test"</span>, p_fnn_oot, y_oot)</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> lbl, p <span class="kw">in</span> [(<span class="st">"GLM"</span>, p_glm_oot), (<span class="st">"FNN"</span>, p_fnn_oot)]:</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>    t, _ <span class="op">=</span> decile_table(p, y_oot)</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>lbl<span class="sc">}</span><span class="ss">: balance miss </span><span class="sc">{</span>(p.<span class="bu">sum</span>() <span class="op">/</span> y_oot.<span class="bu">sum</span>() <span class="op">-</span> <span class="dv">1</span>) <span class="op">*</span> <span class="dv">100</span><span class="sc">:+.2f}</span><span class="ss">%;  "</span></span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"every decile overcharged </span><span class="sc">{</span><span class="bu">bool</span>(np.<span class="bu">all</span>(t[<span class="st">'pred'</span>] <span class="op">&gt;</span> t[<span class="st">'obs'</span>]))<span class="sc">}</span><span class="ss">;  "</span></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"realised lift </span><span class="sc">{</span>t[<span class="st">'obs'</span>]<span class="sc">.</span>iloc[<span class="op">-</span><span class="dv">1</span>] <span class="op">/</span> t[<span class="st">'obs'</span>]<span class="sc">.</span>iloc[<span class="dv">0</span>]<span class="sc">:.2f}</span><span class="ss">x;  "</span></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"Gini </span><span class="sc">{</span>gini(p, y_oot)<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>GLM, out-of-time test: deviance 100.400   AUC 0.7158   Gini 0.4316   mean PD 0.30717 vs observed 0.22798
FNN, out-of-time test: deviance 101.329   AUC 0.7146   Gini 0.4293   mean PD 0.31558 vs observed 0.22798
GLM: balance miss +34.73%;  every decile overcharged True;  realised lift 7.49x;  Gini 0.4316
FNN: balance miss +38.42%;  every decile overcharged True;  realised lift 7.86x;  Gini 0.4293</code></pre>
</div>
</div>
<div id="df3a0e6f" class="cell" data-execution_count="21">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="fl">7.6</span>, <span class="fl">3.5</span>), sharex<span class="op">=</span><span class="va">True</span>, sharey<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, (lbl, p) <span class="kw">in</span> <span class="bu">zip</span>(axes, [(<span class="st">"GLM"</span>, p_glm_oot), (<span class="st">"FNN"</span>, p_fnn_oot)]):</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    t, _ <span class="op">=</span> decile_table(p, y_oot)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>    lim <span class="op">=</span> [<span class="fl">0.0</span>, <span class="fl">0.68</span>]</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>    ax.plot(lim, lim, color<span class="op">=</span><span class="st">"#C8A96A"</span>, lw<span class="op">=</span><span class="fl">1.2</span>, zorder<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>    ax.plot(t[<span class="st">"pred"</span>], t[<span class="st">"obs"</span>], <span class="st">"o-"</span>, ms<span class="op">=</span><span class="dv">4</span>, lw<span class="op">=</span><span class="dv">1</span>, color<span class="op">=</span>RED, zorder<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>    ax.set_xlim(lim)<span class="op">;</span> ax.set_ylim(lim)</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">"predicted PD (decile barycentre)"</span>)</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="ss">f"</span><span class="sc">{</span>lbl<span class="sc">}</span><span class="ss">, out of time"</span>, fontsize<span class="op">=</span><span class="dv">9</span>, loc<span class="op">=</span><span class="st">"left"</span>)</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"observed default rate"</span>)</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()<span class="op">;</span> plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_credit-calibration_files/figure-html/cell-22-output-1.png" width="1129" height="511" class="figure-img"></p>
<figcaption>Actual against predicted plot by decile on the out-of-time test window, the final fifth of origination dates. Every decile of both models sits below the diagonal, so every cohort is charged more than it realises, and the two models are nearly indistinguishable. The GLM overstates the window’s default count by 35 per cent and the network by 38, while both rank the book more sharply here than on the random split.</figcaption>
</figure>
</div>
</div>
</div>
<p>The out-of-time window separates the two properties more sharply than any construction on exchangeable data managed. Both models overstate the level catastrophically, by 35 and 38 per cent of the observed default count, and every one of their twenty deciles sits below the diagonal, so every cohort is overcharged and the failure is systematic rather than concentrated. Meanwhile the GLM’s realised lift rises to 7.49 times and the network’s to 7.86, both above their random-split values, and their Gini coefficients of 0.4316 and 0.4293 give up half a point and 1.9 points respectively against what they scored on exchangeable data. Hence a validation pack reporting Gini and lift would record this model as slightly better at ranking, while carrying no trace of a 35 per cent overstatement of the book’s expected loss.</p>
<p>Both repairs would work here, although neither is available honestly. An intercept shift fitted on the out-of-time actuals removes the level error in one parameter, whereas fitting it requires the realised default rates of the window being predicted, which a lender pricing today does not have. Hence the drift problem is a forecasting problem rather than a calibration problem, and the credit series takes it up on the point-in-time side, where the level is conditioned on macroeconomic covariates instead of being corrected after the fact.</p>
</section>
<section id="takeaways-and-outlook" class="level1 unnumbered">
<h1 class="unnumbered">Takeaways and outlook</h1>
<p>Three calibration properties nest, and the credit series can now name each. Global statistical unbiasedness is an out-of-sample property of the fitting procedure, so a lender with one loan book cannot verify it. The balance property is its in-sample counterpart, exact for the canonical- link GLM, although missed by 0.69 per cent by the network and by 0.42 per cent by the twenty-network ensemble. Auto-calibration, finally, asks that every cohort finance its own defaults. Consequently the shrunk predictor built here holds the balance property exactly and an identical Gini coefficient, while charging its safest decile 23.3 per cent against a realised 9.6.</p>
<p>The repairs sit in the same hierarchy. A one-parameter intercept shift restored in-sample balance for 0.002 deviance points, and it made out-of-sample balance worse, taking the network’s test miss from <span class="math inline">\(-0.34\)</span> to <span class="math inline">\(-1.02\)</span> per cent. Isotonic recalibration restores auto-calibration on the sample it is fitted on, whereas out of sample it lost 0.36 deviance points here, because 105 step heights are a lot to estimate in pursuit of 0.40 points of available miscalibration. On this book both models were already close to auto-calibrated, at 0.3 and 0.4 per cent of their respective deviances.</p>
<p>The finding worth carrying furthest concerns the industry’s own headline statistic. Since the Gini coefficient is a rescaled AUC and depends on the ordering of the predictions alone, it is exactly invariant to every strictly monotone transform of them. Cubing the GLM’s fitted PDs left its Gini at 0.4364 while understating the book’s defaults by 82 per cent. Similarly, the out-of-time window produced a model with better lift and comparable Gini while overstating the level by 35 per cent. A validation pack that leads on discrimination is reporting the one property that cannot see a pricing failure, and the balance property, the actual versus predicted plot, and Murphy’s decomposition are what see it.</p>
<p>Two threads leave this lecture for other parts of the series. The grade-level machinery, meaning risk grade construction, the long-run average default rate per grade, the margin of conservatism, and the exact binomial calibration tests that a low-default portfolio forces, belongs to the IRB capital lecture, which needs this vocabulary and adds the regulatory apparatus to it. The drift problem, meanwhile, belongs to the point-in-time lecture, where conditioning the level on macroeconomic covariates replaces correcting it afterwards. The eighth lecture then returns to the modelling thread with the ICE network and regularisation, where the balance property can be imposed during the fit rather than repaired after it.</p>
</section>
<section id="copyright-and-attribution" class="level1 unnumbered">
<h1 class="unnumbered">Copyright and attribution</h1>
<p>This document adapts the storyline, structure and notation of <em>Lecture 7: Balance Property, Auto-Calibration and Lift Charts</em> from the summer school <strong>Deep Learning for Actuarial Modeling</strong> (Scognamiglio, Maggi and Wüthrich, Università Cattolica del Sacro Cuore, Milano, 2026), part of the project <em>AI Tools for Actuaries</em>, used under CC BY-NC 4.0. Changes made: the Poisson claim-frequency thread is recast as the Bernoulli default thread on the public Bondora loan book, the code is Python with PyTorch, scikit-learn and statsmodels rather than R with <code>locfit</code>, and the following are new: the measurement that in-sample balance does not deliver out-of-sample unbiasedness, the shrinkage counterexample of a predictor that balances exactly while cross-financing badly, the under-spread and over-spread reading of the decile tables, the repair hierarchy with both repairs measured in and out of sample, the finding that an in-sample balance correction worsened out-of-sample balance, the promotion of the Gini appendix to the main argument together with the invariance table and its two-panel figure, the PD-of-zero caution on isotonic recalibration, the log-loss rescaling that reconciles Murphy’s decomposition with the series’ deviance scale, and the out-of-time calibration contrast. The numerical results concern the credit data throughout. The original lecture notes are available at <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5162304" class="uri">https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5162304</a>.</p>
</section>
<section id="references" class="level1 unnumbered">
<h1 class="unnumbered">References</h1>
<ul>
<li>Brauer, A., Menzel, P. and Wüthrich, M.V. (2025). Model monitoring: a general framework with an application to non-life insurance pricing. arXiv:2510.04556.</li>
<li>Brauer, A. and Wüthrich, M.V. (2025). Gini score under ties and case weights. arXiv:2511.15446.</li>
<li>Bühlmann, H. and Gisler, A. (2005). <em>A Course in Credibility Theory and its Applications</em>. Springer.</li>
<li>Dimitriadis, T., Gneiting, T. and Jordan, A.I. (2021). Stable reliability diagrams for probabilistic classifiers. <em>PNAS</em> 118(8).</li>
<li>Fissler, T., Lorentzen, C. and Mayer, M. (2022). Model comparison and calibration assessment. arXiv:2202.12780.</li>
<li>Gini, C. (1936). On the measure of concentration with special reference to income and statistics. <em>Colorado College Publication</em> 208, 73-79.</li>
<li>Goldburd, M., Khare, A., Tevet, D. and Guller, D. (2020). <em>Generalized Linear Models for Insurance Rating</em>, 2nd edn. Casualty Actuarial Society, CAS Monograph 5.</li>
<li>Lindholm, M. and Wüthrich, M.V. (2025). The balance property in insurance pricing. <em>Scandinavian Actuarial Journal</em>.</li>
<li>Loader, C. (1999). <em>Local Regression and Likelihood</em>. Springer.</li>
<li>Murphy, A.H. (1973). A new vector partition of the probability score. <em>Journal of Applied Meteorology and Climatology</em> 12(4), 595-600.</li>
<li>Wüthrich, M.V. and Merz, M. (2023). <em>Statistical Foundations of Actuarial Learning and its Applications</em>. Springer.</li>
<li>Wüthrich, M.V. and Ziegel, J. (2024). Isotonic recalibration under a low signal-to-noise ratio. <em>Scandinavian Actuarial Journal</em> 2024(3), 279-299.</li>
<li>Scognamiglio, S., Maggi, M. and Wüthrich, M.V. (2026). <em>Deep Learning for Actuarial Modeling</em>, SSRN 5162304.</li>
</ul>
</section>

</main>
<!-- /main column -->
</div> <!-- /content -->




</body></html>